'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{execFile}=require('child_process');

const DATE=/^\d{4}-\d{2}-\d{2}$/;
function finiteMoney(value,label,{allowZero=true}={}){
 const n=Number(value);if(!Number.isFinite(n)||n<0||(!allowZero&&n===0)||!Number.isSafeInteger(Math.round(n*100)))throw Error('Проверьте поле «'+label+'»');
 return Math.round(n*100)/100;
}
function clean(value,label,max=160,{required=true}={}){const text=String(value??'').trim();if((required&&!text)||text.length>max)throw Error('Проверьте поле «'+label+'»');return text}
function date(value,label,{required=true}={}){const text=String(value??'').trim();if(!text&&!required)return null;const parsed=new Date(text+'T00:00:00Z');if(!DATE.test(text)||Number.isNaN(parsed.getTime())||parsed.toISOString().slice(0,10)!==text)throw Error('Проверьте поле «'+label+'»');return text}
function normalizeState(raw){return {version:1,updatedAt:raw?.updatedAt||null,loans:Array.isArray(raw?.loans)?raw.loans:[],payments:Array.isArray(raw?.payments)?raw.payments:[]}}
function aggregate(stores,from,to){
 const byDate=new Map(),sources=[];let complete=true,totalCents=0,records=0,hasAny=false,hasCoveredSource=false;
 for(const store of stores){const ledger=store.ledger;if(!ledger){complete=false;sources.push({storeId:store.id,name:store.name,status:'missing',period:null,updatedAt:null});continue}
  const covers=ledger.version===3&&ledger.complete===true&&ledger.period?.from<=from&&ledger.period?.to>=to&&ledger.foreignRecords===0;
  if(!covers)complete=false;else hasCoveredSource=true;sources.push({storeId:store.id,name:store.name,status:covers?'complete':'partial',period:ledger.period||null,updatedAt:store.updatedAt||null,source:'Ozon Seller API /v1/finance/accrual/by-day'});
  for(const row of ledger.daily||[]){if(row.date<from||row.date>to)continue;const cents=Number(row.values?.net);if(!Number.isSafeInteger(cents))continue;hasAny=true;records+=Number(row.values?.records)||0;totalCents+=cents;const item=byDate.get(row.date)||{date:row.date,positiveCents:0,negativeCents:0,netCents:0};item.netCents+=cents;if(cents>=0)item.positiveCents+=cents;else item.negativeCents+=cents;byDate.set(row.date,item)}
 }
 return {status:stores.length===0?'missing':complete?'complete':'partial',value:complete&&hasCoveredSource?totalCents/100:null,knownSubtotal:hasAny||hasCoveredSource?totalCents/100:null,records,series:[...byDate.values()].sort((a,b)=>a.date.localeCompare(b.date)).map(r=>({date:r.date,positive:r.positiveCents/100,negative:r.negativeCents/100,net:r.netCents/100})),sources};
}
function debtSummary(state,from,to){
 const active=state.loans.filter(x=>x.status==='active');const outstandingKnown=active.length>0&&active.every(x=>Number.isFinite(x.outstandingPrincipal));
 const inPeriod=state.payments.filter(p=>p.date>=from&&p.date<=to);const sum=k=>inPeriod.reduce((n,p)=>n+p[k],0);
 return {source:state.loans.length||state.payments.length?'Ручной реестр · подтверждение владельца':'Источник договоров и платежей не подключён',updatedAt:state.updatedAt,loans:state.loans,payments:state.payments,summary:{activeCount:active.length,outstandingPrincipal:outstandingKnown?active.reduce((n,x)=>n+x.outstandingPrincipal,0):null,principalPaid:sum('principal'),interestExpense:sum('interest'),feeExpense:sum('fee'),totalCashOut:inPeriod.reduce((n,p)=>n+p.principal+p.interest+p.fee,0)}};
}
function buildReport({stores,state,from,to}){
 from=date(from,'Начало периода');to=date(to,'Конец периода');if(from>to||Date.parse(to+'T00:00:00Z')-Date.parse(from+'T00:00:00Z')>366*86400000)throw Error('Проверьте период');
 const accruals=aggregate(stores,from,to),debt=debtSummary(state,from,to);
 return {period:{from,to},generatedAt:new Date().toISOString(),accruals,bankCash:{status:'missing',receipts:null,payments:null,net:null,source:'Банковская выписка не подключена'},operatingCashFlow:{status:'missing',value:null,reason:'Без банковской выписки нельзя подтвердить реальные поступления и выплаты'},profit:{status:'separate',value:null,reason:'Прибыль рассчитывается отдельно по начислениям и себестоимости; перечисления и займы в прибыль не входят',href:'/#economics'},debt};
}
function ruDate(value){const match=String(value||'').match(/\b(\d{1,2})[./-](\d{1,2})[./-](\d{4})\b/);if(!match)return null;const result=match[3]+'-'+match[2].padStart(2,'0')+'-'+match[1].padStart(2,'0');try{return date(result,'Дата')}catch{return null}}
function decimal(value){if(value===undefined||value===null||String(value).trim()==='')return null;const n=Number(String(value).replace(/\s/g,'').replace(',','.'));return Number.isFinite(n)&&n>=0&&Number.isSafeInteger(Math.round(n*100))?Math.round(n*100)/100:null}
function extractDraft(pages,name,hash,warnings=[]){
 const rows=[];for(const page of pages||[])for(const raw of String(page.text||'').split(/\r?\n/)){const line=raw.replace(/\s+/g,' ').trim();if(line)rows.push({page:page.page??null,line})}
 const find=(pattern,skip)=>{for(const row of rows){if(skip?.test(row.line))continue;const match=row.line.match(pattern);if(match)return {match,row}}return null},field=(value,found,confidence='exact')=>({value:value??null,confidence:value==null?'unknown':confidence,source:found?{page:found.row.page,excerpt:found.row.line.slice(0,280)}:null});
 const lender=find(/(?:кредитор|займодавец|наименование банка)\s*[:\-–]?\s*(.{3,160})$/iu),agreement=find(/(?:кредитн(?:ый|ого)\s+договор|договор(?:а)?\s+(?:займа|кредита)|договор)\s*(?:№|N(?:[oOОоQq0]|2)?)\s*([A-Za-zА-Яа-яЁё0-9./_-]{1,80})/iu),agreementDate=find(/(?:кредитн(?:ый|ого)\s+договор|договор(?:а)?\s+(?:займа|кредита)|договор).{0,120}от\s+(\d{1,2}[./-]\d{1,2}[./-]\d{4})/iu)||find(/от\s+(\d{1,2}[./-]\d{1,2}[./-]\d{4})/iu);
 const principal=find(/(?:сумма\s+(?:кредита|займа|договора)|размер\s+займа|предоставляет\s+(?:заем|займ|кредит))[^\d\n]{0,80}(\d[\d\s]*(?:[,.]\d{1,2})?)\s*(руб(?:лей|ля|ль|\.)?|RUB|₽|USD|EUR|доллар(?:ов|а)?|евро)(?:\s|$|[.,;])/iu),rate=find(/(?:процентная\s+ставка|ставка)[^\d%]{0,50}(\d+(?:[,.]\d+)?)\s*%\s*(годовых|в\s+месяц|ежемесячно|в\s+день|ежедневно)?/iu,/ПСК|полная\s+стоимость\s+кредита/iu),maturity=find(/(?:срок\s+возврата|дата\s+(?:погашения|возврата))[^\d]{0,50}(\d{1,2}[./-]\d{1,2}[./-]\d{4})/iu),frequency=find(/(ежемесячно|ежеквартально|еженедельно|ежегодно|аннуитетн(?:ый|ыми)|дифференцированн(?:ый|ыми))(?:\s|$|[.,;])/iu),plan=find(/(?:график\s+платежей|платежи\s+осуществляются)[^.!?]{0,220}/iu);
 const currency=principal?/^(?:USD|доллар)/iu.test(principal.match[2])?'USD':/^(?:EUR|евро)/iu.test(principal.match[2])?'EUR':'RUB':null,ratePeriod=rate?.match[2]?/год/iu.test(rate.match[2])?'annual':/месяц|ежемесяч/iu.test(rate.match[2])?'monthly':/день|ежеднев/iu.test(rate.match[2])?'daily':null:null;
 const annualRate=ratePeriod==='annual'?decimal(rate.match[1]):null;
 return {needsReview:true,fields:{lender:field(lender?.match[1]?.trim(),lender),agreementNumber:field(agreement?.match[1],agreement),signedDate:field(ruDate(agreementDate?.match[1]),agreementDate),originalPrincipal:field(decimal(principal?.match[1]),principal),currency:field(currency,principal),annualRatePercent:field(annualRate,rate,rate&&ratePeriod!=='annual'?'ambiguous':'exact'),rate:field(rate?decimal(rate.match[1]):null,rate,rate&&!ratePeriod?'ambiguous':'exact'),ratePeriod:field(ratePeriod,rate,rate&&!ratePeriod?'ambiguous':'exact'),maturityDate:field(ruDate(maturity?.match[1]),maturity),paymentFrequency:field(frequency?.match[1]?.toLocaleLowerCase('ru-RU'),frequency),paymentPlan:field(plan?.match[0],plan,'ambiguous')},suggestedSourceNote:'Файл '+name+' · проверено владельцем · '+hash.slice(0,12),warnings:[...warnings,...(!rows.length?['Текст не извлечён; заполните поля вручную или установите локальный OCR.']:[])]};
}
function create({privateDir,getStores,extractFile=null,now=()=>new Date().toISOString()}){
 const file=path.join(privateDir,'finance-register.json'),contractsDir=path.join(privateDir,'loan-contracts'),maxUpload=20*1024*1024,maxStorage=200*1024*1024;
 function read(){if(!fs.existsSync(file))return normalizeState(null);return normalizeState(JSON.parse(fs.readFileSync(file,'utf8')))}
 function write(state){state.updatedAt=new Date().toISOString();const tmp=file+'.tmp';fs.writeFileSync(tmp,JSON.stringify(state,null,2));fs.renameSync(tmp,file);return state}
 function saveLoan(input){const state=read(),id=clean(input.id||crypto.randomUUID(),'Идентификатор',80),lender=clean(input.lender,'Кредитор'),agreementNumber=clean(input.agreementNumber,'Номер договора'),signedDate=date(input.signedDate,'Дата договора');
  const duplicate=state.loans.find(x=>x.id!==id&&x.lender.toLocaleLowerCase('ru-RU')===lender.toLocaleLowerCase('ru-RU')&&x.agreementNumber.toLocaleLowerCase('ru-RU')===agreementNumber.toLocaleLowerCase('ru-RU'));if(duplicate)throw Error('Такой договор уже есть в реестре');
  const loan={id,lender,agreementNumber,signedDate,currency:'RUB',originalPrincipal:finiteMoney(input.originalPrincipal,'Сумма договора',{allowZero:false}),outstandingPrincipal:input.outstandingPrincipal===''||input.outstandingPrincipal==null?null:finiteMoney(input.outstandingPrincipal,'Остаток основного долга'),annualRatePercent:input.annualRatePercent===''||input.annualRatePercent==null?null:finiteMoney(input.annualRatePercent,'Процентная ставка'),nextPaymentDate:date(input.nextPaymentDate,'Следующий платёж',{required:false}),status:['active','closed'].includes(input.status)?input.status:'active',sourceNote:clean(input.sourceNote,'Источник подтверждения',300)};
  const index=state.loans.findIndex(x=>x.id===id);if(index>=0)state.loans[index]=loan;else state.loans.push(loan);write(state);return loan;
 }
 function savePayment(input){const state=read(),loanId=clean(input.loanId,'Договор',80);if(!state.loans.some(x=>x.id===loanId))throw Error('Договор не найден');const payment={id:clean(input.id||crypto.randomUUID(),'Идентификатор',80),loanId,date:date(input.date,'Дата платежа'),principal:finiteMoney(input.principal,'Погашение тела'),interest:finiteMoney(input.interest,'Проценты'),fee:finiteMoney(input.fee,'Комиссии'),sourceNote:clean(input.sourceNote,'Источник подтверждения',300)};
  if(payment.principal+payment.interest+payment.fee<=0)throw Error('Укажите хотя бы одну сумму платежа');const duplicate=state.payments.find(x=>x.id!==payment.id&&x.loanId===payment.loanId&&x.date===payment.date&&x.principal===payment.principal&&x.interest===payment.interest&&x.fee===payment.fee&&x.sourceNote.toLocaleLowerCase('ru-RU')===payment.sourceNote.toLocaleLowerCase('ru-RU'));if(duplicate)throw Error('Похожий платёж уже есть в реестре');const index=state.payments.findIndex(x=>x.id===payment.id);if(index>=0)state.payments[index]=payment;else state.payments.push(payment);write(state);return payment;
 }
 function report(query){const today=new Date().toISOString().slice(0,10),from=query.from||new Date(Date.parse(today+'T00:00:00Z')-29*86400000).toISOString().slice(0,10),to=query.to||today;return buildReport({stores:getStores(),state:read(),from,to})}
 function publicDraft(meta){return {id:meta.id,fileName:meta.fileName,format:meta.format,size:meta.size,createdAt:meta.createdAt,status:'draft',needsReview:true,fields:meta.fields,warnings:meta.warnings,suggestedSourceNote:meta.suggestedSourceNote}}
 function drafts(){if(!fs.existsSync(contractsDir))return [];return fs.readdirSync(contractsDir).filter(name=>/^[a-f0-9-]+\.json$/.test(name)).map(name=>{try{return publicDraft(JSON.parse(fs.readFileSync(path.join(contractsDir,name),'utf8')))}catch{return null}}).filter(Boolean).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
 function pythonPath(){const bundled=process.env.USERPROFILE&&path.join(process.env.USERPROFILE,'.cache','codex-runtimes','codex-primary-runtime','dependencies','python','python.exe');return process.env.PULT_PYTHON||(bundled&&fs.existsSync(bundled)?bundled:'python')}
 function runExtract(kind,target){return new Promise((resolve,reject)=>execFile(pythonPath(),[path.join(__dirname,'loan-contract-extract.py'),kind,target],{windowsHide:true,timeout:35000,maxBuffer:3*1024*1024},(error,stdout)=>{let value;try{value=JSON.parse(String(stdout).trim())}catch{}if(error||!value?.ok)return reject(Error(value?.error||(/timed out/i.test(error?.message||'')?'Превышено время безопасного разбора документа.':'Локальный обработчик документа недоступен.')));resolve(value)}))}
 extractFile ||= runExtract;
 async function upload(req,{fileName,contentType}){
  fileName=decodeURIComponent(String(fileName||''));const extension=path.extname(fileName).toLowerCase(),byExt={'.pdf':'pdf','.docx':'docx','.png':'png','.jpg':'jpg','.jpeg':'jpg'},kind=byExt[extension];if(!kind||path.basename(fileName)!==fileName||fileName.length>180)throw Error('Поддерживаются обычные PDF, DOCX, JPG и PNG');
  const declared=String(contentType||'').split(';')[0].toLowerCase(),allowed={pdf:['application/pdf'],docx:['application/vnd.openxmlformats-officedocument.wordprocessingml.document'],png:['image/png'],jpg:['image/jpeg']};if(!allowed[kind].includes(declared))throw Error('Тип файла не совпадает с расширением');
  const announced=Number(req.headers['content-length']);if(Number.isFinite(announced)&&announced>maxUpload)throw Error('Файл больше 20 МБ');let size=0,chunks=[];for await(const chunk of req){size+=chunk.length;if(size>maxUpload)throw Error('Файл больше 20 МБ');chunks.push(chunk)}if(!size)throw Error('Файл пуст');const buffer=Buffer.concat(chunks),magic=buffer.subarray(0,16),detected=magic.subarray(0,5).toString()==='%PDF-'?'pdf':magic.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))?'png':magic[0]===0xff&&magic[1]===0xd8&&magic[2]===0xff?'jpg':magic[0]===0x50&&magic[1]===0x4b?'docx':null;if(detected!==kind)throw Error('Содержимое файла не совпадает с расширением');
  fs.mkdirSync(contractsDir,{recursive:true,mode:0o700});const used=fs.readdirSync(contractsDir).reduce((sum,name)=>{try{return sum+fs.statSync(path.join(contractsDir,name)).size}catch{return sum}},0);if(used+size>maxStorage)throw Error('Хранилище договоров достигло лимита 200 МБ');const hash=crypto.createHash('sha256').update(buffer).digest('hex');for(const item of drafts()){const meta=JSON.parse(fs.readFileSync(path.join(contractsDir,item.id+'.json'),'utf8'));if(meta.hash===hash)return {...item,duplicate:true}}
  const id=crypto.randomUUID(),target=path.join(contractsDir,id+'.'+(kind==='jpg'?'jpg':kind)),temporary=target+'.tmp',metaTmp=path.join(contractsDir,id+'.json.tmp');fs.writeFileSync(temporary,buffer,{mode:0o600});try{const extracted=await extractFile(kind,temporary),draft=extractDraft(extracted.pages,fileName,hash,extracted.warnings),meta={id,fileName,format:kind,size,hash,createdAt:now(),...draft};fs.renameSync(temporary,target);fs.writeFileSync(metaTmp,JSON.stringify(meta,null,2),{mode:0o600});fs.renameSync(metaTmp,path.join(contractsDir,id+'.json'));return publicDraft(meta)}catch(error){if(fs.existsSync(temporary))fs.unlinkSync(temporary);if(fs.existsSync(metaTmp))fs.unlinkSync(metaTmp);if(fs.existsSync(target))fs.unlinkSync(target);throw error}
 }
 return {read,saveLoan,savePayment,report,drafts,upload};
}
module.exports={create,buildReport,aggregate,debtSummary,extractDraft};
