'use strict';
const {shift}=require('./insights-sync.cjs');
const fields=['realized','net','commission','logistics','ads','acquiring','storage','penalties','other','bonus','partners','reversal','unreconciled','unreconciledRecords','records'];
const inRange=(date,period)=>date>=period.from&&date<=period.to;
function covers(source,period){return !!source?.period&&source.period.from<=period.from&&source.period.to>=period.to}
function sumRows(rows,period){const totals=Object.fromEntries(fields.map(k=>[k,0]));for(const row of rows||[])if(inRange(row.date,period))for(const [key,value] of Object.entries(row.values))totals[key]=(totals[key]||0)+value;return totals}
function report(stores,{from,to,hideInactive=true},now=new Date()){
 if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||!Number.isFinite(Date.parse(from))||!Number.isFinite(Date.parse(to))||shift(from,0)!==from||shift(to,0)!==to||from>to)throw Error('Проверьте даты периода');
 const days=Math.round((Date.parse(to)-Date.parse(from))/86400000)+1;if(days>90)throw Error('Выберите не больше 90 дней');
 const current={from,to},previous={from:shift(from,-days),to:shift(from,-1)},financeComplete=p=>stores.length>0&&stores.every(s=>s.ledger?.complete&&covers(s.ledger,p)),ordersComplete=p=>stores.length>0&&stores.every(s=>s.extra?.orders&&covers(s.extra.orders,p));
 function aggregate(period){let totals=Object.fromEntries(fields.map(k=>[k,0]));let orderedRevenue=0,orderedUnits=0;for(const s of stores){const values=sumRows(s.ledger?.daily,period);for(const k of fields)totals[k]+=values[k]||0;for(const day of s.extra?.orders?.daily||[])if(inRange(day.date,period)){orderedRevenue+=Math.round(day.revenue*100);orderedUnits+=day.units}}
  return {totals,orderedRevenue,orderedUnits};}
 const c=aggregate(current),p=aggregate(previous),finance=financeComplete(current),previousFinance=financeComplete(previous),orders=ordersComplete(current),previousOrders=ordersComplete(previous),catalog=[];
 for(const store of stores)for(const product of store.products||[])if(!hideInactive||!require('./dist/dashboard-model.js').isInactive(product))catalog.push(product);
 const known=catalog.filter(p=>p.quantity!==null),costed=known.filter(p=>p.cost?.status==='filled'&&p.cost.currency==='RUB'),stockValue=costed.reduce((s,p)=>s+Math.round(p.cost.unitCost*100)*p.quantity,0),stocks=known.reduce((s,p)=>s+p.quantity,0);
 const metrics={};for(const key of fields){if(key==='records'||key==='unreconciledRecords')continue;const sign=['commission','logistics','ads','acquiring','storage','penalties','other'].includes(key)?-1:1;metrics[key]={current:finance?c.totals[key]*sign/100:null,previous:previousFinance?p.totals[key]*sign/100:null,kind:'money',source:'finance'};}
 metrics.orderedRevenue={current:orders?c.orderedRevenue/100:null,previous:previousOrders?p.orderedRevenue/100:null,kind:'money',source:'orders'};metrics.orderedUnits={current:orders?c.orderedUnits:null,previous:previousOrders?p.orderedUnits:null,kind:'units',source:'orders'};
 metrics.adShare={current:finance&&c.totals.realized>0?-c.totals.ads/c.totals.realized*100:null,previous:previousFinance&&p.totals.realized>0?-p.totals.ads/p.totals.realized*100:null,kind:'percent',source:'finance'};
 metrics.stocks={current:known.length?stocks:null,previous:null,kind:'units',source:'inventory'};metrics.stockValue={current:costed.length?stockValue/100:null,previous:null,kind:'money',source:'inventory'};metrics.zeroStock={current:known.filter(p=>p.quantity===0).length,previous:null,kind:'units',source:'inventory'};metrics.costCoverage={current:catalog.length?catalog.filter(p=>p.cost?.status==='filled').length/catalog.length*100:null,previous:null,kind:'percent',source:'inventory'};
 const daily=[];for(let date=from;date<=to;date=shift(date,1)){const a=aggregate({from:date,to:date});daily.push({date,realized:finance?a.totals.realized/100:null,net:finance?a.totals.net/100:null,ads:finance?-a.totals.ads/100:null,orderedRevenue:orders?a.orderedRevenue/100:null,orderedUnits:orders?a.orderedUnits:null})}
 const feeMap=new Map(),products=[],storeRows=[];
 for(const store of stores){
  const values=sumRows(store.ledger?.daily,current);storeRows.push({id:store.id,name:store.name,complete:!!store.ledger?.complete&&covers(store.ledger,current),realized:values.realized/100,net:values.net/100,ads:-values.ads/100,logistics:-values.logistics/100,commission:-values.commission/100,records:values.records});
  for(const f of store.ledger?.fees||[])if(inRange(f.date,current)){const key=f.typeId+':'+f.group;const v=feeMap.get(key)||{name:f.name,group:f.group,typeId:f.typeId,amount:0,count:0};v.amount+=f.values.amount;v.count+=f.count;feeMap.set(key,v)}
  const bySku=new Map();for(const day of store.ledger?.skuDaily||[])if(inRange(day.date,current)){const v=bySku.get(day.sku)||{};for(const[k,n]of Object.entries(day.values))v[k]=(v[k]||0)+n;bySku.set(day.sku,v)}
  const productMap=new Map();for(const product of store.products||[])for(const sku of product.skus||[product.sku])if(sku)productMap.set(String(sku),product);
  for(const [sku,values]of bySku){const product=productMap.get(sku);products.push({sku,key:product?.key||null,name:product?.name||'SKU '+sku,offer_id:product?.offer_id||'Нет карточки в текущем каталоге',storeId:store.id,storeName:store.name,archived:product?require('./dist/dashboard-model.js').isInactive(product):false,realized:(values.realized||0)/100,net:(values.net||0)/100,commission:-(values.commission||0)/100,logistics:-(values.logistics||0)/100,fees:-(values.acquiring||0)/100,quantity:product?.quantity??null,cost:product?.cost?.status==='filled'?product.cost.unitCost:null,costCurrency:product?.cost?.currency||null});}
 }
 return {declines:require('./sales-decline.cjs').analyze(stores,current,previous,{now,hideInactive}),economics:require('./economics.cjs').economics(stores,current),current,previous,days,metrics,daily,fees:[...feeMap.values()].map(f=>({...f,amount:f.amount/100})).sort((a,b)=>a.amount-b.amount),products:products.sort((a,b)=>b.realized-a.realized),stores:storeRows,coverage:{finance,previousFinance,orders,previousOrders,financeFrom:stores.length?stores.map(s=>s.ledger?.period?.from||'').sort().at(-1):null,financeTo:stores.length?stores.map(s=>s.ledger?.period?.to||'').sort()[0]:null,unknownStocks:catalog.length-known.length,valuedStockProducts:costed.length,knownStockProducts:known.length,unreconciled:finance?c.totals.unreconciled/100:null,unreconciledRecords:finance?c.totals.unreconciledRecords:null,records:finance?c.totals.records:null,foreignRecords:stores.reduce((v,s)=>v+(s.ledger?.foreignRecords||0),0)},sources:stores.map(s=>({id:s.id,name:s.name,financeAt:s.ledger?.completedAt,ordersAt:s.extra?.orders?.updatedAt,errors:s.extra?.errors||[]})),generatedAt:now.toISOString()};
}
module.exports={report,covers,sumRows};
