'use strict';
const path=require('node:path');
const {DatabaseSync}=require('node:sqlite');
const DAY=/^\d{4}-\d{2}-\d{2}$/,MAX_REPORT_DAYS=3660;
const METRICS={units:{column:'units',sources:['ozon-orders','wb-orders']},revenue:{column:'revenue',sources:['ozon-orders','wb-orders']},soldUnits:{column:'sold_units',sources:['ozon-finance']},returnedUnits:{column:'returned_units',sources:['ozon-finance']},realized:{column:'realized',sources:['ozon-finance']},ads:{column:'ads',sources:['ozon-finance']}};
const mskDay=value=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
function validDay(value){if(!DAY.test(value||''))return false;const parsed=new Date(value+'T00:00:00Z');return Number.isFinite(+parsed)&&parsed.toISOString().slice(0,10)===value}
function days(from,to){if(!validDay(from)||!validDay(to)||from>to)throw Error('Некорректный календарный период');const out=[];for(let at=Date.parse(from+'T00:00:00Z'),end=Date.parse(to+'T00:00:00Z');at<=end;at+=86400000)out.push(new Date(at).toISOString().slice(0,10));return out}
function number(value,label,{integer=false,min}={}){if(value===null||value===undefined||value===''||!Number.isFinite(value)||integer&&!Number.isSafeInteger(value)||min!==undefined&&value<min)throw Error('Некорректное значение '+label);if(!Number.isSafeInteger(Math.round(value*100)))throw Error('Слишком большое значение '+label);return value}
function optionalUnits(value,label){return value===undefined?0:number(value,label,{integer:true,min:0})}
function optionalCents(value,label){return value===undefined?0:number(value,label,{integer:true})/100}
function requiredTime(value,label){const parsed=Date.parse(value);if(!Number.isFinite(parsed))throw Error('Некорректное время '+label);return new Date(parsed).toISOString()}
function storeFrom(file,prefix,pattern='\\d+'){const name=path.basename(String(file||'')),match=name.match(new RegExp('^'+prefix+'-('+pattern+')\\.json$'));if(!match)throw Error('Неподдерживаемое имя файла источника');return match[1]}
function create({dbFile,now=Date.now}){
 if(!dbFile)throw Error('Не указан файл базы истории');const db=new DatabaseSync(dbFile);db.exec(`PRAGMA journal_mode=WAL;PRAGMA synchronous=FULL;PRAGMA busy_timeout=5000;PRAGMA foreign_keys=ON;
 CREATE TABLE IF NOT EXISTS ingestions(id INTEGER PRIMARY KEY,source_file TEXT NOT NULL,content_hash TEXT NOT NULL,captured_at TEXT NOT NULL,source_kind TEXT NOT NULL,UNIQUE(source_file,content_hash));
 CREATE TABLE IF NOT EXISTS snapshots(id INTEGER PRIMARY KEY,ingestion_id INTEGER NOT NULL REFERENCES ingestions(id),source_kind TEXT NOT NULL,market TEXT NOT NULL,store_id TEXT NOT NULL,day TEXT NOT NULL,source_actual_at TEXT NOT NULL,closed_confirmed INTEGER NOT NULL,partial_reason TEXT,UNIQUE(ingestion_id,source_kind,store_id,day));
 CREATE TABLE IF NOT EXISTS facts(id INTEGER PRIMARY KEY,snapshot_id INTEGER NOT NULL REFERENCES snapshots(id),product_id TEXT NOT NULL,observed_at TEXT,units REAL,revenue REAL,sold_units REAL,returned_units REAL,realized REAL,ads REAL,unknown_unit_rows INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS order_events(id INTEGER PRIMARY KEY,snapshot_id INTEGER NOT NULL REFERENCES snapshots(id),product_id TEXT NOT NULL,occurred_at TEXT NOT NULL,amount REAL);
 CREATE TABLE IF NOT EXISTS product_names(market TEXT NOT NULL,store_id TEXT NOT NULL,product_id TEXT NOT NULL,name TEXT NOT NULL,source_actual_at TEXT NOT NULL,PRIMARY KEY(market,store_id,product_id));
 CREATE TABLE IF NOT EXISTS product_aliases(market TEXT NOT NULL,store_id TEXT NOT NULL,alias TEXT NOT NULL,product_id TEXT NOT NULL,source_actual_at TEXT NOT NULL,PRIMARY KEY(market,store_id,alias));
 CREATE INDEX IF NOT EXISTS snapshots_store_day ON snapshots(market,store_id,day,source_kind,closed_confirmed,source_actual_at DESC);CREATE INDEX IF NOT EXISTS facts_product_day ON facts(product_id,snapshot_id);CREATE INDEX IF NOT EXISTS events_product_time ON order_events(product_id,occurred_at);`);
 const insertIngestion=db.prepare('INSERT INTO ingestions(source_file,content_hash,captured_at,source_kind) VALUES(?,?,?,?)'),findIngestion=db.prepare('SELECT id FROM ingestions WHERE source_file=? AND content_hash=?'),insertSnapshot=db.prepare('INSERT INTO snapshots(ingestion_id,source_kind,market,store_id,day,source_actual_at,closed_confirmed,partial_reason) VALUES(?,?,?,?,?,?,?,?)'),insertFact=db.prepare('INSERT INTO facts(snapshot_id,product_id,observed_at,units,revenue,sold_units,returned_units,realized,ads,unknown_unit_rows) VALUES(?,?,?,?,?,?,?,?,?,?)'),insertEvent=db.prepare('INSERT INTO order_events(snapshot_id,product_id,occurred_at,amount) VALUES(?,?,?,?)');
 function addSnapshot(ingestionId,{sourceKind,market,storeId,day,actual,closed,reason,rows=[]}){const info=insertSnapshot.run(ingestionId,sourceKind,market,String(storeId),day,actual,closed?1:0,reason||null),id=Number(info.lastInsertRowid);for(const row of rows)insertFact.run(id,String(row.productId),row.observedAt||null,row.units??null,row.revenue??null,row.soldUnits??null,row.returnedUnits??null,row.realized??null,row.ads??null,row.unknownUnitRows||0);return id}
 function catalog(ingestionId,storeId,data,capturedAt){const products=data?.products||data?.data?.products;if(!Array.isArray(products))throw Error('Некорректный каталог товаров');const upName=db.prepare(`INSERT INTO product_names VALUES(?,?,?,?,?) ON CONFLICT(market,store_id,product_id) DO UPDATE SET name=excluded.name,source_actual_at=excluded.source_actual_at WHERE excluded.source_actual_at>=product_names.source_actual_at`),upAlias=db.prepare(`INSERT INTO product_aliases VALUES(?,?,?,?,?) ON CONFLICT(market,store_id,alias) DO UPDATE SET product_id=excluded.product_id,source_actual_at=excluded.source_actual_at WHERE excluded.source_actual_at>=product_aliases.source_actual_at`);for(const item of products){const id=item.sku??item.product_id??item.nmID;if(id===undefined||id===null||String(id)==='')continue;const market=String(item.market||data.market||(String(storeId).startsWith('wb-')?'WB':'Ozon')),name=String(item.name??item.title??item.offer_id??item.vendorCode??id);if(!['Ozon','WB'].includes(market))throw Error('Некорректная площадка каталога');upName.run(market,String(storeId),String(id),name,capturedAt);for(const alias of [item.sku,item.product_id,item.nmID,item.offer_id,item.vendorCode])if(alias!==undefined&&alias!==null&&String(alias)!==String(id))upAlias.run(market,String(storeId),String(alias),String(id),capturedAt)}return products.length}
 function ingest({sourceFile,contentHash,data,capturedAt}){
  if(!sourceFile||!contentHash||!data||typeof data!=='object')throw Error('Не указаны sourceFile, contentHash или data');capturedAt=requiredTime(capturedAt||new Date(now()).toISOString(),'capturedAt');const base=path.basename(String(sourceFile));let kind,storeId;if(/^insights-\d+\.json$/.test(base)){kind='ozon-orders';storeId=storeFrom(base,'insights')}else if(/^ledger-\d+\.json$/.test(base)){kind='ozon-finance';storeId=storeFrom(base,'ledger')}else if(/^wb-orders-wb-\d+\.json$/.test(base)){kind='wb-orders';storeId=storeFrom(base,'wb-orders','wb-\\d+')}else if(/^order-category-catalog-(?:wb-)?\d+\.json$/.test(base)){kind='catalog';storeId=storeFrom(base,'order-category-catalog','(?:wb-)?\\d+')}else throw Error('Неподдерживаемое имя файла источника');if(findIngestion.get(base,String(contentHash)))return{duplicate:true};
  db.exec('BEGIN IMMEDIATE');try{const ingestionId=Number(insertIngestion.run(base,String(contentHash),capturedAt,kind).lastInsertRowid);let snapshotCount=0,factCount=0;
   if(kind==='catalog'){factCount=catalog(ingestionId,storeId,data,capturedAt)}
   else if(kind==='ozon-orders'){const orders=data.orders;if(!orders||!orders.period)throw Error('Некорректный снимок заказов Ozon');const periodDays=days(orders.period.from,orders.period.to),periodSet=new Set(periodDays),actual=requiredTime(orders.skuUpdatedAt||orders.updatedAt,'заказов Ozon'),byDay=new Map();if(!Array.isArray(orders.skuDaily))throw Error('Некорректный skuDaily');for(const row of orders.skuDaily){if(!validDay(row.date)||!periodSet.has(row.date)||row.sku===undefined||row.sku===null||String(row.sku)==='')throw Error('Некорректная строка заказов Ozon');const list=byDay.get(row.date)||[];list.push({productId:row.sku,observedAt:actual,units:number(row.units,'units',{integer:true,min:0}),revenue:number(row.revenue,'revenue')});byDay.set(row.date,list)}let covered;if(Array.isArray(orders.skuCoverage))covered=new Set(orders.skuCoverage);else if(orders.skuPeriod)covered=new Set(days(orders.skuPeriod.from,orders.skuPeriod.to));else covered=new Set([orders.todayDate||mskDay(actual)]);for(const day of covered)if(!validDay(day)||!periodSet.has(day))throw Error('Некорректное покрытие SKU');const snapshotDays=new Set([...byDay.keys(),...covered]);for(const day of snapshotDays){const rows=byDay.get(day)||[],closed=orders.skuDailyCoverage===true&&covered.has(day)&&mskDay(actual)>day;factCount+=rows.length;addSnapshot(ingestionId,{sourceKind:kind,market:'Ozon',storeId,day,actual,closed,reason:closed?null:'Покрытие SKU или закрытие дня не подтверждено',rows});snapshotCount++}}
   else if(kind==='ozon-finance'){const ledger=data.data||data,period=ledger.period,actual=requiredTime(ledger.completedAt||data.stamp,'финансов Ozon');if(!period||!Array.isArray(ledger.skuDaily))throw Error('Некорректный ledger');const periodDays=days(period.from,period.to),periodSet=new Set(periodDays),byDay=new Map();for(const row of ledger.skuDaily){if(!validDay(row.date)||!periodSet.has(row.date)||row.sku===undefined||row.sku===null||String(row.sku)===''||!row.values)throw Error('Некорректная финансовая строка');const values=row.values,list=byDay.get(row.date)||[],unknown=values.unknownUnitRows===undefined?0:number(values.unknownUnitRows,'unknownUnitRows',{integer:true,min:0});list.push({productId:row.sku,observedAt:actual,soldUnits:optionalUnits(values.soldUnits,'soldUnits'),returnedUnits:optionalUnits(values.returnedUnits,'returnedUnits'),realized:optionalCents(values.realized,'realized'),ads:optionalCents(values.ads,'ads'),unknownUnitRows:unknown});byDay.set(row.date,list)}for(const day of periodDays){const rows=byDay.get(day)||[],closed=ledger.complete===true&&mskDay(actual)>day;factCount+=rows.length;addSnapshot(ingestionId,{sourceKind:kind,market:'Ozon',storeId,day,actual,closed,reason:closed?null:'Финансы неполны или день ещё открыт',rows});snapshotCount++}}
   else{const day=data.day,actual=requiredTime(data.fetchedAt,'WB');if(!validDay(day)||!Array.isArray(data.orders))throw Error('Некорректный снимок заказов WB');const grouped=new Map();for(const order of data.orders){if(order.nmId===undefined||order.nmId===null||String(order.nmId)===''||!order.at)throw Error('Некорректная строка заказа WB');const occurredAt=requiredTime(order.at,'заказа WB');if(mskDay(occurredAt)!==day)throw Error('Дата заказа WB не совпадает с днём снимка');const amount=number(order.amount,'amount WB'),id=String(order.nmId),row=grouped.get(id)||{productId:id,units:0,revenue:0,events:[]};row.units++;row.revenue+=amount;if(!Number.isSafeInteger(Math.round(row.revenue*100)))throw Error('Слишком большая сумма WB');row.events.push({occurredAt,amount});grouped.set(id,row)}const rows=[...grouped.values()],closed=data.complete===true&&mskDay(actual)>day,id=addSnapshot(ingestionId,{sourceKind:kind,market:'WB',storeId,day,actual,closed,reason:closed?null:'Снимок WB неполон или день ещё открыт',rows});for(const row of rows)for(const event of row.events)insertEvent.run(id,row.productId,event.occurredAt,event.amount);snapshotCount=1;factCount=rows.length}
   db.exec('COMMIT');return{duplicate:false,ingestionId,snapshotCount,factCount}
  }catch(error){db.exec('ROLLBACK');throw error}
 }
 function status(){const counts=db.prepare('SELECT (SELECT count(*) FROM ingestions) ingestions,(SELECT count(*) FROM snapshots) snapshots,(SELECT count(*) FROM facts) facts,(SELECT count(*) FROM order_events) events').get(),last=db.prepare('SELECT captured_at,source_kind FROM ingestions ORDER BY id DESC LIMIT 1').get();return{...counts,lastImport:last||null,retention:'unbounded'}}
 function report({from,to,market,storeId,productId,metric='revenue'}={}){const range=days(from,to);if(range.length>MAX_REPORT_DAYS)throw Error('Период отчёта превышает 3660 дней; хранение базы при этом бессрочное');if(market===undefined||market===null||market===''||String(market).toLowerCase()==='all')market=null;else if(!['Ozon','WB'].includes(String(market)))throw Error('Неизвестная площадка');const spec=METRICS[metric];if(!spec)throw Error('Неизвестная метрика');
  const selected=`WITH ranked AS (SELECT s.*,row_number() OVER(PARTITION BY source_kind,market,store_id,day ORDER BY source_actual_at DESC,id DESC) rn FROM snapshots s WHERE closed_confirmed=1 AND day BETWEEN ? AND ? AND source_kind IN (${spec.sources.map(()=>'?').join(',')}))`;
  const selectedParams=[from,to,...spec.sources],extra=[];if(market){extra.push('market=?');selectedParams.push(String(market))}if(storeId){extra.push('store_id=?');selectedParams.push(String(storeId))}const coverageRows=db.prepare(`${selected} SELECT market,store_id,day FROM ranked WHERE rn=1${extra.length?' AND '+extra.join(' AND '):''}`).all(...selectedParams),coverageMap=new Map();for(const row of coverageRows){const key=row.market+'\0'+row.store_id,list=coverageMap.get(key)||[];list.push(row.day);coverageMap.set(key,list)}
  const factSql=`${selected} SELECT r.market,r.store_id,r.day,f.product_id,f.${spec.column} value,f.unknown_unit_rows,p.name FROM ranked r JOIN facts f ON f.snapshot_id=r.id LEFT JOIN product_aliases a ON a.market=r.market AND a.store_id=r.store_id AND a.alias=f.product_id LEFT JOIN product_names p ON p.market=r.market AND p.store_id=r.store_id AND p.product_id=coalesce(a.product_id,f.product_id) WHERE r.rn=1${market?' AND r.market=?':''}${storeId?' AND r.store_id=?':''}${productId?' AND f.product_id=?':''}`;const factParams=[from,to,...spec.sources];if(market)factParams.push(String(market));if(storeId)factParams.push(String(storeId));if(productId)factParams.push(String(productId));const grouped=new Map();for(const row of db.prepare(factSql).all(...factParams)){const key=[row.market,row.store_id,row.product_id].join('\0'),item=grouped.get(key)||{market:row.market,storeId:row.store_id,productId:row.product_id,name:row.name||null,values:new Map(),unknownUnitRows:0};item.values.set(row.day,(item.values.get(row.day)||0)+(row.value??0));item.unknownUnitRows+=row.unknown_unit_rows||0;grouped.set(key,item)}
  const isWeekend=day=>[0,6].includes(new Date(day+'T12:00:00Z').getUTCDay()),rows=[];for(const item of grouped.values()){const covered=coverageMap.get(item.market+'\0'+item.storeId)||[],parts={weekday:{days:0,value:0},weekend:{days:0,value:0}};for(const day of covered){const part=isWeekend(day)?parts.weekend:parts.weekday;part.days++;part.value+=item.values.get(day)||0}for(const part of Object.values(parts))part.averagePerDay=part.days?part.value/part.days:null;const value=parts.weekday.value+parts.weekend.value;rows.push({market:item.market,storeId:item.storeId,productId:item.productId,name:item.name,totals:{value,[metric]:value,unknownUnitRows:item.unknownUnitRows,unitsComplete:item.unknownUnitRows===0},weekday:parts.weekday,weekend:parts.weekend})}rows.sort((a,b)=>b.totals.value-a.totals.value||a.storeId.localeCompare(b.storeId)||a.productId.localeCompare(b.productId));const confirmedDays=new Set(coverageRows.map(row=>row.market+'\0'+row.store_id+'\0'+row.day));return{period:{from,to,timeZone:'Europe/Moscow'},metric,rows,coverage:{requestedDays:range.length,confirmedStoreDays:confirmedDays.size,excludedPartialOrOpen:true},limitations:['Сравнение будней и выходных использует только подтверждённые полные дни; текущие и частичные снимки исключены.','Пустой подтверждённый день входит в знаменатель как ноль.','unknownUnitRows больше нуля означает, что количество является нижней границей, а не полным подтверждённым итогом.','Время Ozon SKU — время наблюдения, а не час заказа; реальные часы доступны только для WB.']}}
 return{ingest,status,report,close(){db.close()}};
}
module.exports={create,MAX_REPORT_DAYS};
