const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),{spawn}=require('child_process');
const root=path.join(__dirname,'dist'),privateDir=path.join(__dirname,'.private');fs.mkdirSync(privateDir,{recursive:true});const dbFile=path.join(privateDir,'stores.json');const allowedNames=['SK','Современная канцелярия','СтальКрепеж','Строительный континент'];let stores=fs.existsSync(dbFile)?JSON.parse(fs.readFileSync(dbFile,'utf8')):{};const jobs=new Map(),sessions=new Set();const port=Number(process.env.PORT||4317),origin='http://127.0.0.1:'+port;
function save(){fs.writeFileSync(dbFile+'.tmp',JSON.stringify(stores,null,2));fs.renameSync(dbFile+'.tmp',dbFile)}
function protect(value,decrypt=false){return new Promise((resolve,reject)=>{const script=decrypt?`Add-Type -AssemblyName System.Security; $v=[Console]::In.ReadToEnd(); $b=[Convert]::FromBase64String($v); $o=[Security.Cryptography.ProtectedData]::Unprotect($b,$null,[Security.Cryptography.DataProtectionScope]::CurrentUser); [Console]::Out.Write([Text.Encoding]::UTF8.GetString($o))`:`Add-Type -AssemblyName System.Security; $v=[Console]::In.ReadToEnd(); $b=[Text.Encoding]::UTF8.GetBytes($v); $o=[Security.Cryptography.ProtectedData]::Protect($b,$null,[Security.Cryptography.DataProtectionScope]::CurrentUser); [Console]::Out.Write([Convert]::ToBase64String($o))`;const p=spawn('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,stdio:['pipe','pipe','pipe']});let out='';p.stdout.on('data',b=>out+=b);p.stderr.on('data',()=>{});p.on('error',()=>reject(Error('Хранилище Windows недоступно')));p.on('close',n=>n?reject(Error('Не удалось обработать защищённый ключ')):resolve(out));p.stdin.end(value)})}
async function api(store,key,endpoint,payload){for(let attempt=0;attempt<3;attempt++){let response;try{response=await fetch('https://api-seller.ozon.ru'+endpoint,{method:'POST',headers:{'Content-Type':'application/json','Client-Id':store.clientId,'Api-Key':key},body:JSON.stringify(payload),signal:AbortSignal.timeout(45000)})}catch{throw Error('Нет ответа Ozon. Повторите обновление позже.')};if(response.status===429||response.status>=500){if(attempt<2){await new Promise(r=>setTimeout(r,2000*(attempt+1)));continue}}if(!response.ok)throw Error('Ozon '+response.status+' · '+endpoint+(response.status===403?' · Недостаточно прав':response.status===401?' · Проверьте ключ':''));return response.json()}throw Error('Ozon временно недоступен')}
function snapshot(id){const file=path.join(privateDir,'data-'+id+'.json');return fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):null}
const summaryCache=new Map();
function publicSnapshot(id){const file=path.join(privateDir,'data-'+id+'.json');if(!fs.existsSync(file))return null;const costFile=path.join(privateDir,'costs-'+id+'.json'),priceFile=path.join(privateDir,'prices-'+id+'.json');const stamp=fs.statSync(file).mtimeMs+':'+(fs.existsSync(costFile)?fs.statSync(costFile).mtimeMs:0)+':'+(fs.existsSync(priceFile)?fs.statSync(priceFile).mtimeMs:0);if(summaryCache.get(id)?.stamp===stamp)return summaryCache.get(id).data;const costs=fs.existsSync(costFile)?JSON.parse(fs.readFileSync(costFile,'utf8')):null;const data=require('./summary.cjs').summarize(snapshot(id),costs,fs.existsSync(priceFile)?JSON.parse(fs.readFileSync(priceFile,'utf8')):null);summaryCache.set(id,{stamp,data});return data}
function publicStores(){return Object.entries(stores).map(([id,s])=>({id,name:s.name,clientId:s.clientId,connectedAt:s.connectedAt,job:jobs.get(id)||null,updatedAt:s.updatedAt||null,revision:(s.updatedAt||'')+':'+(fs.existsSync(path.join(privateDir,'costs-'+id+'.json'))?fs.statSync(path.join(privateDir,'costs-'+id+'.json')).mtimeMs:0)+':'+(fs.existsSync(path.join(privateDir,'prices-'+id+'.json'))?fs.statSync(path.join(privateDir,'prices-'+id+'.json')).mtimeMs:0)}))}
const wbConnector=require('./wb.cjs')({stores,jobs,protect,save,privateDir});
const pricing=require('./pricing.cjs')({stores,protect,api,privateDir,jobs});
const insightsSync=require('./insights-sync.cjs')({stores,protect,api,privateDir});
const trueStats=require('./truestats.cjs').create({privateDir,protect});
const wbEconomics=require('./wb-economics.cjs').create({stores,privateDir,trueStats});
const refreshPolicy=require('./refresh-policy.cjs'),{day:moscowDay}=require('./intraday.cjs');
function refreshState(id){return {job:jobs.get(id),attemptAt:stores[id].syncAttemptAt,snapshotAt:stores[id].updatedAt}}
function ensureFreshOzon(){for(const [id,s] of Object.entries(stores))if(refreshPolicy.due(refreshState(id)))void sync(id)}
const ledgerFor=require('./ledger.cjs').cache({privateDir,readTypes:insightsSync.read});
const intraday=require('./intraday.cjs').create({privateDir});let historyError=null;
function captureLatest(){historyError=null;for(const [id,s] of Object.entries(stores))if(s.market!=='WB')try{intraday.capture(id,{orders:insightsSync.read(id)?.orders,ledger:ledgerFor(id),products:require('./dist/dashboard-model.js').rowsFor([{id,...s}],new Map([[id,publicSnapshot(id)]]))})}catch{historyError='Не удалось сохранить часть точек графика. Проверьте доступность диска.'}}
let trueStatsAttemptAt=0,trueStatsAttemptDay='';
function ensureTrueStats(){
 const today=moscowDay(new Date()),now=Date.now();
 if(!trueStats.status().connected||(trueStatsAttemptDay===today&&now-trueStatsAttemptAt<30*60*1000))return;
 trueStatsAttemptAt=now;trueStatsAttemptDay=today;
 if(Object.values(stores).some(s=>s.market==='WB'))void wbEconomics.read({from:today,to:today}).catch(()=>{});
 void trueStats.compare({period:{from:today,to:today},stores:Object.entries(stores).filter(([,s])=>s.market!=='WB').map(([id,s])=>({id,name:s.name}))});
}
function backgroundRefresh(){captureLatest();insightsSync.ensure();ensureFreshOzon();ensureTrueStats()}
const management=require('./management.cjs')({file:path.join(privateDir,'management.json'),catalog:()=>require('./dist/dashboard-model.js').rowsFor(publicStores(),new Map(Object.keys(stores).map(id=>[id,publicSnapshot(id)])))});
async function sync(id){if(stores[id]?.market==='WB')return wbConnector.sync(id);if(jobs.get(id)?.status==='running')return;const s=stores[id];const job={status:'running',stage:'Товары',count:0,errors:[],startedAt:new Date().toISOString()};jobs.set(id,job);s.syncAttemptAt=job.startedAt;save();const today=moscowDay(new Date());const data={store:s.name,clientId:s.clientId,startedAt:job.startedAt,products:[],stocks:[],operations:[],sections:{},period:{from:require('./insights-sync.cjs').shift(today,-29),to:today}};let key;try{key=await protect(s.key,true);try{const costs=await require('./costs.cjs')(s,key,api);const cf=path.join(privateDir,'costs-'+id+'.json');fs.writeFileSync(cf+'.tmp',JSON.stringify(costs));fs.renameSync(cf+'.tmp',cf)}catch(e){job.errors.push('Себестоимость: '+e.message)}try{let last='',seen=new Set();for(let page=0;page<500;page++){const r=await api(s,key,'/v3/product/list',{filter:{visibility:'ALL'},last_id:last,limit:1000});const v=r.result||r;if(!Array.isArray(v.items))throw Error('Неожиданный формат списка товаров');data.products.push(...v.items);job.count=data.products.length;if(!v.items.length||data.products.length>=v.total||!v.last_id)break;if(seen.has(v.last_id))throw Error('Ozon повторил страницу товаров');seen.add(v.last_id);last=v.last_id;await new Promise(r=>setTimeout(r,1100))}const ids=data.products.map(p=>String(p.product_id));for(let i=0;i<ids.length;i+=100){const r=await api(s,key,'/v3/product/info/list',{product_id:ids.slice(i,i+100)});if(!Array.isArray(r.items))throw Error('Неожиданный формат карточек товаров');const byId=new Map(r.items.map(p=>[String(p.id),p]));data.products=data.products.map(p=>byId.has(String(p.product_id))?{...p,...byId.get(String(p.product_id))}:p);await new Promise(r=>setTimeout(r,1100))}data.sections.products={ok:true,count:data.products.length}}catch(e){data.sections.products={ok:false,error:e.message};job.errors.push(e.message)}
job.stage='Остатки';try{let cursor='',seen=new Set();for(let page=0;page<500;page++){const r=await api(s,key,'/v4/product/info/stocks',{filter:{visibility:'ALL'},cursor,limit:1000});const v=r.result||r;if(!Array.isArray(v.items))throw Error('Неожиданный формат остатков');data.stocks.push(...v.items);if(!v.items.length||!v.cursor)break;if(seen.has(v.cursor))throw Error('Ozon повторил страницу остатков');seen.add(v.cursor);cursor=v.cursor;await new Promise(r=>setTimeout(r,1100))}data.sections.stocks={ok:true,count:data.stocks.length}}catch(e){data.sections.stocks={ok:false,error:e.message};job.errors.push(e.message)}
job.stage='Финансовые начисления за 30 дней';try{const end=Date.parse(data.period.to+'T00:00:00.000Z');for(let day=Date.parse(data.period.from+'T00:00:00.000Z');day<=end;day+=86400000){const date=new Date(day).toISOString().slice(0,10);let last='',seen=new Set();for(let page=0;page<1000;page++){const v=await api(s,key,'/v1/finance/accrual/by-day',{date,last_id:last});if(!Array.isArray(v.accruals))throw Error('Неожиданный формат начислений');data.operations.push(...v.accruals.map(a=>({...a,operation_id:a.accrual_id,amount:Number(a.total_amount?.amount||0),operation_type:a.accrued_category,operation_type_name:a.accrued_category})));job.count=data.operations.length;job.stage='Начисления · '+date;if(!v.accruals.length||!v.last_id)break;if(seen.has(v.last_id)||page===999)throw Error('Не удалось получить все страницы начислений');seen.add(v.last_id);last=v.last_id;await new Promise(r=>setTimeout(r,1100))}await new Promise(r=>setTimeout(r,1100))}data.sections.finance={ok:true,count:data.operations.length,source:'/v1/finance/accrual/by-day'}}catch(e){data.sections.finance={ok:false,error:e.message};job.errors.push(e.message)}

data.completedAt=new Date().toISOString();const file=path.join(privateDir,'data-'+id+'.json');fs.writeFileSync(file+'.tmp',JSON.stringify(data));fs.renameSync(file+'.tmp',file);s.updatedAt=data.completedAt;save();job.status=job.errors.length?'partial':'done';job.stage=job.errors.length?'Часть разделов требует проверки':'Готово';}catch(e){job.status='error';job.stage=e.message}finally{key=null;job.finishedAt=new Date().toISOString()}}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.svg':'image/svg+xml'};function json(res,status,obj){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(obj))}
http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');if(req.headers.host!=='127.0.0.1:'+port){res.writeHead(403).end();return}const u=new URL(req.url,origin);const token=(req.headers.cookie||'').match(/(?:^|; )pult_session=([a-f0-9]+)/)?.[1];if(u.pathname.startsWith('/api/')){if(!sessions.has(token)){json(res,403,{error:'Откройте страницу подключения'});return}if(req.method==='POST'&&(req.headers.origin!==origin||!req.headers['content-type']?.startsWith('application/json'))){json(res,403,{error:'Запрос отклонён'});return}try{if(req.method==='GET'&&u.pathname==='/api/wb/economics'){json(res,200,await wbEconomics.read({from:u.searchParams.get('from'),to:u.searchParams.get('to'),storeId:u.searchParams.get('store')||undefined}));return}if(req.method==='GET'&&u.pathname==='/api/truestats/status'){json(res,200,trueStats.status());return}if(req.method==='GET'&&u.pathname==='/api/economics/compare'){
 const id=u.searchParams.get('store')||'';if(id&&(!Object.hasOwn(stores,id)||stores[id].market==='WB')){json(res,400,{error:'Выберите магазин Ozon'});return}
 const selected=publicStores().filter(s=>!s.id.startsWith('wb-')&&(!id||s.id===id));
 const values=selected.map(s=>({id:s.id,name:s.name,ledger:ledgerFor(s.id),extra:insightsSync.read(s.id),products:require('./dist/dashboard-model.js').rowsFor([s],new Map([[s.id,publicSnapshot(s.id)]]))}));
 const report=require('./insights.cjs').report(values,{from:u.searchParams.get('from'),to:u.searchParams.get('to')});
 const comparison=await trueStats.compare({period:report.current,stores:selected.map(s=>({id:s.id,name:s.name})),localEconomics:report.economics});
 json(res,200,comparison);return
}if(req.method==='GET'&&u.pathname==='/api/stores'){json(res,200,publicStores());return}if(req.method==='GET'&&u.pathname==='/api/data'){const id=u.searchParams.get('id');if(!/^(?:wb-)?[0-9]+$/.test(id)||!stores[id]){json(res,404,{error:'Магазин не подключён'});return}json(res,200,publicSnapshot(id));return}if(req.method==='GET'&&u.pathname==='/api/insights'){backgroundRefresh();const id=u.searchParams.get('store')||'';if(id&&!Object.hasOwn(stores,id)){json(res,404,{error:'Магазин не подключён'});return}const selected=publicStores().filter(s=>!s.id.startsWith('wb-')&&(!id||s.id===id));const values=selected.map(s=>({id:s.id,name:s.name,ledger:ledgerFor(s.id),extra:insightsSync.read(s.id),products:require('./dist/dashboard-model.js').rowsFor([s],new Map([[s.id,publicSnapshot(s.id)]]))}));try{const report=require('./insights.cjs').report(values,{from:u.searchParams.get('from'),to:u.searchParams.get('to'),hideInactive:u.searchParams.get('hideInactive')!=='false'});json(res,200,{...report,intraday:report.days===1?intraday.series(selected.map(s=>s.id),report.current.from):null,refresh:{intervalMinutes:30,background:true,nextAt:selected.length?selected.flatMap(s=>[insightsSync.next(s.id),refreshPolicy.nextAt(refreshState(s.id))]).sort()[0]:null,error:historyError},jobs:insightsSync.status(),syncJobs:selected.map(s=>jobs.get(s.id)||null)});}catch(e){json(res,400,{error:e.message})}return}if(req.method==='GET'&&u.pathname==='/api/insights/sources'){insightsSync.ensure();json(res,200,{stores:Object.entries(stores).filter(([,s])=>s.market!=='WB').map(([id,s])=>({id,name:s.name,data:insightsSync.read(id)})),jobs:insightsSync.status()});return}if(req.method==='GET'&&u.pathname==='/api/manage'){json(res,200,{products:management.products(),...management.state(),priceJobs:pricing.status()});return}if(req.method!=='POST'){json(res,404,{error:'Не найдено'});return}let raw='';for await(const chunk of req){raw+=chunk;if(Buffer.byteLength(raw)>1500000)throw Error('Слишком большой запрос')}const body=JSON.parse(raw);
if(u.pathname==='/api/truestats/connect'){try{const result=await trueStats.connect(body.key);json(res,200,result)}catch{json(res,400,{error:'TrueStats не подключён. Проверьте токен, срок действия и доступ к отчётам.'})}return}
if(u.pathname==='/api/insights/refresh'){if(body.store&&(!Object.hasOwn(stores,body.store)||stores[body.store].market==='WB'))throw Error('Проверьте магазин Ozon');const ids=Object.keys(stores).filter(id=>stores[id].market!=='WB'&&(!body.store||body.store===id));for(const id of ids){void insightsSync.sync(id);void sync(id);}json(res,200,{ok:true});return}
if(u.pathname==='/api/manage/preview'){json(res,200,management.preview(body));return}
if(u.pathname==='/api/manage/drafts'){json(res,200,management.create(body));return}
if(u.pathname==='/api/manage/transition'){json(res,200,management.transition(body));return}
if(u.pathname==='/api/manage/note'){json(res,200,management.note(body));return}
if(u.pathname==='/api/manage/refresh-prices'){if(!Array.isArray(body.ids)||!body.ids.length||body.ids.length>5||body.ids.some(id=>typeof id!=='string'||!Object.hasOwn(stores,id)))throw Error('Проверьте магазины');for(const id of new Set(body.ids))void pricing.refresh(id);json(res,200,{ok:true});return}
if(u.pathname==='/api/connect-wb'){const id=await wbConnector.connect(body.key);json(res,200,{ok:true,id});return}if(u.pathname==='/api/connect'){if(!allowedNames.includes(body.name)||!/^\d+$/.test(body.clientId)||typeof body.key!=='string'||body.key.length<20||body.key.length>500)throw Error('Проверьте магазин, Client ID и ключ');if(stores[body.clientId])throw Error('Этот магазин уже подключён');const s={name:body.name,clientId:body.clientId};await api(s,body.key,'/v3/product/list',{filter:{visibility:'ALL'},last_id:'',limit:1});s.key=await protect(body.key);s.connectedAt=new Date().toISOString();stores[body.clientId]=s;save();json(res,200,{ok:true,id:body.clientId});void sync(body.clientId);return}if(u.pathname==='/api/sync'){if(!stores[body.id])throw Error('Магазин не подключён');void sync(body.id);json(res,200,{ok:true});return}json(res,404,{error:'Не найдено'})}catch(e){json(res,e.public?e.status:400,{error:e.public?e.message:e.message?.includes('WB')||e.message?.includes('Ozon')||e.message?.includes('Магазин')||e.message?.includes('Проверьте')||e.message?.includes('магазин')?e.message:'Не удалось выполнить запрос'})}return}
if(req.method!=='GET'){res.writeHead(405).end();return}const pathname=u.pathname==='/'?'/index.html':u.pathname;const file=path.resolve(root,'.'+pathname);if(!file.startsWith(root+path.sep)||!['.html','.css','.js','.svg','.png'].includes(path.extname(file))){res.writeHead(404).end();return}if(!sessions.has(token)&&path.extname(file)==='.html'){const t=crypto.randomBytes(32).toString('hex');sessions.add(t);res.setHeader('Set-Cookie','pult_session='+t+'; HttpOnly; SameSite=Strict; Path=/')}fs.readFile(file,(e,b)=>{if(e){res.writeHead(404).end();return}res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.setHeader('Cache-Control','no-store');res.end(b)})}).listen(port,'127.0.0.1',()=>{console.log(origin);setTimeout(backgroundRefresh,1000).unref();setInterval(backgroundRefresh,30000).unref()});
