'use strict';
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const { spawn } = require('node:child_process');
const { once } = require('node:events');
const { initialize, createDispatcher, parsePlan } = require('../dispatcher.cjs');
const directors = require('../directors-catalog.cjs');
const plan = { tasks: [{ directorId: 'development', title: 'Архитектура', instruction: 'Подготовь архитектуру' }, { directorId: 'quality', title: 'Проверка', instruction: 'Проверь план' }] };
assert.equal(parsePlan(JSON.stringify(plan), directors).length, 2);
assert.equal(parsePlan('```json\n' + JSON.stringify(plan) + '\n```', directors).length, 2);
for (const value of ['not JSON', '{}', '{"tasks":[]}', JSON.stringify({ ...plan, extra: true }), JSON.stringify({ tasks: Array(6).fill(plan.tasks[0]) }), JSON.stringify({ tasks: [{ ...plan.tasks[0], directorId: 'unknown' }] }), JSON.stringify({ tasks: [{ ...plan.tasks[0], instruction: 'x'.repeat(2001) }] }), JSON.stringify({ tasks: [{ ...plan.tasks[0], extra: 1 }] })]) assert.throws(() => parsePlan(value, directors));
const waitFor = async test => { for (let i = 0; i < 300; i++) { if (test()) return; await new Promise(resolve => setTimeout(resolve, 10)); } throw new Error('Timeout'); };
let db = { users: [{ username: 'admin', role: 'admin' }, { username: 'editor', role: 'editor' }], projects: { items: [{ id: 'p1', name: 'Chosen' }, { id: 'p2', name: 'NOT_SENT' }], tasks: [] }, state: { value: 'original' }, version: 7 };
initialize(db);
const capacity = new Set();
let available = true, hold = null;
const calls = [];
const adapter = { async generate(input) { calls.push(input); if (hold) await hold; return input.director.prompt.includes('Верни исключительно JSON') ? JSON.stringify(plan) : 'Result ' + input.director.id; } };
const dispatcher = createDispatcher({ getDb: () => db, save: next => { db = structuredClone(next); }, capacity, connection: () => ({ adapter, status: { available } }), directors });
const data = goal => ({ goal, projectId: 'p1', requestId: crypto.randomUUID() });
const runById = id => db.dispatchRuns.find(run => run.id === id);
(async () => {
  available = false;
  assert.throws(() => dispatcher.create('admin', data('Offline')), err => err.status === 503);
  assert.equal(db.dispatchRuns.length, 0);
  available = true;
  for (const invalid of [{ ...data('x'), goal: '' }, { ...data('x'), goal: 'x'.repeat(4001) }, { ...data('x'), requestId: 'bad' }, { ...data('x'), projectId: 'missing' }]) assert.throws(() => dispatcher.create('admin', invalid));
  capacity.add('chat:a'); capacity.add('chat:b');
  const input = data('Prepare project');
  const run = dispatcher.create('admin', input);
  assert.equal(run.status, 'planning');
  assert.equal(Object.hasOwn(run, 'username'), false);
  assert.equal(dispatcher.create('admin', input).id, run.id);
  assert.throws(() => dispatcher.create('admin', { ...input, goal: 'changed' }), err => err.status === 409);
  assert.throws(() => dispatcher.create('admin', data('another')), err => err.status === 409);
  await new Promise(resolve => setTimeout(resolve, 50));
  assert.equal(calls.length, 0, 'Planner waits for shared chat capacity');
  capacity.delete('chat:a');
  await waitFor(() => runById(run.id).status === 'planned');
  assert.equal(calls.length, 1);
  assert.equal(calls[0].project.name, 'Chosen');
  assert.equal(JSON.stringify(calls[0]).includes('NOT_SENT'), false);
  assert.equal(dispatcher.list('editor').length, 0);
  assert.throws(() => dispatcher.start('editor', run.id), err => err.status === 404);
  let release;
  hold = new Promise(resolve => { release = resolve; });
  assert.equal(dispatcher.start('admin', run.id).status, 'running');
  assert.equal(dispatcher.start('admin', run.id).status, 'running');
  await waitFor(() => calls.length === 2);
  assert.equal(capacity.size, 2);
  db = { ...db, state: { value: 'edited during generation' }, version: 8 };
  hold = null; release();
  await waitFor(() => runById(run.id).status === 'completed');
  assert.equal(calls.length, 3);
  assert.match(calls[2].history[0].text, /Result development/);
  assert.equal(db.state.value, 'edited during generation');
  assert.equal(db.version, 8);
  assert.equal(runById(run.id).tasks.every(task => task.status === 'done' && task.result), true);
  dispatcher.start('admin', run.id);
  assert.equal(calls.length, 3);
  assert.equal(db.projects.tasks.length, 0, 'Text assignments do not claim project implementation');
  capacity.clear();
  const revoked = dispatcher.create('editor', data('Revocation'));
  await waitFor(() => runById(revoked.id).status === 'planned');
  hold = new Promise(resolve => { release = resolve; });
  dispatcher.start('editor', revoked.id);
  await waitFor(() => capacity.size === 1);
  db.users.find(user => user.username === 'editor').disabled = true;
  const before = calls.length;
  hold = null; release();
  await waitFor(() => runById(revoked.id).status === 'failed');
  assert.equal(calls.length, before, 'No next task after revocation');
  assert.match(runById(revoked.id).error, /права/);
  for (let i = 0; i < 21; i++) {
    const completed = dispatcher.create('admin', data('Prune ' + i));
    await waitFor(() => runById(completed.id)?.status === 'planned');
    dispatcher.start('admin', completed.id);
    await waitFor(() => runById(completed.id)?.status === 'completed');
  }
  assert.equal(dispatcher.list('admin').length, 20);
  assert.throws(() => dispatcher.create('admin', input), err => err.status === 410, 'Pruned request cannot generate again');
  const restart = { dispatchRuns: [{ id: 'r', username: 'admin', status: 'running', tasks: [{ status: 'running' }, { status: 'queued' }] }], dispatchRequestMarkers: {} };
  assert.equal(initialize(restart), true);
  assert.equal(restart.dispatchRuns[0].status, 'failed');
  assert.equal(restart.dispatchRuns[0].tasks.every(task => task.status === 'failed'), true);
  assert.equal(initialize(restart), false);
  console.log('Dispatch unit tests passed: strict JSON, shared cap, sequencing, idempotency, private runs, project isolation, current-store preservation, revocation, pruning and restart recovery.');
})().then(apiTests).catch(err => { console.error(err); process.exitCode = 1; });

async function apiTests() {
  const tmp = fs.mkdtempSync(path.join(__dirname, 'dispatch-test-'));
  const serverFile = path.join(__dirname, '../server.cjs');
  const preload = path.join(tmp, 'preload.cjs');
  fs.writeFileSync(preload, `const Module=require('node:module'); const load=Module._load; Module._load=function(request,parent){if(request==='./ai-directors.cjs'&&parent.filename.endsWith('server.cjs'))return {getStatus:()=>({available:true,provider:'test'}),generate:async input=>input.director.prompt.includes('Верни исключительно JSON')?${JSON.stringify(JSON.stringify(plan))}:'Test result'};return load.apply(this,arguments);};`);
  let child, base;
  const request = async (url, method = 'GET', body, cookie, origin = base) => {
    const res = await fetch(base + url, { method, headers: { Origin: origin, 'Content-Type': 'application/json', ...(cookie ? { Cookie: cookie } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
    return { status: res.status, body: await res.json(), cookie: res.headers.get('set-cookie')?.split(';')[0] };
  };
  try {
    child = spawn(process.execPath, ['--require', preload, serverFile], { env: { ...process.env, HOST: '127.0.0.1', PORT: '0', OZON_DATA_DIR: tmp }, stdio: ['ignore', 'pipe', 'pipe'] });
    child.stderr.on('data', chunk => process.stderr.write(chunk));
    await new Promise((resolve, reject) => { child.once('exit', code => reject(new Error('Server exited ' + code))); child.stdout.on('data', chunk => { const match = String(chunk).match(/http:\/\/127\.0\.0\.1:\d+/); if (match) { base = match[0]; resolve(); } }); });
    const password = 'dispatch testing password';
    const admin = (await request('/api/setup', 'POST', { username: 'admin', password })).cookie;
    await request('/api/users', 'POST', { username: 'viewer', password, role: 'viewer' }, admin);
    await request('/api/users', 'POST', { username: 'editor', password, role: 'editor' }, admin);
    const viewer = (await request('/api/login', 'POST', { username: 'viewer', password })).cookie;
    const editor = (await request('/api/login', 'POST', { username: 'editor', password })).cookie;
    assert.equal((await request('/api/dispatch')).status, 401);
    const input = { goal: 'Build a plan', requestId: crypto.randomUUID() };
    assert.equal((await request('/api/dispatch', 'POST', input, viewer)).status, 403);
    assert.equal((await request('/api/dispatch', 'POST', input, admin, 'http://evil.example')).status, 403);
    const created = await request('/api/dispatch', 'POST', input, admin);
    assert.equal(created.status, 202);
    const id = created.body.run.id;
    assert.equal((await request('/api/dispatch', 'POST', input, admin)).body.run.id, id);
    assert.equal((await request('/api/dispatch', 'GET', undefined, editor)).body.runs.length, 0);
    assert.equal((await request('/api/dispatch/' + id + '/start', 'POST', {}, editor)).status, 404);
    assert.equal((await request('/api/dispatch/' + id + '/start', 'POST', {}, viewer)).status, 403);
    for (let i = 0; i < 100; i++) { const runs = (await request('/api/dispatch', 'GET', undefined, admin)).body.runs; if (runs[0].status === 'planned') break; await new Promise(resolve => setTimeout(resolve, 10)); }
    assert.equal((await request('/api/dispatch/' + id + '/start', 'POST', {}, admin)).status, 202);
    for (let i = 0; i < 100; i++) { const runs = (await request('/api/dispatch', 'GET', undefined, admin)).body.runs; if (runs[0].status === 'completed') break; await new Promise(resolve => setTimeout(resolve, 10)); }
    assert.equal((await request('/api/dispatch', 'GET', undefined, admin)).body.runs[0].status, 'completed');
    const disk = JSON.parse(fs.readFileSync(path.join(tmp, 'store.json'), 'utf8'));
    assert.equal(disk.dispatchRuns[0].status, 'completed');
    assert.equal(disk.users.length, 3);
    assert.equal(disk.version, 0);
    assert.equal(disk.projectsVersion, 0);
    console.log('Dispatch API tests passed: auth/roles/origin, private ownership, planning/start/poll, idempotency and persisted results; no real AI calls.');
  } finally { if (child && child.exitCode === null) { const exited = once(child, 'exit'); child.kill(); await exited; } fs.rmSync(tmp, { recursive: true, force: true }); }
}
