'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),m=require('../dist/business-dynamics-model.js');
const date='2026-09-24',STEP=900000,DAY=86400000,at=(d,n)=>new Date(m.start(d)+n*STEP).toISOString();
function day(d,{bins=96,revenue=100,orders=2,complete=true}={}){return {date:d,basis:'order-time',complete,totals:{orderedRevenue:bins*revenue,orderedUnits:bins*3,orderCount:bins*orders},intervals:Array.from({length:bins},(_,i)=>({from:at(d,i),to:at(d,i+1),orderedRevenue:revenue,orderedUnits:3,orderCount:orders,complete:true}))};}
function store(id='1',history=7){return {id,name:'Магазин '+id,market:'Ozon',updatedAt:at(date,48),days:[day(date,{bins:48,complete:false}),...Array.from({length:history},(_,i)=>day(m.shift(date,-i-1)))]};}
const payload=stores=>({period:{to:date},stores,events:[]}),build=(stores,opts={})=>m.build(payload(stores),{date,now:Date.parse(at(date,48)),...opts});
test('equal MSK cutoff, seven complete days and historical-share forecast',()=>{const a=build([store()]);assert.equal(a.kpis.today.value,4800);assert.equal(a.kpis.yesterdayAtSameTime.value,4800);assert.equal(a.kpis.pace.value,0);assert.equal(a.comparison.avg7dSameTime,4800);assert.equal(a.kpis.forecast.value,9600);assert.equal(a.kpis.forecast.sampleSize,7);assert.equal(a.series.forecast.at(-1).at,at(date,96));assert.equal(a.velocity.length,48);assert.equal(a.velocityComparison.value,0);assert.equal(a.series.today.at(-1).avgCheck,50);});
test('total and child checkbox never double count; empty selection stays empty',()=>{const a=store(),b=store('2');assert.equal(build([a,a,b],{selectedIds:['','1']}).kpis.today.value,9600);assert.equal(build([a,b],{selectedIds:['2']}).kpis.today.value,4800);assert.equal(build([a],{selectedIds:[]}).state,'empty');});
test('missing store, interval or historical day is not zero',()=>{const a=store(),b=store('2');b.days=[];const result=build([a,b]);assert.equal(result.kpis.today.value,4800);assert.equal(result.kpis.yesterdayAtSameTime.value,null);assert.equal(result.kpis.forecast.available,false);assert.equal(result.state,'partial');a.days[0].intervals.splice(4,1);assert.equal(build([a]).kpis.pace.value,null);assert.equal(build([store('1',6)]).comparison.avg7dSameTime,null);assert.equal(build([store('1',6)]).kpis.yesterdayAtSameTime.value,4800);});
test('zero previous base has no percentage and zero current has no forecast',()=>{const a=store();a.days[1]=day(m.shift(date,-1),{revenue:0});assert.equal(build([a]).kpis.pace.value,null);a.days[0]=day(date,{bins:48,revenue:0,complete:false});assert.equal(build([a]).kpis.today.value,0);assert.equal(build([a]).kpis.forecast.available,false);});
test('incomplete seven minutes of current bucket never compare to full interval',()=>{const a=store();a.days[0].intervals.push({...day(date).intervals[48],orderedRevenue:40,complete:false});const r=build([a],{now:Date.parse(at(date,48))+7*60000});assert.equal(r.asOf,at(date,48));assert.equal(r.kpis.today.value,4800);assert.equal(r.velocity.length,48);});
test('partial current bucket is timestamped at confirmed source cutoff, never its future end',()=>{const a=store();const cutoff=new Date(Date.parse(at(date,48))+7*60000).toISOString();a.updatedAt=cutoff;a.days[0].coverage={from:at(date,0),to:cutoff};a.days[0].intervals.push({...day(date).intervals[48],orderedRevenue:40,complete:false});const r=build([a],{now:Date.parse(at(date,49))});assert.equal(r.asOf,cutoff);assert.equal(r.kpis.today.value,4840);assert.equal(r.kpis.yesterdayAtSameTime.value,null);assert.equal(r.velocity.length,48);});
test('staggered observations keep known sum but disable exact-time comparisons',()=>{const a=store(),b=store('2');for(const [s,t,v] of [[a,48,100],[b,47,200]])s.days[0]={date,basis:'observation',complete:false,observations:[{at:at(date,t),orderedRevenue:v,orderedUnits:1,complete:true}]};const r=build([a,b]);assert.equal(r.kpis.today.value,300);assert.equal(r.series.today.at(-1).cumulative,300);assert.equal(r.series.today.at(-1).complete,false);assert.equal(r.kpis.yesterdayAtSameTime.value,null);assert.equal(r.velocity.length,0);assert.equal(r.series.today.at(-1).last15,null);});
test('mixed observation and order-time semantics never give precise comparisons',()=>{const a=store(),b=store('2');b.days[0]={date,basis:'observation',observations:[{at:at(date,48),orderedRevenue:200,orderedUnits:1,complete:true}]};const r=build([a,b]);assert.equal(r.state,'partial');assert.equal(r.kpis.pace.value,null);assert.equal(r.kpis.forecast.available,false);});
test('average check uses pooled revenue and order counts and has no additive forecast',()=>{const a=store();a.days[1]=day(m.shift(date,-1),{orders:10,revenue:300});const r=build([a],{metric:'avgCheck'});assert.equal(r.kpis.today.value,50);assert.equal(r.comparison.avg7dSameTime,(300+6*100)/(10+6*2));assert.equal(r.kpis.forecast.available,false);assert.equal(r.velocity.length,0);});
test('unknown order count remains unavailable, units are not orders',()=>{const a=store();for(const d of a.days){d.totals.orderCount=null;for(const i of d.intervals)i.orderCount=null;}assert.equal(build([a],{metric:'orderCount'}).kpis.today.value,null);assert.equal(build([a],{metric:'avgCheck'}).kpis.today.value,null);assert.equal(build([a]).series.today.at(-1).orders,null);});
test('forecast excludes an outlier and needs seven usable days after exclusion',()=>{const a=store('1',8);a.days[8]=day(m.shift(date,-8),{revenue:10000});assert.equal(build([a]).kpis.forecast.sampleSize,7);a.days.pop();a.days[7]=day(m.shift(date,-7),{revenue:10000});assert.equal(build([a]).kpis.forecast.available,false);});
test('freshness is oldest source, future points/events and foreign store events excluded',()=>{const a=store(),b=store('2');a.updatedAt=at(date,40);const p=payload([a,b]);p.events=[{kind:'price',at:at(date,20),storeId:'1'},{kind:'price',at:at(date,49)},{kind:'bid',at:at(date,30),storeId:'other'},{kind:'unsupported',at:at(date,10)}];const r=m.build(p,{now:Date.parse(at(date,48))});assert.equal(r.updatedAt,at(date,40));assert.equal(r.events.length,1);assert.equal(r.events[0].storeId,'1');});
