'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../dist/buyer-order-segments-ui.js'),'utf8'),html=fs.readFileSync(require.resolve('../dist/index.html'),'utf8'),css=fs.readFileSync(require.resolve('../dist/buyer-order-segments.css'),'utf8'),flush=()=>new Promise(resolve=>setImmediate(resolve));
function runtime(api,{from='2026-09-01',to='2026-09-07',sharedFrom=from,sharedTo=to,search='',hash=''}={}){
 const nodes=new Map(),listeners=new Map();let enabled=false;
 const typeButtons=['legal','individual','unknown'].map(type=>({dataset:{buyerType:type},classList:{toggle(){}},setAttribute(){}}));
 const initialValue=id=>id==='buyer-segment-from'?from:id==='buyer-segment-to'?to:id==='ins-from'?sharedFrom:id==='ins-to'?sharedTo:'';
 const node=id=>{if(!nodes.has(id))nodes.set(id,{id,value:initialValue(id),innerHTML:'',textContent:'',className:'',querySelectorAll:()=>id==='buyer-product-types'?typeButtons:[],addEventListener(type,fn){const key=id+':'+type,list=listeners.get(key)||[];list.push(fn);listeners.set(key,list)},dispatchEvent(event){for(const fn of listeners.get(id+':'+event.type)||[])fn(event)}});return nodes.get(id)};
 class Clock extends Date{constructor(...args){super(...(args.length?args:['2026-09-20T12:00:00Z']))}static now(){return Date.parse('2026-09-20T12:00:00Z')}}
 const context={window:{location:{search,hash}},document:{get hidden(){return false},getElementById:id=>id==='buyer-order-segments'&&!enabled?null:node(id)},Intl,Date:Clock,URLSearchParams,Event:class{constructor(type){this.type=type}},fetch:async()=>{throw Error('unexpected fetch')},setInterval:()=>1,clearInterval(){},setTimeout:fn=>fn(),console};vm.runInNewContext(source,context);enabled=true;const app=context.window.createPultBuyerOrderSegments({api});return {app,node,switchType(type){node('buyer-product-types').onclick({target:{closest:()=>({dataset:{buyerType:type}})}})},emit(id,type='change'){node(id).dispatchEvent({type})}};
}
const total=(units,orders=units,amountRub=units*100,currency='RUB')=>({units,orders,cancelledUnits:0,cancelledOrders:0,notCancelledUnits:units,notCancelledOrders:orders,cancellationUnknownUnits:0,cancellationUnknownOrders:0,amountRub,currency});
const totals=()=>({legal:total(5,3,1250),individual:total(8,6,2400),unknown:{...total(2,2),amountRub:null,currency:null}});
const report=complete=>({status:complete?'ready':'partial',period:{from:'2026-09-01',to:'2026-09-07'},totals:totals(),byStore:[{storeId:'1',name:'Ozon 1',market:'Ozon',totals:{legal:total(5,3),individual:total(8,6),unknown:total(2,2)}}],coverage:{complete,includedRecords:11,invalidRecords:0,duplicateRecords:0,sources:[{market:'Ozon',scheme:'FBO',complete,available:true,limitation:null}]},source:{metric:'gross_ordered_item_units',commonFreshnessAt:'2026-09-20T10:00:00.000Z'},limitations:['Это заказанные единицы товара, а не реализованные продажи.']});
const productReport=(buyerType='legal',complete=false,extra={})=>({status:complete?'ready':'partial',buyerType,period:{from:'2026-09-01',to:'2026-09-07'},totals:totals(),products:[{productId:'101',name:'Крепёж <тест>',sku:'101',market:'Ozon',storeName:'Ozon 1',orderedUnits:7,buyerShare:.7,amountRub:1789.5,currency:'RUB',cancelledUnits:2,cancellationUnknownUnits:0}],coverage:{complete,sources:[{market:'Ozon',scheme:'FBO',complete,available:true}]},...extra});
const paired=data=>async url=>url.includes('/api/buyer-product-segments')?productReport(new URL('http://x'+url).searchParams.get('buyerType')):data;
test('panel names order-based buyer sales, exposes all switches and six product columns',()=>{assert.match(html,/rel="icon"[^>]+\/favicons\/index\.svg/);assert.match(html,/Продажи по типам покупателей/);assert.match(html,/Выкуп и выручка не подтверждены этими данными/);for(const type of ['legal','individual','unknown'])assert.match(html,new RegExp('data-buyer-type="'+type+'"'));assert.match(html,/colspan="6"/);assert.match(css,/buyer-product-types button\.active/)});
test('without shared or user dates defaults to the last seven completed Moscow days',async()=>{const urls=[];const view=runtime(async url=>{urls.push(url);return url.includes('/api/buyer-product-segments')?{...productReport('legal'),period:{from:'2026-09-13',to:'2026-09-19'}}:{...report(false),period:{from:'2026-09-13',to:'2026-09-19'}}},{from:'',to:'',sharedFrom:'',sharedTo:''});await flush();assert.equal(view.node('buyer-segment-from').value,'2026-09-13');assert.equal(view.node('buyer-segment-to').value,'2026-09-19');assert.ok(urls.every(url=>url.includes('from=2026-09-13')&&url.includes('to=2026-09-19')));view.app.destroy()});
test('direct buyers view ignores auto-initialized today in hidden insights dates',async()=>{const urls=[];const view=runtime(async url=>{urls.push(url);return url.includes('/api/buyer-product-segments')?{...productReport('legal'),period:{from:'2026-09-13',to:'2026-09-19'}}:{...report(false),period:{from:'2026-09-13',to:'2026-09-19'}}},{from:'',to:'',sharedFrom:'2026-09-20',sharedTo:'2026-09-20',search:'?view=buyers'});await flush();assert.equal(view.node('buyer-segment-from').value,'2026-09-13');assert.equal(view.node('buyer-segment-to').value,'2026-09-19');assert.ok(urls.every(url=>url.includes('from=2026-09-13')&&url.includes('to=2026-09-19')));view.app.destroy()});
test('complete order and product totals show units and proper money while unknown money remains a dash',async()=>{const view=runtime(async url=>url.includes('/api/buyer-product-segments')?productReport('legal',true):report(true));await flush();const cards=view.node('buyer-segment-cards').innerHTML;assert.match(cards,/<strong>5<\/strong>/);assert.match(cards,/3 заказов/);assert.match(cards,/1[\s\u00a0]?250[^<]*₽/);assert.match(cards,/Тип не указан[\s\S]*Сумма заказов неизвестна/);view.app.destroy()});
test('partial order totals never become zero or a false complete amount',async()=>{const view=runtime(paired(report(false)));await flush();const cards=view.node('buyer-segment-cards').innerHTML;assert.match(cards,/<strong>—<\/strong>/);assert.doesNotMatch(cards,/<strong>0<\/strong>/);assert.match(cards,/Сумма скрыта до полного покрытия/);view.app.destroy()});
test('product switch sends buyerType and renders generic fields without HTML injection',async()=>{const urls=[];const view=runtime(async url=>{urls.push(url);return url.includes('/api/buyer-product-segments')?productReport(new URL('http://x'+url).searchParams.get('buyerType')):report(true)});await flush();assert.match(urls.find(url=>url.includes('/api/buyer-product-segments')),/buyerType=legal/);view.switchType('individual');await flush();assert.match(urls.at(-1),/buyerType=individual/);assert.equal(view.node('buyer-product-title').textContent,'Товары: физлица');assert.match(view.node('buyer-product-rows').innerHTML,/Крепёж &lt;тест&gt;/);assert.match(view.node('buyer-product-rows').innerHTML,/>7<\/td>/);assert.match(view.node('buyer-product-rows').innerHTML,/70\s?%/);assert.match(view.node('buyer-product-rows').innerHTML,/1[\s\u00a0]?789,5[^<]*₽/);view.app.destroy()});
test('switch race ignores an older product response for another buyer type',async()=>{const pending=[];const view=runtime(url=>url.includes('/api/buyer-product-segments')?new Promise(resolve=>pending.push({url,resolve})):Promise.resolve(report(true)));await flush();view.switchType('individual');await flush();pending[0].resolve(productReport('legal',true,{products:[{name:'Старый ответ',orderedUnits:99,buyerShare:1}]}));await flush();assert.doesNotMatch(view.node('buyer-product-rows').innerHTML,/Старый ответ/);pending[1].resolve(productReport('individual'));await flush();assert.match(view.node('buyer-product-title').textContent,/физлица/);view.app.destroy()});
test('unknown currency and incomplete product response do not invent a zero amount',async()=>{const products=productReport('unknown',false,{products:[{name:'Без валюты',orderedUnits:4,buyerShare:.2,amountRub:999,currency:null,cancelledUnits:0}]});const view=runtime(async url=>url.includes('/api/buyer-product-segments')?products:report(true));view.switchType('unknown');await flush();assert.match(view.node('buyer-product-rows').innerHTML,/Без валюты/);assert.match(view.node('buyer-product-rows').innerHTML,/<td class="numeric">—<\/td>/);assert.doesNotMatch(view.node('buyer-product-rows').innerHTML,/>0 ₽<\/td>/);assert.match(view.node('buyer-product-state').textContent,/Частичные данные/);view.app.destroy()});
test('product totals provide an explicit partial fallback when order totals are unavailable',async()=>{const unavailable={...report(false),status:'unavailable',totals:null,byStore:[]};const view=runtime(async url=>url.includes('/api/buyer-product-segments')?productReport('legal',false):unavailable);await flush();assert.match(view.node('buyer-segment-cards').innerHTML,/<strong>5<\/strong>/);assert.match(view.node('buyer-segment-cards').innerHTML,/Загруженная часть периода/);assert.match(view.node('buyer-segment-source').textContent,/только по загруженным товарным строкам/);view.app.destroy()});
test('partial fallback does not present a zero segment as a known zero',async()=>{const unavailable={...report(false),status:'unavailable',totals:null,byStore:[]},products=productReport('legal',false);products.totals.unknown={units:0,cancelledUnits:0,cancellationUnknownUnits:0,amountRub:0,currency:'RUB'};const view=runtime(async url=>url.includes('/api/buyer-product-segments')?products:unavailable);await flush();const unknownCard=view.node('buyer-segment-cards').innerHTML.split('Тип не указан')[1];assert.match(unknownCard,/<strong>—<\/strong>/);assert.match(unknownCard,/Нет подтверждённых данных/);assert.doesNotMatch(unknownCard,/<strong>0<\/strong>/);view.app.destroy()});
test('market filter changes also discard both stale responses',async()=>{const pending=[];const view=runtime(url=>new Promise(resolve=>pending.push({url,resolve})));await flush();view.node('market').value='WB';view.emit('market');await flush();pending[0].resolve({...report(true),totals:{...totals(),legal:total(99)}});pending[1].resolve(productReport('legal',true,{products:[{name:'Старый товар',orderedUnits:99,buyerShare:1}]}));await flush();assert.doesNotMatch(view.node('buyer-segment-cards').innerHTML,/<strong>99<\/strong>/);assert.doesNotMatch(view.node('buyer-product-rows').innerHTML,/Старый товар/);pending[2].resolve({...report(true),byStore:[],coverage:{...report(true).coverage,sources:[{market:'WB',complete:true}]}});pending[3].resolve(productReport('legal',true,{products:[{name:'Новый товар',orderedUnits:4,buyerShare:1,amountRub:400,currency:'RUB',cancelledUnits:0}]}));await flush();assert.match(view.node('buyer-product-rows').innerHTML,/Новый товар/);view.app.destroy()});
