'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const source=require('../buyer-order-segments.cjs'),apiModule=require('../buyer-order-segments-api.cjs');
const DAY='2026-09-20';
function fixture(t){const privateDir=fs.mkdtempSync(path.join(os.tmpdir(),'buyer-segments-api-'));t.after(()=>fs.rmSync(privateDir,{recursive:true,force:true}));const record=source.projectOzonPosting({posting_number:'order-1',created_at:DAY+'T09:00:00Z',products:[{quantity:2}],analytics_data:{is_legal:true},status:'awaiting_deliver'},{scheme:'FBO',storeId:'1',storeName:'Первый'});const sources=[{market:'Ozon',scheme:'FBO',storeId:'1',name:'Первый',from:DAY,to:DAY,available:true,complete:true,fetchedAt:DAY+'T10:00:00Z'},{market:'Ozon',scheme:'FBS',storeId:'1',name:'Первый',from:DAY,to:DAY,available:true,complete:true,fetchedAt:DAY+'T10:01:00Z'}];fs.writeFileSync(path.join(privateDir,`buyer-order-segments-${DAY}_${DAY}.json`),JSON.stringify({records:[record],report:{coverage:{sources}},privateNote:'never expose'}));return {privateDir,stores:{1:{name:'Первый'},'wb-1':{name:'Второй',market:'WB'}}}}
test('exact Ozon snapshot returns public counts without source contracts or private fields',t=>{const f=fixture(t),value=apiModule.create(f).read({from:DAY,to:DAY,market:'Ozon'});assert.equal(value.status,'ready');assert.equal(value.coverage.complete,true);assert.equal(value.totals.legal.units,2);assert.equal(value.totals.unknown.units,0);assert.equal(value.source.commonFreshnessAt,DAY+'T10:00:00.000Z');assert.equal('contracts' in value.source,false);assert.doesNotMatch(JSON.stringify(value),/privateNote|sourceUrl|route/)});
test('combined scope stays partial while a connected marketplace source is absent',t=>{const f=fixture(t),value=apiModule.create(f).read({from:DAY,to:DAY,market:'all'});assert.equal(value.status,'partial');assert.equal(value.coverage.complete,false);assert.equal(value.totals.legal.units,2);assert.ok(value.coverage.sources.some(item=>item.market==='WB'&&item.available===false))});
test('missing range and WB-only scope fail closed with null totals',t=>{const service=apiModule.create(fixture(t));for(const options of [{from:'2026-09-19',to:'2026-09-19',market:'Ozon'},{from:DAY,to:DAY,market:'WB'}]){const value=service.read(options);assert.equal(value.status,'unavailable');assert.equal(value.totals,null)}});
test('invalid period, market and store are rejected',t=>{const service=apiModule.create(fixture(t));assert.throws(()=>service.read({from:'2026-02-30',to:DAY}),/период/);assert.throws(()=>service.read({from:DAY,to:DAY,market:'Other'}),/площадку/);assert.throws(()=>service.read({from:DAY,to:DAY,storeId:'missing'}),/магазин/)});
