'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../dist/buyer-order-segments-ui.js'),'utf8'),html=fs.readFileSync(require.resolve('../dist/index.html'),'utf8'),css=fs.readFileSync(require.resolve('../dist/buyer-order-segments.css'),'utf8'),flush=()=>new Promise(resolve=>setImmediate(resolve));
function runtime(api){
 const nodes=new Map(),listeners=new Map();let enabled=false;
 const node=id=>{if(!nodes.has(id))nodes.set(id,{id,value:['ins-from','buyer-segment-from'].includes(id)?'2026-09-01':['ins-to','buyer-segment-to'].includes(id)?'2026-09-07':'',innerHTML:'',textContent:'',className:'',addEventListener(type,fn){const key=id+':'+type,list=listeners.get(key)||[];list.push(fn);listeners.set(key,list)},dispatchEvent(event){for(const fn of listeners.get(id+':'+event.type)||[])fn(event)}});return nodes.get(id)};
 class Clock extends Date{constructor(...args){super(...(args.length?args:['2026-09-20T12:00:00Z']))}static now(){return Date.parse('2026-09-20T12:00:00Z')}}
 const context={window:{},document:{get hidden(){return false},getElementById:id=>id==='buyer-order-segments'&&!enabled?null:node(id)},Intl,Date:Clock,URLSearchParams,Event:class{constructor(type){this.type=type}},fetch:async()=>{throw Error('unexpected fetch')},setInterval:()=>1,clearInterval(){},setTimeout:fn=>fn(),console};vm.runInNewContext(source,context);enabled=true;const app=context.window.createPultBuyerOrderSegments({api});return {app,node,emit(id,type='change'){node(id).dispatchEvent({type})}};
}
const total=(units,orders=units)=>({units,orders,cancelledUnits:0,cancelledOrders:0,notCancelledUnits:units,notCancelledOrders:orders,cancellationUnknownUnits:0,cancellationUnknownOrders:0});
const report=complete=>({status:complete?'ready':'partial',period:{from:'2026-09-01',to:'2026-09-07'},totals:{legal:total(5,3),individual:total(8,6),unknown:total(2,2)},byStore:[{storeId:'1',name:'Ozon 1',market:'Ozon',totals:{legal:total(5,3),individual:total(8,6),unknown:total(2,2)}}],coverage:{complete,includedRecords:11,invalidRecords:0,duplicateRecords:0,sources:[{market:'Ozon',scheme:'FBO',complete,available:true,limitation:null}]},source:{metric:'gross_ordered_item_units',commonFreshnessAt:'2026-09-20T10:00:00.000Z'},limitations:['Это заказанные единицы товара, а не реализованные продажи.']});
const productReport=complete=>({status:complete?'ready':'partial',period:{from:'2026-09-01',to:'2026-09-07'},products:[{productId:'101',name:'Крепёж тестовый',sku:'101',market:'Ozon',storeName:'Ozon 1',legalUnits:7,legalShare:.7,cancelledUnits:2,cancellationUnknownUnits:0}],coverage:{complete,sources:[{market:'Ozon',scheme:'FBO',complete,available:true}]}});
const paired=data=>async url=>url.includes('/api/buyer-product-segments')?productReport(false):data;
test('overview contains buyer totals and named product ranking and preserves the favicon',()=>{assert.match(html,/rel="icon"[^>]+\/favicons\/index\.svg/);assert.match(html,/id="buyer-order-segments"/);assert.match(html,/Кто заказывает наши товары/);assert.match(html,/Товары, которые чаще заказывают юрлица/);assert.match(html,/buyer-order-segments-ui\.js/);assert.match(css,/buyer-product-heading/)});
test('combined segment values require complete coverage and never turn missing into zero',async()=>{let data=report(false);const view=runtime(async url=>url.includes('/api/buyer-product-segments')?productReport(false):data);await flush();assert.match(view.node('buyer-segment-cards').innerHTML,/Юрлица/);assert.match(view.node('buyer-segment-cards').innerHTML,/<strong>—<\/strong>/);assert.doesNotMatch(view.node('buyer-segment-cards').innerHTML,/<strong>0<\/strong>/);data=report(true);await view.app.load();assert.match(view.node('buyer-segment-cards').innerHTML,/<strong>5<\/strong>/);assert.match(view.node('buyer-segment-cards').innerHTML,/3 заказов/);view.app.destroy()});
test('partial product ranking keeps names, units, share and cancellations visible with a warning',async()=>{const view=runtime(paired(report(true)));await flush();assert.match(view.node('buyer-product-rows').innerHTML,/Крепёж тестовый/);assert.match(view.node('buyer-product-rows').innerHTML,/>7<\/td>/);assert.match(view.node('buyer-product-rows').innerHTML,/70\s?%/);assert.match(view.node('buyer-product-rows').innerHTML,/>2<\/td>/);assert.match(view.node('buyer-product-state').textContent,/Частичные данные/);view.app.destroy()});
test('unavailable response clears figures instead of rendering zero',async()=>{const value={...report(true),status:'unavailable',totals:null,byStore:[],coverage:{complete:false,sources:[]}};const view=runtime(paired(value));await flush();assert.match(view.node('buyer-segment-state').textContent,/не готовы/i);assert.doesNotMatch(view.node('buyer-segment-cards').innerHTML,/<strong>0<\/strong>/);view.app.destroy()});
test('scope changes ignore stale replies and errors clear previously shown figures',async()=>{const pending=[];const view=runtime(url=>url.includes('/api/buyer-product-segments')?Promise.resolve(productReport(false)):new Promise((resolve,reject)=>pending.push({resolve,reject})));await flush();view.node('market').value='WB';const current=view.app.load();await flush();pending[0].resolve(report(true));await flush();assert.doesNotMatch(view.node('buyer-segment-cards').innerHTML,/<strong>5<\/strong>/);const wb={...report(true),byStore:[],coverage:{...report(true).coverage,sources:[{market:'WB',scheme:'FBS',complete:true,available:true,limitation:null}]}};pending[1].resolve(wb);await current;assert.match(view.node('buyer-segment-state').textContent,/подтверждено/i);const failed=view.app.load();await flush();pending[2].reject(Error('Источник временно недоступен'));await failed;assert.match(view.node('buyer-segment-state').textContent,/недоступен/);assert.doesNotMatch(view.node('buyer-segment-cards').innerHTML,/<strong>5<\/strong>/);view.app.destroy()});
