'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const apiModule=require('../buyer-product-segments-api.cjs');
const FROM='2026-09-01',TO='2026-09-07';
function segment(units,{cancelledUnits=0,amountRub=null,amountKnown=false}={}){return {units,orders:units,cancelledUnits,cancelledOrders:cancelledUnits,cancellationUnknownUnits:0,cancellationUnknownOrders:0,amountRub,amountKnown}}
function fixture(t,{partial=true}={}){const privateDir=fs.mkdtempSync(path.join(os.tmpdir(),'buyer-products-api-'));t.after(()=>fs.rmSync(privateDir,{recursive:true,force:true}));const sources=[{market:'Ozon',scheme:'FBO',storeId:'1',name:'Первый',available:true,complete:!partial,coversRequested:true},{market:'Ozon',scheme:'FBS',storeId:'1',name:'Первый',available:true,complete:true,coversRequested:true}];const value={status:partial?'partial':'ready',period:{from:FROM,to:TO},products:[{productId:'101',segments:{legal:segment(7,{cancelledUnits:2,amountRub:700,amountKnown:true}),individual:segment(3)},legalShare:.7},{productId:'102',segments:{legal:segment(4,{amountRub:999,amountKnown:false}),individual:segment(0)},legalShare:1}],coverage:{sources},privateNote:'never expose'};fs.writeFileSync(path.join(privateDir,`buyer-product-segments-${FROM}_${TO}.${partial?'partial.':''}json`),JSON.stringify(value));const stores={1:{name:'Первый'},'wb-1':{name:'WB',market:'WB'}};const catalogs={1:{products:[{sku:101,name:'Первый товар'},{sku:102,name:'Второй товар'}]},'wb-1':{products:[{nmID:201,name:'WB товар'}]}};return {privateDir,stores,catalogForStore:id=>catalogs[id]}}
test('returns named ranked products with units, share and cancellations',t=>{const value=apiModule.create(fixture(t)).read({from:FROM,to:TO,market:'Ozon'});assert.equal(value.status,'partial');assert.equal(value.products[0].name,'Первый товар');assert.equal(value.products[0].legalUnits,7);assert.equal(value.products[0].legalShare,.7);assert.equal(value.products[0].cancelledUnits,2);assert.equal(value.products[0].currency,'RUB');assert.equal(value.products[1].amountRub,null);assert.equal(value.products[1].currency,null);assert.doesNotMatch(JSON.stringify(value),/privateNote/)});
test('combined scope remains partial when connected WB has no source and WB-only fails closed',t=>{const service=apiModule.create(fixture(t,{partial:false})),all=service.read({from:FROM,to:TO,market:'all'}),wb=service.read({from:FROM,to:TO,market:'WB'});assert.equal(all.status,'partial');assert.ok(all.coverage.sources.some(source=>source.market==='WB'&&!source.available));assert.equal(wb.status,'unavailable');assert.deepEqual(wb.products,[])});
test('exact store filter uses its catalog and unknown periods never become zero',t=>{const service=apiModule.create(fixture(t)),value=service.read({from:FROM,to:TO,storeId:'1'}),missing=service.read({from:'2026-09-08',to:'2026-09-08'});assert.equal(value.products.length,2);assert.equal(value.products[0].storeName,'Первый');assert.equal(missing.status,'unavailable');assert.deepEqual(missing.products,[])});
test('rejects invalid filters and bounded limit',t=>{const service=apiModule.create(fixture(t));assert.throws(()=>service.read({from:'2026-02-30',to:TO}),/период/);assert.throws(()=>service.read({from:FROM,to:TO,market:'Other'}),/площадку/);assert.throws(()=>service.read({from:FROM,to:TO,storeId:'missing'}),/магазин/);assert.throws(()=>service.read({from:FROM,to:TO,limit:101}),/размер/)})
test('builds a partial ranking from overlapping local order snapshots',t=>{const value=fixture(t),file=path.join(value.privateDir,`buyer-product-segments-${FROM}_${TO}.partial.json`);fs.rmSync(file);const snapshot={generatedAt:'2026-09-08T00:00:00Z',records:[{id:'r1',market:'Ozon',storeId:'1',scheme:'FBO',orderKey:'o1',buyerType:'legal'}],productOrders:[{market:'Ozon',storeId:'1',scheme:'FBO',orderId:'o1',postingId:'p1',productId:'101',orderedAt:'2026-09-03T10:00:00Z',units:5,amountRub:500,cancelled:false,updatedAt:'2026-09-08T00:00:00Z'}],report:{coverage:{sources:[{market:'Ozon',scheme:'FBO',storeId:'1',name:'Первый',available:true,complete:true,from:FROM,to:'2026-09-06'}]}}};fs.writeFileSync(path.join(value.privateDir,`buyer-order-segments-${FROM}_2026-09-06.json`),JSON.stringify(snapshot));const result=apiModule.create(value).read({from:FROM,to:TO,market:'Ozon'});assert.equal(result.status,'partial');assert.equal(result.products[0].legalUnits,5);assert.equal(result.products[0].storeId,'1');assert.ok(result.coverage.sources.some(source=>source.available&&!source.complete))})
test('filters raw products by requested market before catalog resolution',t=>{const value=fixture(t),file=path.join(value.privateDir,`buyer-product-segments-${FROM}_${TO}.partial.json`),raw=JSON.parse(fs.readFileSync(file,'utf8'));raw.products.unshift({market:'WB',storeId:'wb-1',productId:'201',segments:{legal:segment(99)},legalShare:1});fs.writeFileSync(file,JSON.stringify(raw));const result=apiModule.create(value).read({from:FROM,to:TO,market:'Ozon'});assert.equal(result.products.some(product=>product.market==='WB'||product.productId==='201'),false)})
test('non-overlapping saved sources remain unavailable',t=>{const value=fixture(t),file=path.join(value.privateDir,`buyer-product-segments-${FROM}_${TO}.partial.json`);fs.rmSync(file);const snapshot={generatedAt:'2026-09-08T00:00:00Z',records:[],productOrders:[],report:{coverage:{sources:[{market:'Ozon',scheme:'FBO',storeId:'1',available:true,complete:true,from:FROM,to:TO}]}}};fs.writeFileSync(path.join(value.privateDir,`buyer-order-segments-${FROM}_${TO}.json`),JSON.stringify(snapshot));const result=apiModule.create(value).read({from:'2026-08-01',to:'2026-08-07',market:'Ozon'});assert.equal(result.status,'unavailable');assert.deepEqual(result.products,[])})
test('marks a scheme partial when its evidenced orders have no product rows',t=>{const value=fixture(t),file=path.join(value.privateDir,`buyer-product-segments-${FROM}_${TO}.partial.json`);fs.rmSync(file);const snapshot={generatedAt:'2026-09-08T00:00:00Z',records:[{id:'fbo',market:'Ozon',storeId:'1',scheme:'FBO',orderKey:'o1',buyerType:'legal'},{id:'fbs',market:'Ozon',storeId:'1',scheme:'FBS',orderKey:'o2',buyerType:'legal'}],productOrders:[{market:'Ozon',storeId:'1',scheme:'FBO',orderId:'o1',postingId:'p1',productId:'101',orderedAt:'2026-09-03T10:00:00Z',units:5,amountRub:500,cancelled:false,updatedAt:'2026-09-08T00:00:00Z'}],report:{coverage:{sources:[{market:'Ozon',scheme:'FBO',storeId:'1',available:true,complete:true,from:FROM,to:TO},{market:'Ozon',scheme:'FBS',storeId:'1',available:true,complete:true,from:FROM,to:TO}]}}};fs.writeFileSync(path.join(value.privateDir,`buyer-order-segments-${FROM}_${TO}.json`),JSON.stringify(snapshot));const result=apiModule.create(value).read({from:FROM,to:TO,market:'Ozon'});assert.equal(result.status,'partial');assert.equal(result.products[0].legalUnits,5);assert.ok(result.coverage.sources.some(source=>source.scheme==='FBS'&&!source.available&&!source.complete))})
