const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const finance=require('../finance-module.cjs');
const period={from:'2026-09-01',to:'2026-09-30'};
function store(values,{complete=true,from=period.from,to=period.to}={}){return {id:'1',name:'Ozon',updatedAt:'2026-09-20T10:00:00Z',ledger:{version:3,complete,foreignRecords:0,period:{from,to},daily:values.map(([date,net,records=1])=>({date,values:{net:Math.round(net*100),records}}))}}}
test('accrual series preserves negative corrections and does not replace incomplete total with zero',()=>{let r=finance.buildReport({stores:[store([['2026-09-02',100],['2026-09-03',-25]])],state:{loans:[],payments:[]},...period});assert.equal(r.accruals.value,75);assert.deepEqual(r.accruals.series.map(x=>x.net),[100,-25]);assert.equal(r.bankCash.net,null);assert.equal(r.profit.value,null);r=finance.buildReport({stores:[store([['2026-09-02',100]],{complete:false})],state:{loans:[],payments:[]},...period});assert.equal(r.accruals.value,null);assert.equal(r.accruals.knownSubtotal,100);assert.equal(r.accruals.status,'partial')});
test('principal is financing while interest and fees are expenses',()=>{const state={updatedAt:'2026-09-20T10:00:00Z',loans:[{id:'l',status:'active',outstandingPrincipal:800}],payments:[{loanId:'l',date:'2026-09-10',principal:200,interest:30,fee:5},{loanId:'l',date:'2026-08-10',principal:100,interest:20,fee:0}]};const d=finance.debtSummary(state,period.from,period.to);assert.equal(d.summary.principalPaid,200);assert.equal(d.summary.interestExpense,30);assert.equal(d.summary.feeExpense,5);assert.equal(d.summary.totalCashOut,235);assert.equal(d.summary.outstandingPrincipal,800)});
test('empty debt register is honest and unknown outstanding is not zero',()=>{const d=finance.debtSummary({loans:[],payments:[]},period.from,period.to);assert.equal(d.summary.activeCount,0);assert.equal(d.summary.outstandingPrincipal,null);assert.match(d.source,/не подключён/)});
test('complete empty accrual period is confirmed zero while absent sources remain unknown',()=>{const empty=finance.buildReport({stores:[store([])],state:{loans:[],payments:[]},...period});assert.equal(empty.accruals.value,0);assert.equal(empty.accruals.status,'complete');const absent=finance.buildReport({stores:[],state:{loans:[],payments:[]},...period});assert.equal(absent.accruals.value,null);assert.equal(absent.accruals.status,'missing');assert.throws(()=>finance.buildReport({stores:[],state:{loans:[],payments:[]},from:'2026-02-31',to:period.to}),/Начало периода/)});
test('register validates, rejects duplicates and persists without recalculating outstanding',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pult-finance-'));try{const api=finance.create({privateDir:dir,getStores:()=>[]});const loan=api.saveLoan({lender:'Банк',agreementNumber:'A-1',signedDate:'2026-09-01',originalPrincipal:1000,outstandingPrincipal:'',annualRatePercent:12,nextPaymentDate:'2026-10-01',sourceNote:'Договор A-1'});assert.equal(api.read().loans[0].outstandingPrincipal,null);assert.throws(()=>api.saveLoan({lender:'банк',agreementNumber:'a-1',signedDate:'2026-09-01',originalPrincipal:1000,sourceNote:'Копия'}),/уже есть/);api.savePayment({loanId:loan.id,date:'2026-09-20',principal:100,interest:10,fee:0,sourceNote:'Выписка'});assert.equal(api.read().loans[0].outstandingPrincipal,null);assert.throws(()=>api.savePayment({loanId:loan.id,date:'2026-09-20',principal:100,interest:10,fee:0,sourceNote:'Выписка'}),/уже есть/);api.savePayment({loanId:loan.id,date:'2026-09-20',principal:100,interest:10,fee:0,sourceNote:'Другое платёжное поручение'});assert.equal(api.read().payments.length,2);assert.throws(()=>api.savePayment({loanId:loan.id,date:'2026-09-21',principal:-1,interest:0,fee:0,sourceNote:'Ошибка'}),/Погашение тела/)}finally{fs.rmSync(dir,{recursive:true,force:true})}});
