const test=require('node:test'),assert=require('node:assert/strict');const {buildLedger}=require('../ledger.cjs'),{report}=require('../insights.cjs');
const m=(amount,currency='RUB')=>({amount:String(amount),currency}),period={from:'2026-08-18',to:'2026-09-16'};
function fixture(){
 const raw={period,completedAt:'2026-09-16T10:00:00Z',sections:{finance:{ok:true}},operations:[
  {date:'2026-09-15',total_amount:m(70),posting:{products:[{sku:10,commission:{sale_amount:m(100),commission:m(-20),bonus:m(30),coinvestment:m(5)},delivery:{total_accrued:m(-10),services:[{type_id:32,accrued:m(-10)}]}}]}},
  {date:'2026-09-15',total_amount:m(-5),non_item_fee:{type_id:41,accrued:m(-5)}},
  {date:'2026-09-15',total_amount:m(-1.11),item_fees:{fees:[{sku:10,fees:[{type_id:1,accrued:m(-1.11)}]}]}}
 ]};
 const types=[{id:32,name:'Logistic',description:'Логистика'},{id:41,name:'PayPerClick',description:'Клики'},{id:1,name:'Acquiring',description:'Эквайринг'}];return {raw,types};
}
function store(){const {raw,types}=fixture();return {id:'1',name:'Магазин',ledger:buildLedger(raw,types),extra:{orders:{period:{from:'2026-07-19',to:period.to},daily:[{date:'2026-09-15',revenue:150,units:3}],updatedAt:'2026-09-16T11:00:00Z'}},products:[{key:'1:1',sku:10,skus:[10,11],name:'Товар',market:'Ozon',quantity:2,cost:{status:'filled',currency:'RUB',unitCost:10}}]};}
test('financial decomposition reconciles exactly, without counting bonuses and delivery twice',()=>{const {raw,types}=fixture(),ledger=buildLedger(raw,types),v=ledger.daily[0].values;assert.equal(ledger.totalCents,6389);assert.equal(v.realized,10000);assert.equal(v.logistics,-1000);assert.equal(v.bonus,3000);assert.equal(v.partners,500);assert.equal(v.ads,-500);assert.equal(ledger.residualRecords,0);assert.equal(ledger.skuDaily[0].values.net,6889);assert.equal(v.net,6389);});
test('negative realizations, unclassified residuals and foreign currencies remain distinct',()=>{const {raw,types}=fixture();raw.operations.push({date:'2026-09-15',total_amount:m(-80),posting:{products:[{sku:10,commission:{sale_amount:m(-100),commission:m(20)}}]}});raw.operations.push({date:'2026-09-15',total_amount:m(2.22)});raw.operations.push({date:'2026-09-15',total_amount:m(900,'USD')});const d=buildLedger(raw,types);assert.equal(d.daily[0].values.reversal,10000);assert.equal(d.daily[0].values.unreconciled,222);assert.equal(d.foreignRecords,1);assert.equal(d.residualRecords,1);assert.equal(d.totalCents,-1389);});
test('comparison outside available financial range never becomes a fictitious zero',()=>{const r=report([store()],{from:'2026-08-18',to:'2026-09-16'});assert.equal(r.metrics.net.current,63.89);assert.equal(r.metrics.net.previous,null);assert.equal(r.metrics.orderedRevenue.current,150);assert.equal(r.metrics.orderedRevenue.previous,0);assert.equal(r.coverage.previousFinance,false);assert.equal(r.metrics.stockValue.current,20);assert.equal(r.metrics.stockValue.previous,null);});
test('previous complete empty period is zero; no-data and failed finance are unavailable',()=>{const s=store();let r=report([s],{from:'2026-09-09',to:'2026-09-15'});assert.equal(r.metrics.net.previous,0);assert.equal(r.metrics.orderedUnits.current,3);s.ledger.complete=false;r=report([s],{from:'2026-09-09',to:'2026-09-15'});assert.equal(r.metrics.net.current,null);assert.equal(r.metrics.orderedUnits.current,3);});
test('stock visibility never deletes historical finances and unknown stocks are not zero',()=>{const s=store();s.products[0].archived=true;s.products.push({sku:20,market:'Ozon',quantity:null,cost:{status:'filled',unitCost:200,currency:'RUB'}});const r=report([s],{from:'2026-09-09',to:'2026-09-15',hideInactive:true});assert.equal(r.metrics.net.current,63.89);assert.equal(r.metrics.stocks.current,null);assert.equal(r.coverage.unknownStocks,1);assert.equal(r.products[0].archived,true);assert.equal(r.products[0].key,'1:1');});
test('invalid dates, reversed dates and excessive ranges are rejected',()=>{for(const [from,to]of [['2026-02-30','2026-03-03'],['2026-09-10','2026-09-01'],['2025-01-01','2026-09-01']])assert.throws(()=>report([store()],{from,to}));});
test('fee groups preserve credits and unknown services instead of treating them as advertising',()=>{const {raw,types}=fixture();raw.operations.push({date:'2026-09-15',total_amount:m(25),non_item_fee:{type_id:999,accrued:m(25)}});const l=buildLedger(raw,types);assert.equal(l.daily[0].values.other,2500);assert.equal(l.fees.find(f=>f.typeId===999).group,'other');assert.equal(l.residualRecords,0);});
test('offsetting unknown accruals do not create a false clean reconciliation',()=>{const s=store(),{raw,types}=fixture();raw.operations.push({date:'2026-09-15',total_amount:m(10)},{date:'2026-09-15',total_amount:m(-10)});s.ledger=buildLedger(raw,types);const r=report([s],{from:'2026-09-09',to:'2026-09-15'});assert.equal(r.coverage.unreconciled,0);assert.equal(r.coverage.unreconciledRecords,2);});
