const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),{Readable}=require('stream'),{execFileSync}=require('child_process');
const finance=require('../finance-module.cjs');
function request(buffer,length=buffer.length){const req=Readable.from([buffer]);req.headers={'content-length':String(length)};return req}

test('contract text becomes a review draft with excerpts while monthly rate and PСК never become annual rate',()=>{
 const draft=finance.extractDraft([{page:1,text:'ДОГОВОР ЗАЙМА № Z-42 от 15.09.2026\nЗаймодавец: ООО «Синтетический банк»\nСумма займа: 1 250 000,50 рублей\nПСК 39,9 % годовых\nПроцентная ставка: 1,5 % в месяц\nСрок возврата: 15.09.2027\nПлатежи осуществляются ежемесячно согласно графику платежей.'}],'synthetic.docx','a'.repeat(64));
 assert.equal(draft.fields.lender.value,'ООО «Синтетический банк»');assert.equal(draft.fields.agreementNumber.value,'Z-42');assert.equal(draft.fields.signedDate.value,'2026-09-15');assert.equal(draft.fields.originalPrincipal.value,1250000.5);assert.equal(draft.fields.currency.value,'RUB');assert.equal(draft.fields.rate.value,1.5);assert.equal(draft.fields.ratePeriod.value,'monthly');assert.equal(draft.fields.annualRatePercent.value,null);assert.equal(draft.fields.maturityDate.value,'2027-09-15');assert.equal(draft.needsReview,true);assert.match(draft.fields.originalPrincipal.source.excerpt,/1 250 000/);
});

test('private upload validates type and magic, deduplicates hash and omits extracted source text from metadata',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pult-finance-upload-'));try{let calls=0;const api=finance.create({privateDir:dir,getStores:()=>[],now:()=> '2026-09-20T12:00:00Z',extractFile:async()=>{calls++;return {pages:[{page:null,text:'Договор займа № A-1 от 01.09.2026\nКредитор: Банк\nСумма займа: 1000 рублей\nПроцентная ставка: 12 % годовых\nСИНТЕТИЧЕСКИЙ НЕСВЯЗАННЫЙ ТЕКСТ'}],warnings:[]}}}),bytes=Buffer.from('PK\x03\x04synthetic');
  const first=await api.upload(request(bytes),{fileName:'contract.docx',contentType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});assert.equal(first.fields.annualRatePercent.value,12);assert.equal(api.drafts().length,1);
  const second=await api.upload(request(bytes),{fileName:'contract.docx',contentType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});assert.equal(second.id,first.id);assert.equal(second.duplicate,true);assert.equal(calls,1);
  const stored=fs.readFileSync(path.join(dir,'loan-contracts',first.id+'.json'),'utf8');assert.equal(stored.includes('СИНТЕТИЧЕСКИЙ НЕСВЯЗАННЫЙ ТЕКСТ'),false);assert.match(stored,/excerpt/);
  await assert.rejects(api.upload(request(Buffer.from('%PDF-test')),{fileName:'../contract.pdf',contentType:'application/pdf'}),/Поддерживаются/);await assert.rejects(api.upload(request(Buffer.from('%PDF-test')),{fileName:'contract.docx',contentType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),/Содержимое/);await assert.rejects(api.upload(request(Buffer.from('%PDF-test')),{fileName:'contract.pdf',contentType:'image/png'}),/Тип файла/);await assert.rejects(api.upload(request(Buffer.from('%PDF-test'),21*1024*1024),{fileName:'contract.pdf',contentType:'application/pdf'}),/20 МБ/);
 }finally{fs.rmSync(dir,{recursive:true,force:true})}
});

test('local DOCX extractor reads text without executing document relationships',t=>{
 const python=process.env.USERPROFILE&&path.join(process.env.USERPROFILE,'.cache','codex-runtimes','codex-primary-runtime','dependencies','python','python.exe');if(!python||!fs.existsSync(python)){t.skip('Bundled Python unavailable');return}const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pult-docx-'));try{const file=path.join(dir,'synthetic.docx'),code=`import sys,zipfile\np=sys.argv[1]\nct=b'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'\ndoc=b'<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>Dogovor zaima N TEST-1</w:t></w:r></w:p></w:body></w:document>'\nwith zipfile.ZipFile(p,'w') as z:z.writestr('[Content_Types].xml',ct);z.writestr('word/document.xml',doc)`;execFileSync(python,['-c',code,file]);const output=JSON.parse(execFileSync(python,[path.join(__dirname,'..','loan-contract-extract.py'),'docx',file],{encoding:'utf8'}));assert.equal(output.ok,true);assert.match(output.pages[0].text,/TEST-1/)}finally{fs.rmSync(dir,{recursive:true,force:true})}
});

test('built-in Russian Windows OCR creates review drafts from synthetic PNG and image-only PDF',t=>{
 if(process.platform!=='win32'){t.skip('Windows OCR is only available on Windows');return}const python=process.env.USERPROFILE&&path.join(process.env.USERPROFILE,'.cache','codex-runtimes','codex-primary-runtime','dependencies','python','python.exe');if(!python||!fs.existsSync(python)){t.skip('Bundled Python unavailable');return}const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pult-ocr-'));try{const png=path.join(dir,'synthetic.png'),pdf=path.join(dir,'synthetic.pdf'),code=`from PIL import Image,ImageDraw,ImageFont\nimport sys\npng,pdf=sys.argv[1:]\nim=Image.new('RGB',(1800,1000),'white');d=ImageDraw.Draw(im);f=ImageFont.truetype(r'C:\\Windows\\Fonts\\arial.ttf',54)\nlines=['ДОГОВОР ЗАЙМА № OCR-42 от 15.09.2026','Займодавец: ООО СИНТЕТИЧЕСКИЙ БАНК','Сумма займа: 1 250 000 рублей','Процентная ставка: 12 % годовых']\nfor i,line in enumerate(lines):d.text((70,70+i*150),line,font=f,fill='black')\nim.save(png);im.save(pdf,'PDF',resolution=150)`;execFileSync(python,['-c',code,png,pdf]);for(const [kind,file] of [['png',png],['pdf',pdf]]){const output=JSON.parse(execFileSync(python,[path.join(__dirname,'..','loan-contract-extract.py'),kind,file],{encoding:'utf8',timeout:15000}));if(output.warnings.some(x=>/недоступен/.test(x))){t.skip('Russian Windows OCR unavailable');return}assert.match(output.warnings.join(' '),/черновик/);assert.match(output.pages[0].text,/OCR-42/);assert.match(output.pages[0].text,/1 250 000/);const draft=finance.extractDraft(output.pages,'synthetic.'+kind,'b'.repeat(64),output.warnings);assert.equal(draft.fields.agreementNumber.value,'OCR-42');assert.equal(draft.fields.originalPrincipal.value,1250000);assert.equal(draft.fields.annualRatePercent.value,12);assert.equal(draft.needsReview,true)}}finally{fs.rmSync(dir,{recursive:true,force:true})}
});

test('image-only PDF OCR refuses documents beyond its page limit',t=>{
 const python=process.env.USERPROFILE&&path.join(process.env.USERPROFILE,'.cache','codex-runtimes','codex-primary-runtime','dependencies','python','python.exe');if(!python||!fs.existsSync(python)){t.skip('Bundled Python unavailable');return}const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pult-ocr-limit-'));try{const file=path.join(dir,'eleven-pages.pdf'),code=`from PIL import Image\nimport sys\nim=Image.new('RGB',(80,80),'white');im.save(sys.argv[1],'PDF',save_all=True,append_images=[im.copy() for _ in range(10)])`;execFileSync(python,['-c',code,file]);const result=require('child_process').spawnSync(python,[path.join(__dirname,'..','loan-contract-extract.py'),'pdf',file],{encoding:'utf8',timeout:10000});assert.notEqual(result.status,0);assert.match(JSON.parse(result.stdout).error,/больше 10 страниц/)}finally{fs.rmSync(dir,{recursive:true,force:true})}
});
