const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),os=require('os');
const createManager=require('../management.cjs'),{loadWbPrices}=require('../pricing.cjs'),{summarize}=require('../summary.cjs');
const at='2026-09-16T11:00:00.000Z';
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pult-management-test-')),file=path.join(dir,'state.json');t.after(()=>{const target=path.resolve(dir),parent=path.resolve(os.tmpdir());if(path.dirname(target)!==parent||!path.basename(target).startsWith('pult-management-test-'))throw Error('Unsafe cleanup target');fs.rmSync(target,{recursive:true,force:true})});const products=[{key:'1:10',storeId:'1',market:'Ozon',name:'Товар',offer_id:'X',storeName:'Магазин',salesStatus:'Продается',cost:{status:'filled',unitCost:50,currency:'RUB'},pricing:{price:100,minPrice:70,oldPrice:150,currency:'RUB',importedAt:at}},{key:'wb-1:20',storeId:'wb-1',market:'WB',name:'WB товар',offer_id:'W',storeName:'WB',pricing:{price:200,discount:20,currency:'RUB',importedAt:at}}];const args={file,catalog:()=>products,now:()=>at},manager=createManager(args);return {manager,products,args,file};}
function request(manager,keys=['1:10'],extra={}){const map=new Map(manager.products().map(p=>[p.key,p]));return {targets:keys.map(key=>({key,version:map.get(key).version})),mode:'percent',amount:10,rounding:0,...extra};}
function draft(manager,input){const p=manager.preview(input);return {...input,title:'Проверка цены',reason:'Новая закупочная цена',requestId:'test-request-12345678',previewHash:p.hash,acceptWarnings:true};}
test('percentage and cost markup preserve constraints, discounts and exact cents',t=>{const {manager}=setup(t);let p=manager.preview(request(manager));assert.equal(p.rows[0].after.price,110);assert.equal(p.valid,true);p=manager.preview(request(manager,['1:10'],{mode:'costplus',amount:100}));assert.equal(p.rows[0].after.price,100);assert.equal(p.valid,false);p=manager.preview(request(manager,['wb-1:20'],{mode:'set',amount:250,rounding:1,fields:{discount:30}}));assert.equal(p.rows[0].effective,175);assert.equal(p.rows[0].before.discount,20);assert.equal(p.rows[0].after.discount,30);assert.equal(p.warningCount,1);});
test('invalid numbers, min price, old price, currencies and stale snapshots block saving',t=>{const {manager,products}=setup(t);assert.throws(()=>manager.preview(request(manager,['1:10'],{amount:NaN})));for(const amount of [0,-3,65,151,Infinity]){if(Number.isFinite(amount))assert.equal(manager.preview(request(manager,['1:10'],{mode:'set',amount})).valid,false);}products[0].pricing.importedAt='2026-08-01T00:00:00Z';assert.equal(manager.preview(request(manager)).valid,false);products[0].pricing.importedAt=at;products[0].pricing.currency='USD';assert.equal(manager.preview(request(manager)).valid,false);});
test('unknown, duplicate, inactive and multi-size products cannot be changed',t=>{const {manager,products}=setup(t);assert.throws(()=>manager.preview({targets:[{key:'excluded:1'}],mode:'set',amount:120,rounding:0}));const r=request(manager);assert.throws(()=>manager.preview({...r,targets:[...r.targets,...r.targets]}));products[0].archived=true;assert.equal(manager.preview(request(manager)).valid,false);products[1].pricing.price=null;products[1].pricing.multiplePrices=true;assert.equal(manager.preview(request(manager,['wb-1:20'])).valid,false);});
test('drafts are idempotent, persistent and prevent overlapping product edits',t=>{const {manager,args,products}=setup(t);const input=draft(manager,request(manager)),b=manager.create(input);assert.equal(b.status,'draft');assert.equal(manager.create(input).id,b.id);assert.equal(manager.state().batches.length,1);assert.throws(()=>manager.create({...input,title:'Другой текст'}));assert.equal(manager.preview(request(manager)).valid,false);assert.equal(createManager(args).state().batches.length,1);assert.equal(products[0].pricing.price,100);assert.equal(manager.state().capabilities.priceWrite,false);});
test('changed product snapshot invalidates preview and review; no approval or publish transition',t=>{const {manager,products}=setup(t);const input=draft(manager,request(manager));products[0].pricing.price=105;assert.throws(()=>manager.create(input));const b=manager.create(draft(manager,request(manager)));assert.throws(()=>manager.transition({id:b.id,version:b.version,status:'approved'}));products[0].pricing.price=106;assert.throws(()=>manager.transition({id:b.id,version:b.version,status:'submitted'}));});
test('review queue handles versions, return reasons, cancellations and audit',t=>{const {manager}=setup(t);let b=manager.create(draft(manager,request(manager)));b=manager.transition({id:b.id,version:1,status:'submitted'});assert.throws(()=>manager.transition({id:b.id,version:1,status:'cancelled'}));assert.throws(()=>manager.transition({id:b.id,version:2,status:'returned',comment:''}));b=manager.transition({id:b.id,version:2,status:'returned',comment:'Проверить закупку'});assert.equal(b.returnReason,'Проверить закупку');b=manager.transition({id:b.id,version:3,status:'cancelled'});assert.equal(b.status,'cancelled');assert.equal(manager.state().events.length,4);assert.equal(manager.preview(request(manager)).valid,true);});
test('notes use conflict detection and survive restart without changing marketplace data',t=>{const {manager,args,products}=setup(t);const result=manager.note({key:'1:10',version:0,text:'Закупить 100 штук',flag:'purchase'});assert.equal(result.version,1);assert.throws(()=>manager.note({key:'1:10',version:0,text:'Устаревшая запись',flag:'normal'}));assert.equal(createManager(args).products()[0].note.text,'Закупить 100 штук');assert.equal(products[0].pricing.price,100);});
test('zero source prices allow explicit initial price but remain a visible warning',t=>{const {manager,products}=setup(t);products[1].pricing.price=0;const p=manager.preview(request(manager,['wb-1:20'],{mode:'set',amount:100,rounding:1}));assert.equal(p.valid,true);assert.equal(p.rows[0].changePercent,null);assert.ok(p.rows[0].warnings.some(s=>s.includes('нулевая')));});
test('WB pagination waits for empty page and retains zero and variable size prices',async()=>{let count=0;const pages=[[{nmID:1,currencyIsoCode4217:'RUB',discount:0,sizes:[{sizeID:11,price:0,discountedPrice:0}]},{nmID:2,currencyIsoCode4217:'RUB',discount:20,sizes:[{sizeID:21,price:100},{sizeID:22,price:200}]}],[]];const result=await loadWbPrices('not-a-real-key',async(url,options)=>{assert.ok(url.startsWith('https://discounts-prices-api.wildberries.ru/'));assert.equal(options.method,undefined);assert.ok(url.endsWith('offset='+count*1000));return {ok:true,status:200,json:async()=>({data:{listGoods:pages[count++]}})}});assert.equal(count,2);assert.equal(result.items[0].pricing.price,0);assert.equal(result.items[1].pricing.price,null);assert.equal(result.items[1].pricing.multiplePrices,true);});
test('dashboard overlays refreshed price snapshot without changing finances or dropping zero',()=>{const d=summarize({market:'WB',financeAmountKnown:false,products:[{product_id:1,price:999}],operations:[]},null,{importedAt:at,items:[{product_id:'1',pricing:{price:0,discount:0,currency:'RUB'}}]});assert.equal(d.products[0].price,0);assert.equal(d.products[0].pricing.importedAt,at);assert.equal(d.financeAmountKnown,false);});
