'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {DatabaseSync}=require('node:sqlite'),{gunzipSync}=require('node:zlib');
const {create,allowed}=require('../market-history-archive.cjs');
function fixture(t,options={}){const parent=fs.realpathSync(os.tmpdir()),dir=fs.mkdtempSync(path.join(parent,'pult-archive-'));const archive=create({privateDir:dir,...options});t.after(()=>{archive.close();assert.equal(path.dirname(dir),parent);assert.ok(path.basename(dir).startsWith('pult-archive-'));fs.rmSync(dir,{recursive:true,force:true})});return {dir,archive,write:(name,value)=>fs.writeFileSync(path.join(dir,name),JSON.stringify(value))}}
test('only approved business snapshots are archived; credentials and paths are excluded',()=>{for(const name of ['data-1.json','insights-1.json','wb-orders-wb-2.json','charity-plan.json'])assert.equal(allowed(name),true);for(const name of ['stores.json','truestats.json','../data-1.json','cookies.json','data-1.json.tmp','server.log','buyer-order-segments-2026-09-20_2026-09-20.partial.json'])assert.equal(allowed(name),false)});
test('snapshots survive updates, deduplicate unchanged content and round-trip from compressed archives',async t=>{let time=Date.parse('2024-01-01Z');const f=fixture(t,{now:()=>time});f.write('data-1.json',{items:[1]});f.write('stores.json',{key:'DO-NOT-ARCHIVE'});await f.archive.scan();await f.archive.scan();assert.equal(f.archive.status().versions,1);time=Date.parse('2026-09-20Z');f.write('data-1.json',{items:[1,2]});await f.archive.scan();assert.equal(f.archive.status().versions,2);assert.equal(f.archive.status().retentionDays,null);const db=new DatabaseSync(path.join(f.dir,'history/archive.sqlite'),{readOnly:true}),rows=db.prepare('SELECT * FROM versions ORDER BY captured_at').all();db.close();assert.deepEqual(rows.map(r=>JSON.parse(gunzipSync(fs.readFileSync(path.join(f.dir,'history',r.object_path))))),[{items:[1]},{items:[1,2]}]);assert.equal(rows.some(r=>r.source_file==='stores.json'),false)});
test('failed fact imports retain the raw archive and retry old versions after the source changes',async t=>{let failed=true;const imported=[];const f=fixture(t,{history:{ingest:value=>{if(failed)throw Error('fixture');imported.push(value.data)}}});f.write('insights-1.json',{version:1});assert.equal((await f.archive.scan()).failed,1);assert.equal(f.archive.status().pendingFacts,1);f.write('insights-1.json',{version:2});failed=false;assert.equal((await f.archive.scan()).failed,0);assert.equal(f.archive.status().versions,2);assert.equal(f.archive.status().pendingFacts,0);assert.deepEqual(imported,[{version:1},{version:2}])});
test('parallel scans share one archive pass',async t=>{const f=fixture(t);f.write('data-1.json',{rows:Array.from({length:1000},(_,i)=>i)});const a=f.archive.scan(),b=f.archive.scan();assert.equal(a,b);await a;assert.equal(f.archive.status().versions,1)});
