'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createCostsPricesAcquisition}=require('../storage/acquisition/postgres-costs-prices.cjs');
const C='11111111-1111-4111-8111-111111111111';
test('Ozon costs use database credentials without decrypting in Node',async()=>{
 const ozonApi=Object.assign(async()=>{}, {usesDatabaseCredentials:true});let writes=0;
 const api=createCostsPricesAcquisition({stateStore:{},storesRepository:{protectedStore:async()=>({key:'opaque'})},decrypt:async()=>{throw Error('Node key access forbidden')},ozonApi,fetchFn:async()=>{throw Error('Node HTTP forbidden')},repositoryFactory:()=>({readCommand:async()=>null,compareAndSet:async()=>{writes++;return{revision:'1'}}}),loadCosts:async(store,key,transport)=>{assert.equal(key,'postgresql-managed');assert.equal(transport,ozonApi);return{importedAt:'2026-09-22T00:00:00Z',items:[]}}});
 await api.refresh({storeId:'1',expectedRevision:'0',commandId:C});assert.equal(writes,1);
});
function fixture({market='Ozon'}={}){let collected=0,written=0,journal=null;const repositoryFactory=()=>({readCommand:async()=>journal,compareAndSet:async (value,o)=>{written++;journal={before:{revision:o.expectedRevision},after:{revision:'1',value}};return{revision:'1',replayed:false}}});return{get counts(){return{collected,written}},api:createCostsPricesAcquisition({stateStore:{},repositoryFactory,storesRepository:{protectedStore:async()=>({name:'S',market,key:'opaque'})},decrypt:async()=> 'plain',ozonApi:async()=>{},fetchFn:async()=>{},loadCosts:async()=>{collected++;return{source:'x',importedAt:'2026-09-22T00:00:00Z',items:[{product_id:'1'}]}},loadWbPrices:async()=>{collected++;return{source:'wb',importedAt:'2026-09-22T00:00:00Z',items:[]}}})};}
test('costs adapter writes exact classified document and durable replay avoids external recollection',async()=>{const f=fixture();assert.deepEqual(await f.api.refresh({storeId:'1',expectedRevision:'0',commandId:C}),{revision:'1',replayed:false,sourcePath:'costs-1.json',count:1});assert.equal((await f.api.refresh({storeId:'1',expectedRevision:'0',commandId:C})).replayed,true);await assert.rejects(f.api.refresh({storeId:'1',expectedRevision:'1',commandId:C}),{code:'COMMAND_ID_REUSED'});assert.deepEqual(f.counts,{collected:1,written:1});});
test('WB prices use prices source path and failures are sanitized without writes',async()=>{const f=fixture({market:'WB'});assert.equal((await f.api.refresh({storeId:'wb-2',expectedRevision:'0',commandId:C})).sourcePath,'prices-wb-2.json');const broken=createCostsPricesAcquisition({stateStore:{},repositoryFactory:()=>({readCommand:async()=>null}),storesRepository:{protectedStore:async()=>({key:'cipher'})},decrypt:async()=>{throw Error('cipher leaked')},ozonApi:async()=>{},fetchFn:async()=>{}});await assert.rejects(broken.refresh({storeId:'1',expectedRevision:'0',commandId:C}),e=>e.code==='ACQUISITION_FAILED'&&!e.message.includes('cipher'));});
