'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const createWorkspace = require('../storage/domains/postgres-charity-workspace.cjs');
const { createStateStore } = require('../storage/postgres-state.cjs');
const key = path => 'file/' + crypto.createHash('sha256').update(path).digest('hex'), hash = bytes => crypto.createHash('sha256').update(bytes).digest();
const command = value => ({ commandId: `${value.repeat(8)}-${value.repeat(4)}-4${value.repeat(3)}-8${value.repeat(3)}-${value.repeat(12)}`, timestamp: `2026-09-22T12:00:0${parseInt(value, 16) % 10}Z` });
function memory({ unknown = null } = {}) { const records = new Map(), commands = new Map(); return { records, async read(k) { return records.get(k) || null; }, async readCommand(k, id) { const row = commands.get(id); if (row && row.key !== k) throw Object.assign(Error(), { code: 'COMMAND_ID_REUSED' }); return row || null; }, async write(k, content, options) { const prior = commands.get(options.commandId); if (prior) { if (prior.key !== k || !prior.after.content.equals(content)) throw Object.assign(Error(), { code: 'COMMAND_ID_REUSED' }); return { revision: prior.after.revision, replayed: true }; } const current = records.get(k); if ((current?.revision || '0') !== options.expectedRevision) throw Object.assign(Error(), { code: 'REVISION_CONFLICT' }); const before = current || { revision: '0', absent: true, deleted: null, content: null, sha256: null, mediaType: null }, after = { revision: String(BigInt(options.expectedRevision) + 1n), content: Buffer.from(content), sha256: hash(content), mediaType: options.mediaType, deleted: false }; records.set(k, after); commands.set(options.commandId, { key: k, before, after }); if (unknown === options.commandId) { unknown = null; throw Object.assign(Error('canary'), { code: 'OUTCOME_UNKNOWN' }); } return { revision: after.revision }; }, async remove() { throw Error('unused'); } }; }
const record = (extra = {}) => ({ date: '2026-09-10', programOrRecipient: 'Тестовый фонд', amount: '10.10', currency: 'RUB', status: 'completed', sourceDocument: { label: 'Документ' }, externalId: '1', ...extra });
const batch = (records, extra = {}) => ({ version: 0, source: 'Синтетическая выгрузка', asOf: '2026-09-20', coverage: { from: '2026-09-01', to: '2026-09-20', complete: true }, records, ...extra });
function put(state, path, value) { const content = Buffer.from(JSON.stringify(value)); state.records.set(key(path), { revision: '1', content, sha256: hash(content), mediaType: 'application/json', deleted: false }); }
test('exact decimals, filters, coverage and separate plan preserve legacy semantics', async () => {
  const state = memory(); put(state, 'charity-plan.json', { schema: 1, observedAt: '2026-09-20T12:00:00Z', storeId: 'SK', source: { label: 'План', url: 'https://example.org/plan' }, summary: { currency: 'RUB', confirmedTransferCount: 1, confirmedTransferredAmount: '10.00', monthlyAmountPerFund: '10.00', activeRegularCount: 1, activeRegularMonthly: '10.00', orphanSupportCount: 1, otherCount: 0, plannedActivationCount: 0, plannedActivationMonthly: '0.00' }, limitations: [], funds: [{ id: 'f', name: 'Фонд', category: 'Сиротство', status: 'active_regular', monthlyAmount: '10.00', website: 'https://example.org/', logo: '/charity-logos/f.svg', logoSource: 'https://example.org/f.svg' }] });
  const service = createWorkspace({ stateStore: state }), result = await service.importRecords(batch([record({ externalId: '1', amount: '0.10', storeId: 's' }), record({ externalId: '2', amount: '0.20', status: 'executed', storeId: 's' }), record({ externalId: '3', amount: '9.99', status: 'pending' })]), command('1'));
  assert.equal(result.totalsByCurrency[0].confirmed, '0.30'); assert.equal(result.plan.status, 'available'); const filtered = await service.read({ storeId: 's', status: 'completed' }); assert.equal(filtered.records.length, 1); assert.equal(filtered.coverage.status, 'complete'); assert.equal(filtered.capabilities.payments, false);
});
test('CAS, exact command replay and unknown outcome never double import', async () => {
  const op = command('2'), state = memory({ unknown: op.commandId }), service = createWorkspace({ stateStore: state }), input = batch([record()]); await assert.rejects(service.importRecords(input, op), error => error.code === 'OUTCOME_UNKNOWN'); await service.importRecords(batch([record({ externalId: '2' })], { version: 1 }), command('3')); const replay = await service.importRecords(input, op); assert.equal(replay.importResult.inserted, 1); assert.equal(replay.version, 1); assert.equal((await service.read()).records.length, 2); const stored = JSON.parse([...state.records.values()].find(value => value.content.toString().includes('commandResults')).content); assert.equal(stored.commandResults.length, 1); assert.equal(stored.commandResults[0].commandId, command('3').commandId); await assert.rejects(service.importRecords(batch([record({ amount: '20.20' })]), op), error => error.code === 'COMMAND_ID_REUSED'); await assert.rejects(service.importRecords(batch([], { version: 0 }), command('4')), error => error.status === 409);
});
test('invalid data and corrupt SQL fail closed without payments or external effects', async () => {
  const state = memory(), service = createWorkspace({ stateStore: state }); await assert.rejects(service.importRecords(batch([record({ amount: '0.001' })]), command('4'))); const content = Buffer.from('{broken'); state.records.set(key('charity.json'), { revision: '1', content, sha256: hash(content), mediaType: 'application/json', deleted: false }); await assert.rejects(service.read(), error => error.status === 503);
});
const integrationUrl = process.env.PULT_TEST_DATABASE_URL;
test('PostgreSQL charity integration persists mapped state and journal replay', { skip: !integrationUrl }, async t => {
  assert.match(decodeURIComponent(new URL(integrationUrl).pathname.slice(1)), /^pult_test_/u); const { Pool } = require('pg'), pool = new Pool({ connectionString: integrationUrl }), schema = `charity_${crypto.randomBytes(8).toString('hex')}`; let owned = false; t.after(async () => { if (owned) await pool.query(`DROP SCHEMA "${schema}" CASCADE`); await pool.end(); }); await pool.query(require('../storage/postgres-schema.cjs').replace(/\bpult\b/gu, schema)); owned = true; await pool.query(require('../storage/postgres-document-schema.cjs').replace(/\bpult\b/gu, schema)); const service = createWorkspace({ stateStore: createStateStore({ pool, schema }) }), op = command('5'), input = batch([record()]), first = await service.importRecords(input, op), replay = await service.importRecords(input, op); assert.deepEqual(replay, first); const rows = await pool.query(`SELECT source_path FROM "${schema}".source_files ORDER BY source_path`); assert.deepEqual(rows.rows, [{ source_path: 'charity.json' }]);
});
