'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { Readable } = require('node:stream');
const createRoutes = require('../storage/domains/postgres-store-routes.cjs');
function response() { return { status: null, body: null, writeHead(status) { this.status = status; }, end(value) { this.body = JSON.parse(value); } }; }
function request(body, headers = {}) { return Object.assign(Readable.from([JSON.stringify(body)]), { method: 'POST', headers: { 'content-type': 'application/json', ...headers } }); }
const command = { commandId: '11111111-1111-4111-8111-111111111111', timestamp: '2026-09-22T10:00:00.000Z', expectedRevision: '0' };
test('routes await fresh authorization and forward stable command envelope', async () => { let allowed = false, received; const commands = { connectOzon: async (input, op) => { received = { input, op }; return { storeId: '1', revision: '1' }; }, connectWb() {}, disconnect() {}, sync() {} }, routes = createRoutes({ commands, authorize: async () => allowed }); let res = response(); await routes.handle(request({ name: 'SK', clientId: '1', key: 'secret', ...command }), res, new URL('http://local/api/connect')); assert.equal(res.status, 403); allowed = true; res = response(); await routes.handle(request({ name: 'SK', clientId: '1', key: 'secret', ...command }), res, new URL('http://local/api/connect')); assert.equal(res.status, 200); assert.deepEqual(received.op, command); assert.deepEqual(received.input, { name: 'SK', clientId: '1', key: 'secret' }); });
test('primitive bodies, extra fields and conflicting headers are safe 400 responses', async () => { const calls = [], commands = Object.fromEntries(['connectOzon', 'connectWb', 'disconnect', 'sync'].map(name => [name, async () => calls.push(name)])), routes = createRoutes({ commands, authorize: async () => true }); let res = response(); await routes.handle(request(null), res, new URL('http://local/api/connect')); assert.equal(res.status, 400); res = response(); await routes.handle(request({ id: '1', ignored: true, ...command }), res, new URL('http://local/api/sync')); assert.equal(res.status, 400); res = response(); await routes.handle(request({ id: '1', ...command }, { 'x-pult-command-id': '22222222-2222-4222-8222-222222222222' }), res, new URL('http://local/api/sync')); assert.equal(res.status, 400); assert.deepEqual(calls, []); });
test('database canaries are sanitized and unknown outcome gives same-command guidance', async () => { const base = { connectOzon() {}, connectWb() {}, disconnect() {}, async sync() { throw Error('private-canary'); } }, routes = createRoutes({ commands: base, authorize: async () => true }); let res = response(); await routes.handle(request({ id: '1', ...command }), res, new URL('http://local/api/sync')); assert.equal(res.status, 503); assert.equal(JSON.stringify(res.body).includes('canary'), false); base.sync = async () => { throw Object.assign(Error(), { code: 'OUTCOME_UNKNOWN' }); }; res = response(); await routes.handle(request({ id: '1', ...command }), res, new URL('http://local/api/sync')); assert.equal(res.status, 503); assert.match(res.body.error, /теми же commandId/u); });
