'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const create=require('../storage/domains/postgres-truestats.cjs');
const {createStateStore}=require('../storage/postgres-state.cjs');
const TOKEN='synthetic-secret-token-123456';
function repo(initial=null){let revision=initial?1:0,row=initial?structuredClone(initial):null;const commands=new Map();return {async read(){return row&&{revision:String(revision),deleted:false,value:structuredClone(row)}},async readCommand(id){return commands.get(id)||null},async compareAndSet(value,{expectedRevision,commandId}){if(commands.has(commandId))return {revision:commands.get(commandId).after.revision,replayed:true};if(expectedRevision!==String(revision)){const e=new Error('conflict');e.code='REVISION_CONFLICT';throw e}const before=row?{revision:String(revision),deleted:false,value:structuredClone(row)}:{revision:'0',absent:true,deleted:false,value:null};revision++;row=structuredClone(value);commands.set(commandId,{before,after:{revision:String(revision),deleted:false,value:structuredClone(row)}});return {revision:String(revision)}}};}
function fixture(){const config=repo(),links=repo(),runtime=repo(),calls=[],deferred=[];let time=Date.parse('2026-09-16T10:00:00Z');const accounts=[{id:17,name:'Shop',accountType:1},{id:18,name:'WB',accountType:0}],catalog=[{id:'profit',header:'Чистая прибыль',meta:{suffix:'₽'}},{id:'tax_value',header:'Налог',meta:{suffix:'₽'}}];const transport=async(url,options)=>{calls.push({url,options});const path=new URL(url).pathname;let value;if(path==='/reporting/facets')value={accounts};else if(path==='/reporting/aggregated-view/day')value={financialMod:false,accountIdsFilter:JSON.parse(options.body).filters.accounts,result:[{date:'2026-09-15',profit:10,tax_value:0}],summary:{profit:10,tax_value:0}};else if(path==='/reporting/main/stats')value={financialMod:false,stats:{profit:10,tax_value:0}};else if(path==='/product-metrics')value=catalog;else if(path==='/v1/data-readiness')value={items:[{accountId:17,dataType:'ozon_report',status:'complete',checkedDate:'2026-09-15',lastDataDate:'2026-09-15'}]};else throw Error('unexpected');return {ok:true,status:200,headers:{get(){return null}},async text(){return JSON.stringify(value)}}};const make=()=>create({configRepository:config,linksRepository:links,runtimeRepository:runtime,protect:async(value,decrypt)=>decrypt?TOKEN:'ciphertext:'+value.length,transport,now:()=>time,getProducts:async()=>[],defer:work=>deferred.push(work)});return {make,config,links,runtime,calls,tick(ms){time+=ms},async runBackground(){while(deferred.length)await deferred.shift()();}};}
test('connect persists only ciphertext and exact command replay does not recollect',async()=>{const f=fixture(),service=f.make(),meta={commandId:'11111111-1111-4111-8111-111111111111',timestamp:'2026-09-16T10:00:00.000Z'};assert.equal((await service.connect(TOKEN,meta)).connected,true);const count=f.calls.length;assert.equal((await service.connect(TOKEN,meta)).connected,true);assert.equal(f.calls.length,count);assert.ok(!JSON.stringify(await f.config.read()).includes(TOKEN));await assert.rejects(service.connect(TOKEN+'x',meta),e=>e.code==='command_conflict'&&!e.message.includes(TOKEN));});
test('link is fresh SQL state and replay returns original result after later write',async()=>{const f=fixture(),a=f.make(),b=f.make();const one=await a.saveLink({storeId:'wb-1',accountId:18},{commandId:'22222222-2222-4222-8222-222222222222',timestamp:'2026-09-16T10:00:00.000Z'});await b.saveLink({storeId:'wb-2',accountId:19},{commandId:'33333333-3333-4333-8333-333333333333',timestamp:'2026-09-16T10:01:00.000Z'});assert.equal((await a.readLinks()).storeId,'wb-2');assert.deepEqual(await a.saveLink({storeId:'wb-1',accountId:18},{commandId:'22222222-2222-4222-8222-222222222222',timestamp:'2026-09-16T10:00:00.000Z'}),one);});
test('verified compare cache survives reopen, is scoped and expires without stale fallback',async()=>{const f=fixture(),service=f.make();await service.connect(TOKEN,{commandId:'55555555-5555-4555-8555-555555555555',timestamp:'2026-09-16T10:00:00.000Z'});const input={period:{from:'2026-09-15',to:'2026-09-15'},stores:[{id:'local',name:'Shop'}]};const first=await service.compare(input);assert.equal(first.status,'ready');const count=f.calls.length,cached=await f.make().compare(input);assert.equal(cached.cached,true);assert.equal(f.calls.length,count);await f.make().compare({...input,stores:[{id:'other',name:'Shop'}]});assert.ok(f.calls.length>count);f.tick(30*60*1000);let attempted=0;const offline=create({configRepository:f.config,linksRepository:f.links,runtimeRepository:f.runtime,protect:async()=>TOKEN,transport:async()=>{attempted++;throw Object.assign(Error('canary secret'),{public:true,code:'leak'})},now:()=>Date.parse('2026-09-16T10:30:00Z')});const failed=await offline.compare(input);assert.equal(failed.status,'unavailable');assert.equal(attempted,1);assert.ok(!JSON.stringify(failed).includes('canary'));});
test('cache-only compare returns pending without external work and never exposes expired finance',async()=>{const f=fixture(),service=f.make();await service.connect(TOKEN,{commandId:'77777777-7777-4777-8777-777777777777',timestamp:'2026-09-16T10:00:00.000Z'});const input={period:{from:'2026-09-15',to:'2026-09-15'},stores:[{id:'local',name:'Shop'}]},baseline=f.calls.length,cold=await service.readCompare(input);assert.equal(cold.status,'pending');assert.equal(cold.metrics.profit,null);assert.equal(f.calls.length,baseline);assert.equal(service.refreshCompare(input),true);assert.equal(f.calls.length,baseline);await f.runBackground();assert.ok(f.calls.length>baseline);const fresh=await service.readCompare(input);assert.equal(fresh.status,'ready');assert.equal(fresh.metrics.profit,10);f.tick(30*60*1000);const beforeExpired=f.calls.length,expired=await service.readCompare(input);assert.equal(expired.status,'pending');assert.equal(expired.metrics.profit,null);assert.equal(expired.fetchedAt,null);assert.equal(f.calls.length,beforeExpired);});
test('background refresh stays deduplicated while the external work is running',async()=>{const f=fixture();await f.make().connect(TOKEN,{commandId:'aaaaaaa1-aaaa-4aaa-8aaa-aaaaaaaaaaaa',timestamp:'2026-09-16T10:00:00.000Z'});let scheduled,release,reached;const gate=new Promise(resolve=>{release=resolve}),started=new Promise(resolve=>{reached=resolve});const service=create({configRepository:f.config,linksRepository:f.links,runtimeRepository:f.runtime,protect:async(_value,decrypt)=>{if(decrypt){reached();await gate;return TOKEN}return 'ciphertext'},transport:async()=>{throw Error('offline')},now:()=>Date.parse('2026-09-16T10:00:00Z'),defer:work=>{scheduled=work}});const input={period:{from:'2026-09-15',to:'2026-09-15'},stores:[{id:'local',name:'Shop'}]};assert.equal(service.refreshCompare(input),true);const work=scheduled();await started;assert.equal(service.refreshCompare(input),false);release();await work;assert.equal(service.refreshCompare(input),true);});
test('daily keeps zero distinct from unknown and reads fresh protected config',async()=>{const f=fixture(),service=f.make();await service.connect(TOKEN,{commandId:'66666666-6666-4666-8666-666666666666',timestamp:'2026-09-16T10:00:00.000Z'});const result=await service.daily({period:{from:'2026-09-15',to:'2026-09-15'},store:{id:'x',name:'Shop'},market:'Ozon'});assert.equal(result.status,'ready');assert.equal(result.points[0].profit,10);assert.equal(result.points[0].tax,0);assert.equal(result.scopeVerified,true);});
test('cache-only daily and WB conversion return null-valued pending shapes before background refresh',async()=>{const f=fixture(),service=f.make();await service.connect(TOKEN,{commandId:'88888888-8888-4888-8888-888888888888',timestamp:'2026-09-16T10:00:00.000Z'});await service.saveLink({storeId:'wb-1',accountId:18},{commandId:'99999999-9999-4999-8999-999999999999',timestamp:'2026-09-16T10:01:00.000Z'});const baseline=f.calls.length,daily=await service.readDaily({period:{from:'2026-09-15',to:'2026-09-15'},store:{id:'x',name:'Shop'},market:'Ozon'}),conversion=await service.readWbConversion('wb-1',{day:'2026-09-16'});assert.equal(daily.status,'pending');assert.equal(daily.totalProfit,null);assert.equal(daily.points[0].profit,null);assert.equal(daily.points[0].status,'pending');assert.equal(conversion.status,'pending');assert.deepEqual(conversion.rows,[]);assert.equal(f.calls.length,baseline);});
test('transport is pinned to allowlisted routes and rejects redirects',async()=>{const f=fixture(),service=f.make();await service.connect(TOKEN,{commandId:'66666666-6666-4666-8666-666666666666',timestamp:'2026-09-16T10:00:00.000Z'});assert.ok(f.calls.every(call=>call.url.startsWith('https://api.truestats.ru/')));assert.ok(f.calls.every(call=>call.options.redirect==='error'));assert.ok(f.calls.every(call=>call.options.headers['X-Api-Token']===TOKEN));});
test('unknown config commit is redacted and the identical retry uses its journal without recollecting',async()=>{const f=fixture(),original=f.config.compareAndSet.bind(f.config);let first=true;f.config.compareAndSet=async(...args)=>{const result=await original(...args);if(first){first=false;throw Error('raw database canary')}return result};const service=f.make(),meta={commandId:'44444444-4444-4444-8444-444444444444',timestamp:'2026-09-16T10:00:00.000Z'};await assert.rejects(service.connect(TOKEN,meta),error=>error.code==='outcome_unknown'&&!error.message.includes('canary'));const calls=f.calls.length,result=await service.connect(TOKEN,meta);assert.equal(result.connected,true);assert.equal(f.calls.length,calls);});
test('legacy imported config/link validate and replay rejects a changed timestamp',async()=>{assert.equal(create.validateConfig({version:1,encryptedKey:'legacy-cipher',connectedAt:'2026-09-16T09:00:00.000Z'}),true);assert.equal(create.validateLink({storeId:'wb-1',accountId:17}),true);const f=fixture(),service=f.make(),meta={commandId:'77777777-7777-4777-8777-777777777777',timestamp:'2026-09-16T10:00:00.000Z'};await service.connect(TOKEN,meta);await assert.rejects(service.connect(TOKEN,{...meta,timestamp:'2026-09-16T10:01:00.000Z'}),error=>error.code==='command_conflict');});
test('RNP rejects incomplete pagination and a link race, and dependency canaries stay redacted',async()=>{const config=repo({version:1,encryptedKey:'legacy-cipher',connectedAt:'2026-09-16T09:00:00.000Z'}),links=repo({storeId:'wb-1',accountId:42}),runtime=repo(),item={id:'1010',articleId:1010,accountId:42,marketplaceId:0,nmId:'10',vendorCode:'offer-10',name:'P',totals:{transitions:10,added_to_cart:2,order_count:1,added_to_cart_percent:20,added_to_order_percent:50},prevTotals:{transitions:10,added_to_cart:2,order_count:1,added_to_cart_percent:20,added_to_order_percent:50}};let mode='incomplete';const transport=async url=>{const route=new URL(url).pathname,value=route.endsWith('filter-values')?{accounts:[{id:42}],articles:[{id:1010,articleId:1010,accountId:42,nmId:10}],dates:{minDate:'2026-09-04',maxDate:'2026-09-18'}}:{items:[item],pagination:{page:1,limit:100,total:mode==='incomplete'?2:1},isCalculationInProgress:false};if(route.endsWith('/grouped')&&mode==='race')await links.compareAndSet({storeId:'wb-1',accountId:99},{expectedRevision:'1',commandId:'race'});return {ok:true,status:200,headers:{get(){return null}},async text(){return JSON.stringify(value)}}};const make=getProducts=>create({configRepository:config,linksRepository:links,runtimeRepository:runtime,protect:async()=>TOKEN,transport,now:()=>Date.parse('2026-09-18T12:00:00Z'),getProducts});let result=await make(async()=>[{product_id:10,sku:10,name:'P',offer_id:'offer-10'}]).getWbConversion('wb-1',{day:'2026-09-18'});assert.equal(result.code,'pagination');mode='race';result=await make(async()=>[{product_id:10,sku:10,name:'P',offer_id:'offer-10'}]).getWbConversion('wb-1',{day:'2026-09-18'});assert.equal(result.code,'changed');assert.ok(!JSON.stringify(result).includes(TOKEN));});

const integrationUrl=process.env.PULT_TEST_DATABASE_URL;
test('PostgreSQL TrueStats stores ciphertext and scoped cache, reopens, rebinds and replays', {skip:!integrationUrl}, async t=>{
 assert.match(decodeURIComponent(new URL(integrationUrl).pathname.slice(1)),/^pult_test_/u);
 const {Pool}=require('pg'),pool=new Pool({connectionString:integrationUrl}),schema=`truestats_${crypto.randomBytes(8).toString('hex')}`;let owned=false;
 t.after(async()=>{if(owned)await pool.query(`DROP SCHEMA "${schema}" CASCADE`);await pool.end();});
 await pool.query(require('../storage/postgres-schema.cjs').replace(/\bpult\b/gu,schema));owned=true;
 await pool.query(require('../storage/postgres-document-schema.cjs').replace(/\bpult\b/gu,schema));
 const stateStore=createStateStore({pool,schema}),calls=[];let activeToken=TOKEN;
 const transport=async(url,options)=>{calls.push(url);const route=new URL(url).pathname,body=options.body?JSON.parse(options.body):null;const value=route==='/reporting/facets'?{accounts:[{id:17,name:'Shop',accountType:1}]}:route==='/reporting/aggregated-view/day'?{financialMod:false,accountIdsFilter:body.filters.accounts,result:[{date:'2026-09-15',profit:10}],summary:{profit:10}}:route==='/reporting/main/stats'?{financialMod:false,stats:{profit:10}}:route==='/product-metrics'?[{id:'profit',header:'Чистая прибыль',meta:{suffix:'₽'}}]:route==='/v1/data-readiness'?{items:[{accountId:17,dataType:'ozon_report',status:'complete',checkedDate:'2026-09-15',lastDataDate:'2026-09-15'}]}:null;return {ok:true,status:200,headers:{get(){return null}},async text(){return JSON.stringify(value)}}};
 const protect=async(value,decrypt)=>decrypt?Buffer.from(value.slice(7),'base64').toString('utf8'):'cipher:'+Buffer.from(value).toString('base64'),make=()=>create({stateStore,protect,transport,now:()=>Date.parse('2026-09-16T10:00:00Z')});
 async function importLegacy(sourcePath,value){const content=Buffer.from(JSON.stringify(value)),digest=crypto.createHash('sha256').update(content).digest(),key='file/'+crypto.createHash('sha256').update(sourcePath).digest('hex');await pool.query(`INSERT INTO "${schema}".document_states(logical_key,media_type,content,sha256,revision,deleted) VALUES($1,'application/json',$2,$3,1,false)`,[key,content,digest]);await pool.query(`INSERT INTO "${schema}".source_files(source_path,logical_key,domain,media_type,source_bytes,source_sha256,baseline_present) VALUES($1,$2,$3,'application/json',$4,$5,true)`,[sourcePath,key,sourcePath==='truestats.json'?'protected-connections':'business-state',content.length,digest])}
 await importLegacy('truestats.json',{version:1,encryptedKey:await protect(activeToken,false),connectedAt:'2026-09-16T09:00:00.000Z'});await importLegacy('truestats-wb-link.json',{storeId:'wb-legacy',accountId:17});
 const connectId=crypto.randomUUID(),service=make();assert.equal((await service.status()).connected,true);assert.equal((await service.readLinks()).storeId,'wb-legacy');
 const input={period:{from:'2026-09-15',to:'2026-09-15'},stores:[{id:'local',name:'Shop'}]};assert.equal((await service.compare(input)).status,'ready');const before=calls.length;
 assert.equal((await make().compare(input)).cached,true);assert.equal(calls.length,before);
 await service.saveLink({storeId:'wb-1',accountId:17},{commandId:crypto.randomUUID(),timestamp:'2026-09-16T10:01:00.000Z'});const runtime=await create.repositories(stateStore).runtime.read();assert.deepEqual(runtime.value.entries,{});
 activeToken=TOKEN+'-replacement';const replaceId=crypto.randomUUID();await service.connect(activeToken,{commandId:replaceId,timestamp:'2026-09-16T10:02:00.000Z'});const afterConnect=calls.length;await service.connect(activeToken,{commandId:replaceId,timestamp:'2026-09-16T10:02:00.000Z'});assert.equal(calls.length,afterConnect);await assert.rejects(service.connect(activeToken,{commandId:replaceId,timestamp:'2026-09-16T10:03:00.000Z'}),error=>error.code==='command_conflict');
 const bytes=(await pool.query(`SELECT content FROM "${schema}".document_states`)).rows.map(row=>row.content.toString('utf8')).join('\n');assert.ok(!bytes.includes(TOKEN));assert.ok(!bytes.includes(activeToken));
 const sources=(await pool.query(`SELECT source_path FROM "${schema}".source_files ORDER BY source_path`)).rows.map(row=>row.source_path);assert.deepEqual(sources,['truestats-runtime-state.json','truestats-wb-link.json','truestats.json']);
});
