'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {stockInventorySummary,compareStockInventories,legacyStockInventory,summarizePostgresStock,summarizeLegacyStock,compareStockSummary}=require('../storage/postgres-stock-history-parity.cjs');
const {ingest}=require('../stock-history.cjs');
const inventory=()=>({imports:[{id:'a',importedAt:'2026-09-22T00:00:00.000Z',manifestText:'[]',issuesText:'[]'}],rows:[{id:'r',day:'2026-09-22',observedAt:null,source:'daily-total',storeId:'1',storeName:'Synthetic',sku:'001',article:null,name:null,warehouse:null,warehouseId:null,cluster:null,totalStock:'0',available:null,inTransit:null,reserved:null,quality:null,detailsText:'{}'}],origins:[{rowId:'r',importId:'a',sourceFile:'x.json',sourceRow:'0'}]});
test('stock parity hashes exact imports, business rows and origins independently',()=>{const left=inventory(),right=structuredClone(left),result=compareStockInventories(left,right);assert.equal(result.matched,true);assert.deepEqual(Object.keys(stockInventorySummary(left)),['imports','rows','origins']);right.rows[0].sku='002';assert.throws(()=>compareStockInventories(left,right),error=>error.code==='PARITY_MISMATCH');assert.throws(()=>compareStockSummary({imports:{count:'1',sha256:'a'.repeat(64)}},{imports:{count:'1',sha256:'a'.repeat(64)}}),error=>error.code==='PARITY_INVALID')});
test('legacy inventory preserves textual JSON, null quantities and business origin keys',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pult-stock-parity-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const dbFile=path.join(dir,'stocks.sqlite');ingest({dbFile,importId:'a'.repeat(64),manifest:[{x:1}],issues:[],now:'2026-09-22T00:00:00.000Z',rows:[{day:'2026-09-22',observedAt:null,source:'daily-total',storeId:'1',storeName:'Synthetic',sku:'001',article:null,name:null,warehouse:null,warehouseId:null,cluster:null,totalStock:0,available:null,inTransit:null,reserved:null,quality:null,details:{z:1},sourceFile:'x.json',sourceRow:0}]});const value=legacyStockInventory({dbFile});assert.equal(value.rows[0].totalStock,'0');assert.equal(value.rows[0].available,null);assert.equal(value.rows[0].detailsText,'{"z":1}');assert.deepEqual(value.origins[0],{rowId:value.rows[0].id,importId:'a'.repeat(64),sourceFile:'x.json',sourceRow:'0'})});

const url=process.env.PULT_TEST_DATABASE_URL;
test('PostgreSQL integration: stock streaming parity crosses batches with Cyrillic and null values',{skip:!url,timeout:30000},async t=>{assert.match(decodeURIComponent(new URL(url).pathname.slice(1)),/^pult_test_[a-f0-9]+$/u);const{Pool}=require('pg'),pool=new Pool({connectionString:url,max:3}),dir=fs.mkdtempSync(path.join(os.tmpdir(),'pult-stock-stream-')),dbFile=path.join(dir,'stocks.sqlite');t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));let owned=false;try{assert.equal((await pool.query("SELECT count(*)::int n FROM pg_namespace WHERE nspname IN ('pult','pult_history')")).rows[0].n,0);await pool.query(require('../storage/postgres-schema.cjs'));await pool.query(require('../storage/postgres-history-schema.cjs'));owned=true;const rows=Array.from({length:259},(_,i)=>({day:'2026-09-22',observedAt:i%2?null:'2026-09-22T01:02:03.000Z',source:'daily-total',storeId:'1',storeName:'Магазин',sku:`товар-${String(i).padStart(4,'0')}`,article:i%3?null:'Арт',name:i%5?`Имя ${i}`:null,warehouse:null,warehouseId:null,cluster:null,totalStock:i,available:i%2?null:0,inTransit:null,reserved:null,quality:null,details:{индекс:i},sourceFile:'synthetic.json',sourceRow:i})),command={schemaVersion:1,kind:'stock-history.ingest',commandId:crypto.randomUUID(),expectedRevision:'0',importId:'f'.repeat(64),importedAt:'2026-09-22T12:00:00.000Z',manifest:[],issues:[],rows};ingest({dbFile,importId:command.importId,manifest:[],issues:[],rows,now:command.importedAt});const state=require('../storage/postgres-state.cjs').createStateStore({pool});await require('../storage/postgres-stock-history-writer.cjs').createStockHistoryWriter({stateStore:state}).ingest(command);const client=await pool.connect();let expected;try{await client.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');expected=await summarizePostgresStock(client,{batchSize:19});await client.query('COMMIT')}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}const actual=await summarizeLegacyStock({dbFile});assert.equal(expected.rows.version,2);assert.equal(expected.rows.count,'259');assert.equal(compareStockSummary(expected,actual).matched,true);const db=new(require('node:sqlite').DatabaseSync)(dbFile);db.exec("UPDATE stock_rows SET quality='changed' WHERE id=(SELECT min(id) FROM stock_rows)");db.close();assert.throws(()=>compareStockSummary(expected,require('../storage/postgres-parity-stream.cjs').inventorySummary(legacyStockInventory({dbFile}),['imports','rows','origins'])),error=>error.code==='PARITY_MISMATCH')}finally{if(owned)await pool.query('DROP SCHEMA IF EXISTS pult_history,pult CASCADE');await pool.end()}});
