'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),fsSync=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite'),{gzipSync}=require('node:zlib');
const {createMigrationSnapshot}=require('../storage/migration-snapshot.cjs');
const {importDocuments,sourceKey}=require('../storage/postgres-document-import.cjs');
const {createStateStore}=require('../storage/postgres-state.cjs');
const {createMarketHistoryRepository}=require('../storage/postgres-history-repository.cjs');
const {createPostgresArchiveRepository}=require('../storage/postgres-archive-repository.cjs');
const {createJournaledHistory}=require('../storage/postgres-journaled-history.cjs');
const {createJournaledArchive}=require('../storage/postgres-journaled-archive.cjs');
const {createMarketWriter}=require('../storage/postgres-market-writer.cjs');
const {exportRuntimeJournal,verifyRuntimeJournal}=require('../storage/postgres-runtime-journal.cjs');
const {replayRuntimeJournal,verifyRuntimeReplay,TREE_DIRECTORY,_test}=require('../storage/postgres-runtime-replay.cjs');
const {create:createLegacyHistory}=require('../market-history.cjs'),{create:createLegacyArchive}=require('../market-history-archive.cjs');
const hash=value=>crypto.createHash('sha256').update(value).digest('hex'),capturedAt='2026-09-22T08:00:00.000Z';
const raw=units=>Buffer.from(JSON.stringify({orders:{period:{from:'2026-09-21',to:'2026-09-21'},skuUpdatedAt:capturedAt,skuDailyCoverage:true,skuCoverage:['2026-09-21'],skuDaily:[{date:'2026-09-21',sku:'A',units,revenue:10}]}}));
async function roots(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'pult-runtime-test-'));t.after(async()=>{assert.equal(path.dirname(root),await fs.realpath(os.tmpdir()));await fs.rm(root,{recursive:true,force:true})});for(const name of['source','snapshot','journal','replay'])await fs.mkdir(path.join(root,name));return{root,source:path.join(root,'source'),snapshot:path.join(root,'snapshot'),journal:path.join(root,'journal'),replay:path.join(root,'replay')}}
async function baseline(t){const r=await roots(t);await fs.writeFile(path.join(r.source,'management.json'),'{}\n');const historyDir=path.join(r.source,'history');await fs.mkdir(historyDir);createLegacyHistory({dbFile:path.join(historyDir,'products.sqlite')}).close();createLegacyArchive({privateDir:r.source}).close();const baseRaw=Buffer.from(JSON.stringify({items:Array.from({length:500},(_,i)=>`v-${i}`)})),contentHash=hash(baseRaw),gzip=gzipSync(baseRaw,{level:9,mtime:0}),object=`snapshots/${contentHash.slice(0,2)}/${contentHash}.json.gz`;await fs.mkdir(path.dirname(path.join(historyDir,object)),{recursive:true});await fs.writeFile(path.join(historyDir,object),gzip);const db=new DatabaseSync(path.join(historyDir,'archive.sqlite'));db.prepare('INSERT INTO versions VALUES(?,?,?,?,?,?,?,?)').run('data-1.json',contentHash,capturedAt,100,baseRaw.length,gzip.length,object,'not_applicable');db.prepare('INSERT INTO latest VALUES(?,?,?)').run('data-1.json',`${baseRaw.length}:100`,contentHash);db.exec('PRAGMA journal_mode=DELETE');db.close();const products=new DatabaseSync(path.join(historyDir,'products.sqlite'));products.exec('PRAGMA journal_mode=DELETE');products.close();await createMigrationSnapshot({sourceRoot:r.source,destinationDir:r.snapshot,writersStopped:true});return{...r,baseRaw,contentHash,gzip}}
const integrationUrl=process.env.PULT_TEST_DATABASE_URL;
test('PostgreSQL integration: runtime journal reconstructs documents, history and archive in an incomplete-safe stage',{skip:!integrationUrl,timeout:60000},async t=>{const database=decodeURIComponent(new URL(integrationUrl).pathname.slice(1));assert.match(database,/^pult_test_[a-z0-9]+$/u);const{Pool}=require('pg'),pool=new Pool({connectionString:integrationUrl,max:4});let owned=false;t.after(async()=>{if(owned)await pool.query('DROP SCHEMA IF EXISTS pult_market,pult_history,pult CASCADE');await pool.end()});assert.equal((await pool.query("SELECT count(*)::int n FROM pg_namespace WHERE nspname IN ('pult','pult_history','pult_market')")).rows[0].n,0);await pool.query(require('../storage/postgres-schema.cjs'));await pool.query(require('../storage/postgres-document-schema.cjs'));await pool.query(require('../storage/postgres-history-schema.cjs'));await pool.query(require('../storage/postgres-market-schema.cjs'));owned=true;const b=await baseline(t);await importDocuments({pool,sourceDir:b.snapshot});await pool.query(`INSERT INTO pult_history.archive_versions(source_file,content_hash,captured_at,captured_at_text,source_mtime,source_bytes,archive_bytes,object_path,facts_status,archive_payload,archive_gzip_hash) VALUES('data-1.json',$1,$2::text::timestamptz,$2::text,100,$3,$4,$5,'not_applicable',$6,sha256($6))`,[b.contentHash,capturedAt,b.baseRaw.length,b.gzip.length,`snapshots/${b.contentHash.slice(0,2)}/${b.contentHash}.json.gz`,b.gzip]);await pool.query(`INSERT INTO pult_history.archive_latest VALUES('data-1.json',$2,$1)`,[b.contentHash,`${b.baseRaw.length}:100`]);
  const state=createStateStore({pool}),history=createMarketHistoryRepository({pool}),archive=createPostgresArchiveRepository({pool,history}),jh=createJournaledHistory({stateStore:state,history}),ja=createJournaledArchive({stateStore:state,archive});
  await state.write(sourceKey('management.json'),Buffer.from('{"changed":true}\n'),{expectedRevision:'1',commandId:crypto.randomUUID(),mediaType:'application/json'});
  await pool.query(`CREATE FUNCTION pult.reject_history_gap() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'synthetic sequence gap'; END$$; CREATE TRIGGER reject_history_gap BEFORE INSERT ON pult.commands FOR EACH ROW EXECUTE FUNCTION pult.reject_history_gap()`);const failedRaw=raw(99);await assert.rejects(jh.ingest({schemaVersion:1,kind:'history.ingest',commandId:crypto.randomUUID(),expectedRevision:'0',sourceFile:'insights-9.json',contentHash:hash(failedRaw),capturedAt,raw:failedRaw}),error=>error.code==='DATABASE_ERROR');await pool.query('DROP TRIGGER reject_history_gap ON pult.commands; DROP FUNCTION pult.reject_history_gap()');
  const historyRaw=raw(2),historyCommand={schemaVersion:1,kind:'history.ingest',commandId:crypto.randomUUID(),expectedRevision:'0',sourceFile:'insights-1.json',contentHash:hash(historyRaw),capturedAt,raw:historyRaw},historyWritten=await jh.ingest(historyCommand);assert.deepEqual(await jh.ingest(historyCommand),{...historyWritten,replayed:true});
  const historyInputs=[
    ['ledger-1.json',{stamp:capturedAt,data:{period:{from:'2026-09-21',to:'2026-09-21'},completedAt:capturedAt,complete:true,skuDaily:[{date:'2026-09-21',sku:'A',values:{soldUnits:3,returnedUnits:1,realized:500,ads:40,unknownUnitRows:2}}]}}],
    ['wb-orders-wb-2.json',{day:'2026-09-21',fetchedAt:capturedAt,complete:true,orders:[{at:'2026-09-21T10:15:00.000Z',amount:19.5,nmId:77}]}],
    ['order-category-catalog-1.json',{products:[{sku:'A',product_id:'P-1',offer_id:'OFF-1',name:'Catalog name',market:'Ozon'}]}]
  ];for(const[sourceFile,data]of historyInputs){const bytes=Buffer.from(JSON.stringify(data));await jh.ingest({schemaVersion:1,kind:'history.ingest',commandId:crypto.randomUUID(),expectedRevision:'0',sourceFile,contentHash:hash(bytes),capturedAt,raw:bytes})}
  await pool.query("INSERT INTO pult_market.stores(store_id,market,display_name) VALUES('1','Ozon','Synthetic')");const marketSnapshot={clientId:'1',market:'Ozon',completedAt:capturedAt,products:[{product_id:10,sku:20,offer_id:'M',name:'Market'}],stocks:[{product_id:10,stocks:[{sku:20,warehouse:'W',present:2}]}],operations:[{operation_id:30,date:'2026-09-21',operation_type:'Sale',posting:{products:[{sku:20,quantity:2}]}}],stockRows:[],categoryTree:[]},marketBytes=Buffer.from(JSON.stringify(marketSnapshot));await createMarketWriter({stateStore:state}).publish({storeId:'1',exactBytes:marketBytes,expectedRevision:'0',commandId:crypto.randomUUID()});const marketCommand=(await pool.query("SELECT result_json FROM pult.commands c JOIN pult.source_files s USING(logical_key) WHERE s.source_path='data-1.json'")).rows[0];assert.match(marketCommand.result_json.sourceSha256,/^[a-f0-9]{64}$/u);
  const duplicate=await ja.addVersion({schemaVersion:1,kind:'archive.version-add',commandId:crypto.randomUUID(),expectedRevision:'0',sourceFile:'data-1.json',sourceMtime:50,capturedAt,raw:b.baseRaw});assert.equal(duplicate.result.changed,false);assert.equal(duplicate.result.gzipHash,hash(b.gzip));
  const archiveRaw=raw(3),add=await ja.addVersion({schemaVersion:1,kind:'archive.version-add',commandId:crypto.randomUUID(),expectedRevision:'0',sourceFile:'insights-2.json',sourceMtime:20,capturedAt,raw:archiveRaw});await ja.processVersion({schemaVersion:1,kind:'archive.process-exact-pending-version',commandId:crypto.randomUUID(),expectedRevision:'1',sourceFile:'insights-2.json',contentHash:add.result.contentHash,capturedAt:'2026-09-22T08:01:00.000Z'});
  const manifest=await exportRuntimeJournal({pool,checkpointSequence:'0',destinationDir:b.journal});assert.deepEqual([...new Set(manifest.commands.map(x=>x.type))].sort(),['archive','document','history']);await verifyRuntimeJournal(b.journal);const replay=await replayRuntimeJournal({snapshotDir:b.snapshot,journalDir:b.journal,destinationDir:b.replay});assert.equal(replay.rollbackReady,false);assert.equal(replay.historyParity.matched,true);await verifyRuntimeReplay(b.replay);const tree=path.join(b.replay,TREE_DIRECTORY);assert.deepEqual(JSON.parse(await fs.readFile(path.join(tree,'management.json'),'utf8')),{changed:true});assert.deepEqual(await fs.readFile(path.join(tree,'data-1.json')),marketBytes);const restored=createLegacyHistory({dbFile:path.join(tree,'history','products.sqlite')});try{const sqlReport=await history.report({from:'2026-09-21',to:'2026-09-21',metric:'units'}),legacyReport=restored.report({from:'2026-09-21',to:'2026-09-21',metric:'units'});assert.deepEqual(legacyReport.rows,sqlReport.rows);assert.deepEqual(legacyReport.coverage,sqlReport.coverage)}finally{restored.close()}const pgId=(await pool.query("SELECT id::text FROM pult_history.ingestions WHERE source_file='insights-1.json'")).rows[0].id,idDb=new DatabaseSync(path.join(tree,'history','products.sqlite'),{readOnly:true});let sqliteId;try{sqliteId=String(idDb.prepare("SELECT id FROM ingestions WHERE source_file='insights-1.json'").get().id)}finally{idDb.close()}assert.notEqual(pgId,sqliteId,'surrogate IDs should be allowed to differ after a rolled-back PostgreSQL sequence allocation');const adb=new DatabaseSync(path.join(tree,'history','archive.sqlite'),{readOnly:true});try{assert.equal(adb.prepare("SELECT facts_status FROM versions WHERE source_file='insights-2.json'").get().facts_status,'imported');assert.equal(adb.prepare("SELECT content_hash FROM latest WHERE source_file='data-1.json'").get().content_hash,b.contentHash)}finally{adb.close()}
  const corrupted=path.join(b.root,'corrupt');await fs.cp(b.journal,corrupted,{recursive:true});const blob=manifest.blobs.find(x=>manifest.commands.some(c=>c.type==='archive'&&c.after.blob?.sha256===x.sha256));await fs.truncate(path.join(corrupted,...blob.path.split('/')),1);await assert.rejects(verifyRuntimeJournal(corrupted),e=>e.code==='JOURNAL_INVALID');const failedStage=path.join(b.root,'failed-stage');await fs.mkdir(failedStage);await assert.rejects(replayRuntimeJournal({snapshotDir:b.snapshot,journalDir:corrupted,destinationDir:failedStage}));assert.equal(JSON.parse(await fs.readFile(path.join(failedStage,'RUNTIME_REPLAY_INCOMPLETE.json'),'utf8')).status,'incomplete');assert.equal(await fs.access(path.join(failedStage,'RUNTIME_REPLAY_COMPLETE.json')).then(()=>true,()=>false),false);
  const missing=path.join(b.root,'missing');await fs.cp(b.journal,missing,{recursive:true});await fs.unlink(path.join(missing,...manifest.blobs[0].path.split('/')));await assert.rejects(verifyRuntimeJournal(missing),e=>e.code==='JOURNAL_INVALID');
});

test('unknown command with recomputed manifest hash fails closed and leaves replay incomplete',async t=>{const b=await baseline(t),manifest={schemaVersion:1,status:'complete',scope:'documents-history-archive',baselineSequence:'0',upperSequence:'1',baselineDocuments:[],commands:[{sequence:'1',commandId:crypto.randomUUID(),type:'market',operation:'write',logicalKey:'market/x',sourcePath:null,beforeRevision:'0',afterRevision:'1',beforeMediaType:null,mediaType:'x/y',before:{deleted:null,blob:null},after:{deleted:false,blob:null},envelope:{},result:{}}],blobs:[],rollbackReady:false};const bytes=Buffer.from(JSON.stringify(manifest,null,2)+'\n');await fs.writeFile(path.join(b.journal,'runtime-journal-manifest.json'),bytes);await fs.mkdir(path.join(b.journal,'blobs'));await fs.writeFile(path.join(b.journal,'RUNTIME_JOURNAL_COMPLETE.json'),JSON.stringify({schemaVersion:1,manifest:'runtime-journal-manifest.json',manifestSha256:hash(bytes)})+'\n');await assert.rejects(verifyRuntimeJournal(b.journal),e=>e.code==='JOURNAL_INVALID');assert.equal((await fs.readdir(b.replay)).length,0)});

test('SQLite checkpoint refuses a busy reader and preserves the WAL',async t=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'pult-checkpoint-busy-'));t.after(async()=>fs.rm(root,{recursive:true,force:true}));const file=path.join(root,'busy.sqlite'),writer=new DatabaseSync(file);writer.exec('PRAGMA journal_mode=WAL; CREATE TABLE rows(id INTEGER PRIMARY KEY); INSERT INTO rows VALUES(1)');const reader=new DatabaseSync(file);reader.exec('BEGIN');reader.prepare('SELECT * FROM rows').all();writer.exec('INSERT INTO rows VALUES(2)');writer.close();await assert.rejects(_test.checkpointSqlite(file),error=>error.code==='SQLITE_BUSY');const wal=await fs.stat(file+'-wal');assert.ok(wal.size>0);reader.exec('ROLLBACK');reader.close()});
