'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const create=require('../storage/domains/postgres-buyer-product-segments.cjs').create;
const FROM='2026-09-01',TO='2026-09-07',stores={1:{name:'Первый'},'wb-1':{name:'WB',market:'WB'}};
const segment=(units,{cancelledUnits=0,amountRub=null,amountKnown=false}={})=>({units,orders:units,cancelledUnits,cancelledOrders:cancelledUnits,cancellationUnknownUnits:0,cancellationUnknownOrders:0,amountRub,amountKnown});
function prepared(){return {status:'partial',period:{from:FROM,to:TO},products:[{productId:'101',segments:{legal:segment(7,{cancelledUnits:2,amountRub:700,amountKnown:true}),individual:segment(3)},legalShare:.7},{productId:'102',segments:{legal:segment(4,{amountRub:999,amountKnown:false}),individual:segment(0)},legalShare:1}],coverage:{sources:[{market:'Ozon',scheme:'FBO',storeId:'1',name:'Первый',available:true,complete:false,coversRequested:true},{market:'Ozon',scheme:'FBS',storeId:'1',name:'Первый',available:true,complete:true,coversRequested:true}]}};}
const catalogs={1:{products:[{sku:101,name:'Первый товар'},{sku:102,name:'Второй товар'}]},'wb-1':{products:[{nmID:201,name:'WB товар'}]}};
function service(overrides={}){return create({getStores:async()=>structuredClone(stores),getSnapshot:async()=>prepared(),getOrderSnapshots:async()=>[],getCatalog:async id=>catalogs[id],...overrides});}
test('prepared SQL snapshot preserves ranking, exact unknown amount and selected buyer type',async()=>{const result=await service().read({from:FROM,to:TO,market:'Ozon'});assert.equal(result.status,'partial');assert.equal(result.products[0].name,'Первый товар');assert.equal(result.products[0].cancelledUnits,2);assert.equal(result.products[0].amountRub,700);assert.equal(result.products[1].amountRub,null);assert.equal(result.totals.legal.units,11);assert.equal(result.totals.legal.amountRub,null);});
test('connected missing marketplace remains unavailable and providers are awaited fresh',async()=>{let reads=0;const value=service({getSnapshot:async()=>{reads++;return prepared()}});assert.equal((await value.read({from:FROM,to:TO,market:'WB'})).status,'unavailable');await value.read({from:FROM,to:TO,market:'Ozon'});assert.equal(reads,2);});
test('fallback derives product segments from explicit order snapshots without directory scans',async()=>{const order={generatedAt:'2026-09-08T00:00:00Z',records:[{id:'r1',market:'Ozon',storeId:'1',scheme:'FBO',orderKey:'o1',buyerType:'legal'}],productOrders:[{market:'Ozon',storeId:'1',scheme:'FBO',orderId:'o1',postingId:'p1',productId:'101',orderedAt:'2026-09-03T10:00:00Z',units:5,amountRub:500,cancelled:false,updatedAt:'2026-09-08T00:00:00Z'}],report:{coverage:{sources:[{market:'Ozon',scheme:'FBO',storeId:'1',name:'Первый',available:true,complete:true,from:FROM,to:'2026-09-06'}]}}};const result=await service({getSnapshot:async()=>null,getOrderSnapshots:async()=>[order]}).read({from:FROM,to:TO,market:'Ozon'});assert.equal(result.status,'partial');assert.equal(result.products[0].legalUnits,5);assert.equal(result.products[0].storeId,'1');});
test('fallback keeps known partial products, deduplicates retries and exposes a newer day missing product rows',async()=>{
 const row={market:'Ozon',storeId:'1',scheme:'FBO',orderId:'o1',postingId:'p1',productId:'101',orderedAt:'2026-09-03T10:00:00Z',units:5,amountRub:500,cancelled:false,updatedAt:'2026-09-06T12:00:00Z'},record={id:'r1',market:'Ozon',storeId:'1',scheme:'FBO',orderKey:'o1',buyerType:'legal'},source={market:'Ozon',scheme:'FBO',storeId:'1',name:'Первый',available:true,complete:true,from:FROM,to:'2026-09-06'},partial={_partialSource:true,generatedAt:'2026-09-06T12:00:00Z',records:[record],productOrders:[row],report:{coverage:{sources:[source]}},},retry={_partialSource:true,generatedAt:'2026-09-06T13:00:00Z',records:[],productOrders:[],report:{coverage:{sources:[{...source,available:false,complete:false,limitation:'failed retry'}]}},},daily={generatedAt:'2026-09-08T00:00:00Z',records:[{id:'r2',market:'Ozon',storeId:'1',scheme:'FBO',orderKey:'o2',buyerType:'legal'}],productOrders:[],report:{coverage:{sources:[{market:'Ozon',scheme:'FBO',storeId:'1',name:'Первый',available:true,complete:true,from:'2026-09-07',to:'2026-09-07'}]}}};
 const result=await service({getSnapshot:async()=>null,getOrderSnapshots:async()=>[partial,retry,daily]}).read({from:FROM,to:TO,market:'Ozon'}),fbo=result.coverage.sources.filter(item=>item.scheme==='FBO');
 assert.equal(result.status,'partial');assert.equal(result.products[0].legalUnits,5);assert.equal(result.totals.legal.units,5);assert.equal(fbo.length,2);assert.ok(fbo.some(item=>item.available&&!item.complete&&/част|период/u.test(item.limitation)));assert.ok(fbo.some(item=>!item.available&&!item.complete&&/товарные строки/u.test(item.limitation)));
});
test('compact SQL product documents bypass full order snapshots and honor buyer filter',async()=>{let orderReads=0,aggregateOptions;const order={generatedAt:'2026-09-08T00:00:00Z',records:[{market:'Ozon',storeId:'1',scheme:'FBO'}],productOrders:[{market:'Ozon',storeId:'1',scheme:'FBO',orderId:'sql:101:legal:false',productId:'101',orderedAt:'2026-09-03T10:00:00Z',units:5,amountRub:500,buyerType:'legal',cancelled:false},{market:'Ozon',storeId:'1',scheme:'FBO',orderId:'sql:101:individual:true',productId:'101',orderedAt:'2026-09-03T10:00:00Z',units:2,amountRub:200,buyerType:'individual',cancelled:true}],report:{coverage:{sources:[{market:'Ozon',scheme:'FBO',storeId:'1',name:'Первый',available:true,complete:true,from:FROM,to:TO}]}}};const result=await service({getSnapshot:async()=>null,getOrderSnapshots:async()=>{orderReads++;return[]},getAggregate:async options=>{aggregateOptions=options;return{documents:[order]}}}).read({from:FROM,to:TO,market:'Ozon',storeId:'1',buyerType:'individual'});assert.equal(orderReads,0);assert.deepEqual(aggregateOptions,{from:FROM,to:TO,market:'Ozon',storeId:'1'});assert.equal(result.products[0].orderedUnits,2);assert.equal(result.products[0].cancelledUnits,2);assert.equal(result.products[0].name,'Первый товар');});
test('invalid filters and provider contracts fail closed',async()=>{await assert.rejects(service().read({from:FROM,to:TO,buyerType:'company'}),/тип покупателя/u);await assert.rejects(service({getStores:async()=>null}).read({from:FROM,to:TO}),/каталог магазинов/u);});
test('revision-keyed projection cache skips repeated heavy reads and invalidates exactly on source change',async()=>{
 let revision='1',snapshotReads=0,aggregateReads=0,catalogReads=0;
 const aggregate=async()=>{aggregateReads++;return{documents:[]}};
 aggregate.revision=async()=>revision;
 aggregate.catalogs=async()=>{catalogReads++;return new Map(Object.entries(catalogs))};
 const value=service({getSnapshot:async()=>{snapshotReads++;return prepared()},getAggregate:aggregate,getCatalog:async()=>{throw Error('per-store catalog path must not run')}});
 const first=await value.read({from:FROM,to:TO,market:'Ozon'}),second=await value.read({from:FROM,to:TO,market:'Ozon'});
 assert.deepEqual(second,first);assert.equal(snapshotReads,1);assert.equal(aggregateReads,0);assert.equal(catalogReads,1);
 revision='2';await value.read({from:FROM,to:TO,market:'Ozon'});
 assert.equal(snapshotReads,2);assert.equal(catalogReads,2);
});
