'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const { createCadenceProducer, GAP } = require('../storage/acquisition/postgres-cadence-producer.cjs');
const digest = value => crypto.createHash('sha256').update(value).digest();
function row(value, revision = '1') { const content = Buffer.from(JSON.stringify(value)); return { revision, mediaType: 'application/json', content, sha256: digest(content), deleted: false }; }
function fixture({ now = '2026-09-22T12:00:00.000Z', jobs = {}, documents = {}, stores = { '1': { market: 'Ozon' } }, leaseActive = async () => true, buildDerivedPayload = null } = {}) { let revision = 0; const transitions = [],reads=[],requests=new Map(), scheduler = { load: async () => ({ revision: String(revision), value: { jobs } }), captureRequest:async value=>{const saved=requests.get(value.commandId);if(saved){if(saved.timestamp!==value.timestamp)throw Object.assign(Error(),{code:'COMMAND_ID_REUSED'});return{targets:structuredClone(saved.targets),replayed:true}}const copy=structuredClone(value);requests.set(value.commandId,copy);revision++;return{targets:structuredClone(copy.targets),replayed:false}},transitionReceipt:async expected=>{const saved=transitions.find(value=>value.commandId===expected.commandId);if(!saved)return null;if(saved.kind!==expected.kind||saved.storeId!==expected.storeId||saved.timestamp!==expected.timestamp)throw Object.assign(Error(),{code:'COMMAND_ID_REUSED'});return structuredClone(saved)}, transition: async request => { transitions.push(structuredClone(request)); revision++; const saved = { ...request }; for (const key of ['expectedRevision','expectedAttemptId','expectedState','expectedRunnerId']) delete saved[key]; jobs[`${saved.kind}:${saved.storeId}`] = saved; return { revision: String(revision), job: saved }; } }; return { transitions, reads, stores, producer: createCadenceProducer({ scheduler, storesRepository: { read: async () => structuredClone(stores) }, stateStore: { read: async key => { reads.push(key); return documents[key] || null; } }, now: () => new Date(now), leaseActive, buildDerivedPayload, intervalMs: 1000 }) }; }
const key = path => require('../storage/postgres-document-import.cjs').sourceKey(path);
test('cadence startup is nonblocking and shutdown drains the initial read without enqueuing', async () => {
  let release, callback, returned = false, reads = 0, transitions = 0, cleared = 0;
  const gate = new Promise(resolve => { release = resolve; });
  const producer = createCadenceProducer({
    scheduler: { load: async () => ({ revision: '0', value: { jobs: {} } }), transition: async () => { transitions++; }, captureRequest: async () => {}, transitionReceipt: async () => null },
    storesRepository: { read: async () => { reads++; await gate; return { '1': { market: 'Ozon' } }; } }, stateStore: { read: async () => null },
    setIntervalFn: fn => { callback = fn; return { unref() {} }; }, clearIntervalFn: () => { cleared++; }
  });
  try {
    const starting = producer.start().then(() => { returned = true; });
    await new Promise(resolve => setImmediate(resolve));
    assert.equal(returned, true); callback(); assert.equal(reads, 1);
    let drained = false; const closing = producer.close().then(() => { drained = true; });
    await new Promise(resolve => setImmediate(resolve));
    assert.equal(drained, false); assert.equal(cleared, 1);
    release(); await Promise.all([starting, closing]); assert.equal(transitions, 0);
  } finally { release(); await producer.close(); }
});
test('producer preserves due ordering and only queues one shared Ozon analytics attempt', async () => { const f = fixture(); await f.producer.tick(); const analytics = f.transitions.filter(value => value.kind.startsWith('insights-')); assert.equal(analytics.length, 1); assert.equal(analytics[0].kind, 'insights-full'); assert.ok(f.transitions.some(value => value.kind === 'market')); assert.ok(f.transitions.some(value => value.kind === 'costs-prices')); await f.producer.close(); });
test('queued and unknown attempts survive restart without replacement', async () => { const held = { kind: 'insights-full', storeId: '1', state: 'unknown', attemptId: crypto.randomUUID(), commandId: crypto.randomUUID(), timestamp: '2026-09-22T11:00:00.000Z', nextDueAt: '2026-09-22T11:00:00.000Z', errorCodes: ['UNKNOWN_OUTCOME'], runnerId: null }, f = fixture({ jobs: { 'insights-full:1': held } }); await f.producer.tick(); assert.equal(f.transitions.some(value => value.kind.startsWith('insights-')), false); await f.producer.close(); });
test('nonterminal regular jobs do not reread their large source documents', async () => { const active=state=>({kind:'market',storeId:'1',state,attemptId:crypto.randomUUID(),commandId:crypto.randomUUID(),timestamp:'2026-09-22T11:00:00.000Z',nextDueAt:'2026-09-22T11:00:00.000Z',errorCodes:[],runnerId:null}),market=active('unknown'),costs={...active('queued'),kind:'costs-prices'},analytics={...active('running'),kind:'insights-full'},f=fixture({jobs:{'market:1':market,'costs-prices:1':costs,'insights-full:1':analytics}});await f.producer.tick();assert.deepEqual(f.reads,[]);assert.equal(f.transitions.length,0);await f.producer.close();});
test('shared analytics gate and imminent orders suppress funnel', async () => { const at = Date.parse('2026-09-22T12:00:00.000Z'), documents = { [key('insights-1.json')]: row({ analyticsAttemptAt: new Date(at - GAP + 1).toISOString() }), [key('ozon-funnel-1.json')]: row({}) }, f = fixture({ documents }); await f.producer.tick(); assert.equal(f.transitions.some(value => value.kind.startsWith('insights-')), false); await f.producer.close(); });
test('source corruption fails closed and close fences lease loss', async () => { const bytes = Buffer.from('{}'), documents = { [key('data-1.json')]: { revision: '1', mediaType: 'application/json', content: bytes, sha256: Buffer.alloc(32) } }, corrupt = fixture({ documents }); await assert.rejects(corrupt.producer.tick(), { code: 'SOURCE_INTEGRITY' }); await corrupt.producer.close(); let leases = 0; const fenced = fixture({ leaseActive: async () => ++leases < 2 }); await fenced.producer.tick(); assert.equal(fenced.transitions.length, 0); await fenced.producer.close(); });
test('manual request is stable and derived payload is durable before dispatch',async()=>{const payload={intraday:[],category:{stores:[],categories:[],registry:{available:false},date:'2026-09-22',evidence:[]},archives:[]},f=fixture({buildDerivedPayload:async()=>payload});await f.producer.tick();const derived=f.transitions.find(value=>value.kind==='derived-capture');assert.deepEqual(derived.payload,payload);assert.match(derived.payloadHash,/^[a-f0-9]{64}$/u);await f.producer.close();const manual=fixture(),commandId='11111111-1111-4111-8111-111111111111',timestamp='2026-09-22T12:01:00.000Z',first=await manual.producer.request({storeId:'1',kinds:['insights-full'],commandId,timestamp}),count=manual.transitions.length;const second=await manual.producer.request({storeId:'1',kinds:['insights-full'],commandId,timestamp}),busy=await manual.producer.request({storeId:'1',kinds:['insights-full'],commandId:'22222222-2222-4222-8222-222222222222',timestamp});assert.deepEqual(second.attempts,first.attempts);assert.deepEqual(busy.attempts,first.attempts,'busy refresh reports the durable active attempt rather than a fictitious new id');assert.equal(manual.transitions.length,count);await manual.producer.close();});
test('manual request survives bounded scheduler contention with one immutable command intent',async()=>{let conflicts=3,revision=0;const requests=[],scheduler={load:async()=>({revision:String(revision++),value:{jobs:{}}}),captureRequest:async()=>{},transitionReceipt:async()=>null,transition:async request=>{requests.push(structuredClone(request));if(conflicts-->0)throw Object.assign(Error('conflict'),{code:conflicts%2?'REVISION_CONFLICT':'JOB_CONFLICT'});return{revision:String(revision),job:request}}},producer=createCadenceProducer({scheduler,storesRepository:{read:async()=>({'1':{market:'Ozon'}})},stateStore:{read:async()=>null},leaseActive:async()=>true,now:()=>new Date('2026-09-22T12:00:00.000Z')});const result=await producer.request({storeId:'1',kinds:['market'],commandId:'44444444-4444-4444-8444-444444444444',timestamp:'2026-09-22T12:01:00.000Z'});assert.equal(requests.length,4);assert.equal(new Set(requests.map(row=>row.commandId)).size,1);assert.equal(new Set(requests.map(row=>row.attemptId)).size,1);assert.equal(new Set(requests.map(row=>row.timestamp)).size,1);assert.equal(result.attempts.market,requests[0].attemptId);await producer.close();});
test('refresh-all captures immutable Ozon targets and retry ignores later registry changes',async()=>{const f=fixture({stores:{'1':{market:'Ozon'},'2':{market:'Ozon'},'wb-3':{market:'WB'}}}),commandId='33333333-3333-4333-8333-333333333333',timestamp='2026-09-22T12:02:00.000Z',first=await f.producer.requestAll({commandId,timestamp}),commands=f.transitions.map(row=>row.commandId),count=f.transitions.length;delete f.stores['2'];f.stores['4']={market:'Ozon'};const second=await f.producer.requestAll({commandId,timestamp});assert.deepEqual(first.targets,['1','2']);assert.deepEqual(second.targets,first.targets);assert.equal(second.replayed,true);assert.equal(f.transitions.length,count,'durable parent replay must not enqueue new children');assert.equal(new Set(commands).size,2);assert.ok(commands.every(value=>value!==commandId));await f.producer.close()});
test('live cadence reader requests metadata without legacy document reads',async()=>{const paths=[],transitions=[],scheduler={load:async()=>({revision:'0',value:{jobs:{}}}),transitionReceipt:async()=>null,captureRequest:async()=>{},transition:async value=>{transitions.push(value);return{revision:'1',job:value}}},producer=createCadenceProducer({scheduler,storesRepository:{read:async()=>({'1':{market:'Ozon'}})},readDocument:async path=>{paths.push(path);return{revision:'4',value:{completedAt:'2026-09-20T00:00:00.000Z'}}},now:()=>new Date('2026-09-22T12:00:00.000Z')});await producer.tick();assert.ok(paths.includes('data-1.json'));assert.ok(paths.includes('costs-1.json'));assert.ok(paths.includes('insights-1.json'));assert.ok(paths.includes('ozon-funnel-1.json'));assert.equal(transitions.every(row=>row.documentRevision==='4'),true);await producer.close()});
