'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createOptimizerRoutes}=require('../storage/domains/postgres-optimizer-routes.cjs');
const COMMAND='11111111-1111-4111-8111-111111111111',TIME='2026-09-24T09:00:00.000Z';
const response=()=>({status:null,headers:null,text:'',writeHead(status,headers){this.status=status;this.headers=headers},end(value){this.text=String(value)}});
function request(method,value,revision='0'){const bytes=value===undefined?[]:[Buffer.from(JSON.stringify(value))];return{method,headers:{'x-pult-command-id':COMMAND,'x-pult-command-timestamp':TIME,'x-pult-expected-revision':revision},async *[Symbol.asyncIterator](){yield*bytes}}}
function fixture(detail=null){const saved=[],experiments={recordExperiment:async(value,op,{validate}={})=>{await validate?.();saved.push(['experiment',value]);return{ok:true,status:'recorded'}},transitionExperiment:async value=>(saved.push(['transition',value]),{ok:true,status:value.status})},repository={saveCredentials:async value=>(saved.push(value),{ok:true,storeId:value.storeId,configured:true,status:'connected',revision:'1'}),getCredentials:async()=>({clientIdCiphertext:'enc-client',clientSecretCiphertext:'enc-secret',credentialVersion:COMMAND}),connectionStatus:async()=>({stores:[]}),saveSettings:async({settings})=>{if(settings?.mode==='AUTO')throw Object.assign(Error('disabled'),{code:'AUTO_DISABLED'});return{ok:true}},recordConnectionTest:async(storeId,value)=>({storeId,...value,status:value.ok?'connected':'error',checkedAt:new Date(value.checkedAt).toISOString()})},routes=createOptimizerRoutes({optimizer:{prices:async()=>({items:[]}),ads:async()=>({items:[]}),sku:async()=>detail,settings:async()=>({})},repository,experiments,transport:{invalidateCredentials(){},testConnection:async()=>({ok:true})},producer:{request:async()=>({attempts:{'ozon-performance':'attempt'}})},storesRepository:{protectedStore:async()=>({market:'Ozon'})},protect:async(value,decrypt)=>decrypt?value.replace('enc-',''):`enc-${value}`,authorize:async()=>true,now:()=>new Date(TIME)});return{routes,saved}}
test('credential save protects both values and response contains no secret or ciphertext',async()=>{const f=fixture(),secret='fixture-secret-123',clientId='client-id',res=response();await f.routes.handle(request('POST',{storeId:'1',clientId,clientSecret:secret,expectedRevision:'0'}),res,new URL('http://local/api/optimizer/performance/credentials'));assert.equal(res.status,200);assert.equal(res.text.includes(secret),false);assert.equal(res.text.includes(clientId),false);assert.equal(res.text.includes('enc-'),false);assert.equal(f.saved[0].clientIdCiphertext,'enc-client-id');assert.equal(f.saved[0].clientSecretCiphertext,'enc-fixture-secret-123');assert.match(f.saved[0].intentHash,/^[a-f0-9]{64}$/u)});
test('status is a safe GET and AUTO settings are rejected',async()=>{const f=fixture(),status=response();await f.routes.handle(request('GET'),status,new URL('http://local/api/optimizer/performance/status'));assert.equal(status.status,200);assert.deepEqual(JSON.parse(status.text),{stores:[]});const auto=response();await f.routes.handle(request('POST',{settings:{mode:'AUTO'},expectedRevision:'0'}),auto,new URL('http://local/api/optimizer/settings'));assert.equal(auto.status,400)});
test('manual refresh only queues the existing scheduler kind',async()=>{const f=fixture(),res=response();await f.routes.handle(request('POST',{storeId:'1'}),res,new URL('http://local/api/optimizer/performance/refresh'));assert.equal(res.status,202);assert.deepEqual(JSON.parse(res.text),{ok:true,storeId:'1',queued:true,attemptId:'attempt'})});

test('manual price experiment requires a matching observed price and never calls Ozon',async()=>{
  const f=fixture({item:{product:{active:true}},price:{sellerPrice:105},advertising:[]});
  const value={storeId:'1',productId:'42',dimension:'PRICE',beforeValue:100,afterValue:105,observeUntil:'2026-10-01T09:00:00Z',expectedRevision:'0'};
  const ok=response();await f.routes.handle(request('POST',value),ok,new URL('http://local/api/optimizer/experiments'));
  assert.equal(ok.status,200);assert.equal(f.saved.filter(row=>row[0]==='experiment').length,1);
  const wrong=response();await f.routes.handle(request('POST',{...value,afterValue:106}),wrong,new URL('http://local/api/optimizer/experiments'));
  assert.equal(wrong.status,409);assert.equal(f.saved.filter(row=>row[0]==='experiment').length,1);
  const bid=response();await f.routes.handle(request('POST',{...value,dimension:'BID',campaignId:'7',afterValue:5}),bid,new URL('http://local/api/optimizer/experiments'));
  assert.equal(bid.status,409);assert.equal(f.saved.filter(row=>row[0]==='experiment').length,1);
});
