'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const crypto=require('node:crypto');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const create=require('../storage/domains/postgres-report-routes.cjs');
const legacyCategories=require('../order-categories.cjs');
const {typesHash}=require('../ledger.cjs');
const {createPostgresSourceProviders}=require('../storage/postgres-source-providers.cjs');
const DAY='2026-09-20',FROM='2026-09-20',TO='2026-09-20';
function fixture({sourceOverrides={},trueStatsOverride,businessDynamics}={}){const ledger={version:3,complete:true,foreignRecords:0,period:{from:'2026-09-19',to:TO},completedAt:'2026-09-20T12:00:00Z',daily:[{date:DAY,values:{realized:10000,net:8000,commission:1000,logistics:1000,ads:0,acquiring:0,storage:0,penalties:0,other:0,bonus:0,partners:0,reversal:0,unreconciled:0,unreconciledRecords:0,records:1,soldUnits:1,returnedUnits:0,unknownUnitRows:0,salesRows:1}}],skuDaily:[],fees:[]},insight={orders:{period:{from:'2026-09-19',to:TO},updatedAt:'2026-09-20T12:00:00Z',skuDailyCoverage:true,skuUpdatedAt:'2026-09-20T10:00:00Z',daily:[{date:DAY,revenue:120,units:2}],skuDaily:[{date:DAY,sku:'101',revenue:120,units:2}]},errors:[]},wb={complete:true,day:DAY,orderedRevenue:50,orderedUnits:1,points:[{at:'2026-09-20T09:00:00Z',orderedRevenue:50,orderedUnits:1}],orders:[{at:'2026-09-20T09:00:00Z',amount:50,nmId:'201',category:'Хозяйственные товары',subject:'Перчатки'}],fetchedAt:'2026-09-20T09:01:00Z',intervalMinutes:30,source:'/api/v1/supplier/orders'},raw={clientId:'1',market:'Ozon',completedAt:'2026-09-20T12:00:00Z',period:{from:'2026-09-19',to:TO},sections:{},products:[{product_id:1,sku:101,name:'Саморезы',offer_id:'A'}],stocks:[]},catalogs=[{storeId:'1',market:'Ozon',products:[{product_id:1,sku:101,description_category_id:1,type_id:2}],categoryTree:[]},{storeId:'wb-1',market:'WB',products:[{nmID:201,title:'Перчатки'}],categoryTree:[]}],sources={async getReportCatalog(id){return id==='1'?raw:null},async exact(){return null},async getOzonLedger(){return {stamp:'cache-key',data:ledger}},async getInsights(){return[{storeId:'1',value:insight}]},async getWbOrders(){return[{storeId:'wb-1',value:wb}]},async getCatalogs(){return catalogs},...sourceOverrides},storesRepository={async read(){return {'1':{clientId:'1',name:'Ozon',connectedAt:'2026-01-01T00:00:00Z'},'wb-1':{clientId:'wb-1',name:'WB',market:'WB',connectedAt:'2026-01-01T00:00:00Z'}}}},supplierPortals={async read(){return {categories:[]}}},productTypes={async read(){return {available:false}}},intraday={async series(ids,date){return {date,ids,orders:[],finance:[]}}},orderCategoryState={async read(){return {version:1,points:[{date:DAY,at:'2026-09-20T10:00:00Z',values:{Крепёж:{orderedRevenue:120,orderedUnits:2}}}]}}},trueStats=trueStatsOverride||{async compare(input){return {status:'ready',input}}},schedules={async schedule(id){return {orders:{nextAt:'2026-09-20T13:00:00Z'},finance:{nextAt:'2026-09-20T14:00:00Z'},id}},async status(){return[{status:'idle'}]},async job(id){return {id,status:'idle'}},async historyError(){return 'history warning'}};return create({businessDynamics,storesRepository,sourceProviders:sources,supplierPortals,productTypes,intraday,orderCategoryState,trueStats,schedules,now:()=>Date.parse('2026-09-20T12:00:00Z')})}
const params=value=>new URLSearchParams(value);

test('business dynamics GET forwards scope to saved SQL reader and isolates unavailable SQL/errors',async()=>{
 const calls=[],businessDynamics={async read(input){calls.push(input);return {version:1,stores:[],events:[]}}};
 const forbidden=async()=>{throw Error('Existing heavy report sources must not be used')};
 const service=fixture({businessDynamics,sourceOverrides:{getInsights:forbidden,getOrderInsights:forbidden,getReportCatalog:forbidden,getWbOrders:forbidden}});
 const response=()=>({status:null,body:null,writeHead(status){this.status=status;return this},end(body){this.body=JSON.parse(body)}});
 let res=response();assert.equal(await service.handle({method:'GET'},res,new URL('http://localhost/api/business-dynamics?date=2026-09-20&store=wb-1&market=WB')),true);
 assert.equal(res.status,200);assert.deepEqual(calls,[{date:DAY,storeId:'wb-1',market:'WB'}]);assert.deepEqual(res.body.events,[]);
 res=response();await service.handle({method:'POST'},res,new URL('http://localhost/api/business-dynamics'));assert.equal(res.status,405);assert.equal(calls.length,1);
 businessDynamics.read=async()=>{throw Error('secret SQL connection string')};res=response();await service.handle({method:'GET'},res,new URL('http://localhost/api/business-dynamics'));assert.equal(res.status,503);assert.doesNotMatch(JSON.stringify(res.body),/secret/);
 const {DynamicsError}=require('../storage/domains/postgres-business-dynamics.cjs');businessDynamics.read=async()=>{throw new DynamicsError('Магазин не подключён.',404)};
 res=response();await service.handle({method:'GET'},res,new URL('http://localhost/api/business-dynamics'));assert.equal(res.status,404);
 res=response();await fixture().handle({method:'GET'},res,new URL('http://localhost/api/business-dynamics'));assert.equal(res.status,503);
});

test('live SQL insight projection preserves sales, ledger evidence and warnings in reports', async () => {
 const codecs=require('../storage/postgres-live-codecs.cjs');
 const {createLiveSourceProviders}=require('../storage/postgres-live-source-providers.cjs');
 const period={from:'2026-09-19',to:TO},completedAt='2026-09-20T12:00:00Z';
 const types=[{id:32,name:'Logistic'}],warning='Orders update unavailable';
 const insight={orders:{period,updatedAt:completedAt,daily:[{date:'2026-09-19',revenue:60,units:1},{date:DAY,revenue:120,units:2}],skuDaily:[{date:DAY,sku:'101',revenue:120,units:2}],skuCoverage:[DAY]},types,errors:[warning]};
 const evidence={snapshotId:'live:1:7',marketRevision:'7',marketSha256:'a'.repeat(64)};
 const catalog={completedAt,period,products:[],stocks:[],sections:{},_source:evidence};
 const ledger={version:3,complete:true,period,completedAt,daily:[{date:DAY,values:{realized:10000,net:8000,records:1}}],skuDaily:[],fees:[]};
 const providers=createLiveSourceProviders({sources:{
  identity:codecs.parseSourcePath,
  async listSources(){return [{sourcePath:'insights-1.json'}]},
  async record(sourcePath,options){
   const encoded=codecs.encode(sourcePath,insight);
   const collections=Object.fromEntries(Object.entries(encoded.collections).filter(([key])=>!options?.entities||options.entities.includes(key)));
   return {revision:'1',value:codecs.decode(sourcePath,{metadata:encoded.metadata,collections},{partial:!!options?.entities})};
  }
 }});
 const service=fixture({sourceOverrides:{getInsights:providers.getInsights,async getReportCatalog(){return catalog},async getOzonLedger(){return {source:{...evidence,typesSha256:typesHash(types)},data:ledger}}}});
 const result=await service.insights(params({store:'1',from:FROM,to:TO}));
 assert.equal(result.coverage.orders,true);
 assert.equal(result.metrics.orderedRevenue.current,120);
 assert.equal(result.metrics.orderedRevenue.previous,60);
 assert.equal(result.metrics.orderedUnits.current,2);
 assert.equal(result.daily[0].orderedRevenue,120);
 assert.equal(result.coverage.finance,true);
 assert.equal(result.metrics.net.current,80);
 assert.deepEqual(result.sources[0].errors,[warning]);
 assert.deepEqual((await providers.getInsights())[0].value.orders.skuCoverage,[DAY]);
 // A fully read source with no sales must still display a real zero.
 insight.orders.daily=[];
 const empty=await service.insights(params({store:'1',from:FROM,to:TO}));
 assert.equal(empty.coverage.orders,true);
 assert.equal(empty.metrics.orderedRevenue.current,0);
});
test('insights preserves legacy report, intraday, schedule, jobs and history error shape',async()=>{const service=fixture(),result=await service.insights(params({store:'1',from:FROM,to:TO}));assert.equal(result.days,1);assert.equal(result.intraday.date,DAY);assert.equal(result.refresh.error,'history warning');assert.equal(result.refresh.nextAt,'2026-09-20T13:00:00Z');assert.equal(result.jobs[0].status,'idle');assert.equal(result.syncJobs[0].id,'1');assert.equal(result.metrics.orderedRevenue.current,120);});

test('orders-only report leaves ledger, catalog, costs and full SKU insights cold',async()=>{
 let orderReads=0;
 const forbidden=async()=>{throw Error('Heavy source must not be read for the chart')};
 const service=fixture({sourceOverrides:{getReportCatalog:forbidden,getOzonLedger:forbidden,exact:forbidden,getInsights:forbidden,async getOrderInsights(){orderReads++;return [{storeId:'1',value:{orders:{period:{from:'2026-09-19',to:TO},updatedAt:'2026-09-20T11:55:00Z',daily:[{date:DAY,revenue:120,units:2}]},errors:[]}}]}}});
 const result=await service.insights(params({store:'1',from:FROM,to:TO,scope:'orders'}));
 assert.equal(orderReads,1);assert.equal(result.scope,'orders');assert.equal(result.metrics.orderedRevenue.current,120);assert.equal(result.metrics.orderedUnits.current,2);
 assert.equal(result.metrics.net.current,null);assert.equal(result.metrics.zeroStock.current,null);assert.equal(result.metrics.stocks.current,null);assert.deepEqual(result.products,[]);assert.deepEqual(result.fees,[]);
 assert.equal(result.refresh.error,null,'deferred financial history must not appear as a chart error');
 assert.equal(result.intraday.orders.length,1);assert.equal(result.intraday.orders[0].at,'2026-09-20T11:55:00.000Z');assert.equal(result.intraday.orders[0].orderedRevenue,120);
 assert.equal(result.intraday.orders[0].sourceFromAt,result.intraday.orders[0].at);
});

test('live chart observations never invent current time or use a stale or future source day',async()=>{
 for(const updatedAt of ['2026-09-19T11:00:00Z','2026-09-20T12:01:00Z',null]){
  const service=fixture({sourceOverrides:{async getOrderInsights(){return [{storeId:'1',value:{orders:{period:{from:FROM,to:TO},updatedAt,daily:[{date:DAY,revenue:120,units:2}]},errors:[]}}]}}});
  const result=await service.insights(params({store:'1',from:FROM,to:TO,scope:'orders'}));assert.deepEqual(result.intraday.orders,[]);
 }
 const service=fixture(),historical=await service.insights(params({store:'1',from:'2026-09-19',to:'2026-09-19',scope:'orders'}));
 assert.deepEqual(historical.intraday.orders,[]);
 await assert.rejects(service.insights(params({store:'1',from:FROM,to:TO,scope:'unknown'})),/состав отчёта/);
});
test('insights rejects missing or stale saved ledger without loading the raw market snapshot',async()=>{for(const saved of [null,{version:3,complete:true,period:{from:'2026-09-19',to:TO},completedAt:'2026-09-20T11:59:59Z',daily:[],skuDaily:[],fees:[]}]){let rawReads=0;const service=fixture({sourceOverrides:{async getOzonLedger(){return saved},async getMarketSnapshot(){rawReads++;throw Error('raw snapshot must stay cold')}}}),result=await service.insights(params({store:'1',from:FROM,to:TO}));assert.equal(result.coverage.finance,false);assert.equal(result.metrics.net.current,null);assert.equal(result.metrics.orderedRevenue.current,120);assert.equal(rawReads,0)}});
test('enriched ledger evidence must match current SQL snapshot and insight types',async()=>{const digest='a'.repeat(64),source={snapshotId:'11111111-1111-4111-8111-111111111111',marketRevision:'7',marketSha256:digest},catalog={completedAt:'2026-09-20T12:00:00Z',period:{from:'2026-09-19',to:TO},sections:{stocks:{ok:true}},products:[],stocks:[],_source:source},ledger={version:3,complete:true,period:catalog.period,completedAt:catalog.completedAt,daily:[],skuDaily:[],fees:[]},saved={stamp:catalog.completedAt,source:{...source,typesSha256:typesHash([])},data:ledger},matching=await fixture({sourceOverrides:{async getReportCatalog(){return catalog},async getOzonLedger(){return saved}}}).insights(params({store:'1',from:FROM,to:TO}));assert.equal(matching.coverage.finance,true);const stale=await fixture({sourceOverrides:{async getReportCatalog(){return catalog},async getOzonLedger(){return{...saved,source:{...saved.source,marketRevision:'6'}}}}}).insights(params({store:'1',from:FROM,to:TO}));assert.equal(stale.coverage.finance,false)});
test('sources, WB orders and economics compare use saved SQL shapes without refresh calls',async()=>{const service=fixture(),sources=await service.insightSources();assert.equal(sources.stores[0].data.orders.daily[0].units,2);const wb=await service.wbOrders(params({store:'wb-1',date:DAY}));assert.equal(wb.metrics.orderedRevenue.current,50);assert.equal(wb.coverage.orders,true);const comparison=await service.economicsCompare(params({store:'1',from:FROM,to:TO}));assert.equal(comparison.status,'ready');assert.deepEqual(comparison.input.period,{from:FROM,to:TO});});
test('economics GET uses the cache-only TrueStats reader and only queues a background refresh',async()=>{let reads=0,external=0,queued=0;const service=fixture({trueStatsOverride:{async readCompare(){reads++;return {status:'pending',metrics:{profit:null},fetchedAt:null}},refreshCompare(){queued++;return true},async compare(){external++;throw Error('external refresh must stay outside HTTP')}}}),response={status:null,body:null,writeHead(status){this.status=status;return this},end(body){this.body=JSON.parse(body)}};await service.handle({method:'GET'},response,new URL(`http://localhost/api/economics/compare?store=1&from=${FROM}&to=${TO}`));assert.equal(response.status,200);assert.equal(response.body.status,'pending');assert.equal(response.body.metrics.profit,null);assert.equal(reads,1);assert.equal(queued,1);assert.equal(external,0);});
test('order categories reads durable history and current legacy source shapes without writing',async()=>{const report=await fixture().orderCategories(params({date:DAY}));assert.equal(report.date,DAY);assert.ok(report.series.some(row=>row.market==='Ozon'));assert.ok(report.series.some(row=>row.market==='WB'));assert.match(report.limitations.join(' '),/не складываются/u);});
test('order categories uses the SKU-only insight projection when available',async()=>{let categoryReads=0,fullReads=0;const insight={orders:{skuDailyCoverage:true,skuUpdatedAt:'2026-09-20T10:00:00Z',skuDaily:[{date:DAY,sku:'101',revenue:120,units:2}]}};const service=fixture({sourceOverrides:{async getCategoryInsights(){categoryReads++;return[{storeId:'1',value:insight}]},async getInsights(){fullReads++;throw Error('full insights must stay cold')}}});const report=await service.orderCategories(params({date:DAY}));assert.equal(categoryReads,1);assert.equal(fullReads,0);assert.ok(report.series.some(row=>row.market==='Ozon'));});
test('order categories reads only the requested day from native category state',async()=>{let nativeReads=0;const service=fixture({sourceOverrides:{async getOrderCategoryState(day){nativeReads++;assert.equal(day,DAY);return{version:1,points:[{date:DAY,at:'2026-09-20T10:00:00Z',values:{Крепёж:{orderedRevenue:120,orderedUnits:2}}}]}}}});const report=await service.orderCategories(params({date:DAY}));assert.equal(nativeReads,1);assert.equal(report.date,DAY);});
function sqlCategoryService({state,stores,registry={available:false}}){const categories=[],catalogs=stores.map(store=>({storeId:store.id,market:store.market,products:store.products,categoryTree:store.categoryTree})),insights=stores.filter(store=>store.market==='Ozon').map(store=>({storeId:store.id,value:{orders:store.orders}})),wb=stores.filter(store=>store.market==='WB').map(store=>({storeId:store.id,value:store.orders}));return create({storesRepository:{async read(){return Object.fromEntries(stores.map(store=>[store.id,{clientId:store.id,name:store.id,market:store.market}]))}},sourceProviders:{async getReportCatalog(){return null},async getOzonLedger(){return null},async exact(){return null},async getInsights(){return insights},async getWbOrders(){return wb},async getCatalogs(){return catalogs}},supplierPortals:{async read(){return {categories}}},productTypes:{async read(){return registry}},intraday:{async series(){return {}}},orderCategoryState:{async read(){return structuredClone(state)}},trueStats:{async compare(){return {}}},schedules:{async schedule(){return {}},async status(){return []},async job(){return null},async historyError(){return null}}})}
async function parityCase(t,{state,stores,registry={available:false}}){const privateDir=fs.mkdtempSync(path.join(os.tmpdir(),'report-parity-'));t.after(()=>fs.rmSync(privateDir,{recursive:true,force:true}));fs.writeFileSync(path.join(privateDir,'order-category-intraday.json'),JSON.stringify(state));const legacy=legacyCategories.create({privateDir,productTypes:{read:()=>registry},now:()=>Date.parse('2026-09-20T12:00:00Z')}).report({stores,categories:[],date:DAY});assert.deepEqual(await sqlCategoryService({state,stores,registry}).orderCategories(params({date:DAY})),legacy)}
test('SQL order categories exactly matches legacy aliases and missing categories',async t=>{await parityCase(t,{state:{version:1,points:[{date:DAY,at:'2026-09-20T08:00:00.000Z',values:{'Клейкая лента канцелярская':{orderedRevenue:10,orderedUnits:1}}},{date:DAY,at:'2026-09-20T09:00:00.000Z',values:{'Малярная лента':{orderedRevenue:20,orderedUnits:2},'Круг отрезной':{orderedRevenue:7,orderedUnits:1}}}]},stores:[{id:'1',market:'Ozon',products:[],categoryTree:[],orders:{skuDailyCoverage:false,skuDaily:[]}}]})});
test('SQL order categories exactly matches legacy incomplete coverage',async t=>{await parityCase(t,{state:{version:1,points:[]},stores:[{id:'1',market:'Ozon',products:[],categoryTree:[],orders:{skuDailyCoverage:false,skuDaily:[]}},{id:'wb-1',market:'WB',products:[],categoryTree:[],orders:{complete:false,day:DAY,orders:[]}}]})});
test('SQL and legacy both reject an unknown stored type in the active taxonomy',async t=>{const state={version:2,points:[{date:DAY,at:'2026-09-20T08:00:00.000Z',taxonomyRevision:'types-1',values:{missing:{orderedRevenue:1,orderedUnits:1}}}]},stores=[{id:'1',market:'Ozon',products:[],categoryTree:[],orders:{skuDailyCoverage:false,skuDaily:[]}}],registry={available:true,revision:'types-1',types:[{id:'known',parentId:null,name:'Known'}],assignments:{},rules:[]},privateDir=fs.mkdtempSync(path.join(os.tmpdir(),'report-parity-error-'));t.after(()=>fs.rmSync(privateDir,{recursive:true,force:true}));fs.writeFileSync(path.join(privateDir,'order-category-intraday.json'),JSON.stringify(state));assert.throws(()=>legacyCategories.create({privateDir,productTypes:{read:()=>registry}}).report({stores,categories:[],date:DAY}),/неполные суммы, количество или тип/u);await assert.rejects(()=>sqlCategoryService({state,stores,registry}).orderCategories(params({date:DAY})),/неполные суммы, количество или тип/u)});
test('HTTP handler keeps legacy paths, query names and status codes',async()=>{const service=fixture(),response={status:null,headers:null,body:null,writeHead(status,headers){this.status=status;this.headers=headers;return this},end(body){this.body=JSON.parse(body)}};assert.equal(await service.handle({method:'GET'},response,new URL(`http://localhost/api/insights?store=missing&from=${FROM}&to=${TO}`)),true);assert.equal(response.status,404);assert.match(response.body.error,/Магазин/u);assert.equal(await service.handle({method:'GET'},response,new URL('http://localhost/api/not-owned')),false);});
const integrationUrl=process.env.PULT_TEST_DATABASE_URL;
test('report routes read legacy insight source through real PostgreSQL catalog', {skip:!integrationUrl}, async t=>{assert.match(decodeURIComponent(new URL(integrationUrl).pathname.slice(1)),/^pult_test_/u);const {Pool}=require('pg'),pool=new Pool({connectionString:integrationUrl}),schema=`reports_${crypto.randomBytes(8).toString('hex')}`;let owned=false;t.after(async()=>{if(owned)await pool.query(`DROP SCHEMA "${schema}" CASCADE`);await pool.end()});await pool.query(require('../storage/postgres-schema.cjs').replace(/\bpult\b/gu,schema));owned=true;await pool.query(require('../storage/postgres-document-schema.cjs').replace(/\bpult\b/gu,schema));const sourcePath='insights-1.json',value={orders:{period:{from:FROM,to:TO},daily:[{date:DAY,revenue:0,units:0}]}},content=Buffer.from(JSON.stringify(value)),digest=crypto.createHash('sha256').update(content).digest(),key='file/'+crypto.createHash('sha256').update(sourcePath).digest('hex');await pool.query(`INSERT INTO "${schema}".document_states(logical_key,media_type,content,sha256,revision,deleted) VALUES($1,'application/json',$2,$3,1,false)`,[key,content,digest]);await pool.query(`INSERT INTO "${schema}".source_files(source_path,logical_key,domain,media_type,source_bytes,source_sha256,baseline_present) VALUES($1,$2,'market-snapshots','application/json',$3,$4,true)`,[sourcePath,key,content.length,digest]);const sourceProviders=createPostgresSourceProviders({pool,stateSchema:schema}),service=create({storesRepository:{async read(){return {'1':{clientId:'1',name:'Ozon'}}}},sourceProviders,supplierPortals:{async read(){return {categories:[]}}},productTypes:{async read(){return {available:false}}},intraday:{async series(){return {}}},orderCategoryState:{async read(){return {version:1,points:[]}}},trueStats:{async compare(){return {}}},schedules:{async schedule(){return {}},async status(){return[]},async job(){return null},async historyError(){return null}}});assert.deepEqual((await service.insightSources()).stores,[{id:'1',name:'Ozon',data:value}]);});
