'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {createPostgresSourceProviders}=require('../storage/postgres-source-providers.cjs');
const row=(sourcePath,value)=>{const content=Buffer.from(JSON.stringify(value));return {source_path:sourcePath,domain:'market-snapshots',source_media_type:'application/json',media_type:'application/json',content,sha256:crypto.createHash('sha256').update(content).digest(),deleted:false}};
function fake(rows){return {async query(sql,args){if(sql.includes('WHERE s.source_path=$1'))return {rows:rows.filter(item=>item.source_path===args[0])};const prefix=args[0].replace(/\\([%_\\])/g,'$1').slice(0,-1);return {rows:rows.filter(item=>item.source_path.startsWith(prefix)).sort((a,b)=>a.source_path.localeCompare(b.source_path))}}}}
test('exact market providers preserve unknown fields and derive explicit product identity',async()=>{const source=row('data-1.json',{products:[{product_id:7,name:'P'}],sections:{finance:{ok:false}}}),p=createPostgresSourceProviders({pool:fake([source])});assert.equal((await p.getMarketSnapshot('1')).sections.finance.ok,false);assert.deepEqual(await p.getProducts('1'),[{product_id:7,name:'P',storeId:'1',key:'1:7'}]);assert.equal((await p.getCatalog('1')).products[0].product_id,7);});
test('buyer providers select exact complete period and newest retry without double counting',async()=>{const rows=[row('buyer-order-segments-2026-09-01_2026-09-07.json',{id:'base'}),row('buyer-order-segments-2026-09-01_2026-09-07-retry-2.json',{id:'retry'}),row('buyer-order-segments-2026-09-01_2026-09-07-retry-3.partial.json',{id:'partial'}),row('buyer-product-segments-2026-09-01_2026-09-07.json',{id:'product'})],p=createPostgresSourceProviders({pool:fake(rows)});assert.equal((await p.getBuyerOrderSnapshot({from:'2026-09-01',to:'2026-09-07'})).id,'retry');assert.equal((await p.getBuyerProductSnapshot({from:'2026-09-01',to:'2026-09-07'})).id,'product');assert.deepEqual((await p.getBuyerOrderSnapshots({from:'2026-09-03',to:'2026-09-04'})).map(value=>value.id),['retry']);});
test('catalog queries post-filter allowlisted paths and reject corrupt hashes and store ids',async()=>{const valid=row('insights-1.json',{orders:{value:null}}),unclassified=row('insights-secret.json',{secret:true}),p=createPostgresSourceProviders({pool:fake([valid,unclassified])});assert.deepEqual(await p.getInsights(),[{storeId:'1',value:{orders:{value:null}}}]);valid.sha256=Buffer.alloc(32);await assert.rejects(p.getInsights(),error=>error.code==='CORRUPT_SOURCE');await assert.rejects(p.getMarketSnapshot('../1'),error=>error.code==='INVALID_STORE');});
test('legacy funnel wrapper, undated snapshot load and filename catalog identity are preserved',async()=>{const wrapper={version:1,snapshot:{version:1,complete:true},status:'ready',retryAt:null},partial={records:[],report:{coverage:{sources:[{complete:false}]}}},rows=[row('ozon-funnel-1.json',wrapper),row('buyer-order-segments-2026-09-01_2026-09-07.partial.json',partial),row('order-category-catalog-wb-2.json',{products:[]})],p=createPostgresSourceProviders({pool:fake(rows)});assert.deepEqual(await p.getOzonFunnel('1'),wrapper);assert.deepEqual(await p.getSnapshots(),[partial]);assert.deepEqual(await p.getCatalogs(),[{products:[],storeId:'wb-2',market:'WB'}]);});
const integrationUrl=process.env.PULT_TEST_DATABASE_URL;
const restrictedUrl=process.env.PULT_TEST_RESTRICTED_DATABASE_URL;
test('PostgreSQL restricted source catalog reads verified mappings with SELECT only', {skip:!integrationUrl||!restrictedUrl}, async t=>{assert.match(decodeURIComponent(new URL(integrationUrl).pathname.slice(1)),/^pult_test_/u);const {Pool}=require('pg'),owner=new Pool({connectionString:integrationUrl}),restricted=new Pool({connectionString:restrictedUrl}),schema=`sources_${crypto.randomBytes(8).toString('hex')}`,role=decodeURIComponent(new URL(restrictedUrl).username);assert.match(role,/^[a-zA-Z_][a-zA-Z0-9_]*$/u);let owned=false;t.after(async()=>{await restricted.end();if(owned)await owner.query(`DROP SCHEMA "${schema}" CASCADE`);await owner.end()});await owner.query(require('../storage/postgres-schema.cjs').replace(/\bpult\b/gu,schema));owned=true;await owner.query(require('../storage/postgres-document-schema.cjs').replace(/\bpult\b/gu,schema));async function insert(sourcePath,value){const content=Buffer.from(JSON.stringify(value)),digest=crypto.createHash('sha256').update(content).digest(),key='file/'+crypto.createHash('sha256').update(sourcePath).digest('hex');await owner.query(`INSERT INTO "${schema}".document_states(logical_key,media_type,content,sha256,revision,deleted) VALUES($1,'application/json',$2,$3,1,false)`,[key,content,digest]);await owner.query(`INSERT INTO "${schema}".source_files(source_path,logical_key,domain,media_type,source_bytes,source_sha256,baseline_present) VALUES($1,$2,'market-snapshots','application/json',$3,$4,true)`,[sourcePath,key,content.length,digest])}await insert('data-1.json',{products:[{product_id:9}]});await insert('buyer-order-segments-2026-09-01_2026-09-07.json',{records:[]});await owner.query(`GRANT USAGE ON SCHEMA "${schema}" TO "${role}"; GRANT SELECT ON "${schema}".document_states,"${schema}".source_files TO "${role}"`);const providers=createPostgresSourceProviders({pool:restricted,stateSchema:schema});assert.equal((await providers.getProducts('1'))[0].key,'1:9');assert.deepEqual(await providers.getBuyerOrderSnapshot({from:'2026-09-01',to:'2026-09-07'}),{records:[]});});
