'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const create=require('../storage/domains/postgres-order-category-capture.cjs');
const digest=value=>crypto.createHash('sha256').update(value).digest();
const command=(id,time='2026-09-22T08:00:00.000Z')=>({commandId:id,timestamp:time});
const C1='11111111-1111-4111-8111-111111111111',C2='22222222-2222-4222-8222-222222222222';
function memory(unknown){let current=null;const commands=new Map();return{async read(){return current},async readCommand(_key,id){return commands.get(id)||null},async write(_key,content,options){const old=commands.get(options.commandId);if(old){if(!old.after.content.equals(content))throw Object.assign(Error(),{code:'COMMAND_ID_REUSED'});return{revision:old.after.revision,replayed:true}}if((current?.revision||'0')!==options.expectedRevision)throw Object.assign(Error(),{code:'REVISION_CONFLICT'});const before=current||{revision:'0',mediaType:null,content:null,sha256:null,deleted:null},after={revision:String(BigInt(options.expectedRevision)+1n),mediaType:'application/json',content:Buffer.from(content),sha256:digest(content),deleted:false};current=after;commands.set(options.commandId,{before,after});if(unknown===options.commandId){unknown=null;throw Object.assign(Error(),{code:'OUTCOME_UNKNOWN'})}return{revision:after.revision,replayed:false}},async remove(){}}}
const input=()=>({date:'2026-09-22',stores:[{id:'1',market:'Ozon',products:[{product_id:1,sku:101}],categoryTree:[],orders:{skuDailyCoverage:true,skuUpdatedAt:'2026-09-22T07:00:00.000Z',skuDaily:[{date:'2026-09-22',sku:'101',revenue:10.25,units:2}]}}],categories:[],registry:{available:false},evidence:[{sourcePath:'insights-1.json',revision:'1',sha256:'a'.repeat(64)}],batchIntentHash:'b'.repeat(64)});
test('category capture persists a fresh readable point and exact replay survives later writes',async()=>{const state=memory(C1),service=create({stateStore:state}),first=input();await assert.rejects(service.capture(first,command(C1)),{code:'OUTCOME_UNKNOWN'});const second=input();second.stores[0].orders.skuUpdatedAt='2026-09-22T07:30:00.000Z';await service.capture(second,command(C2,'2026-09-22T08:30:00.000Z'));const replay=await service.capture(first,command(C1));assert.equal(replay.replayed,true);assert.equal(replay.pointCount,1);assert.equal((await service.read()).points.length,2);const changed=input();changed.date='2026-09-21';await assert.rejects(service.capture(changed,command(C1)),{code:'COMMAND_ID_REUSED'});});
test('category capture detaches input before SQL and validates evidence',async()=>{const state=memory(),original=state.readCommand.bind(state);let entered,release;const waiting=new Promise(resolve=>{entered=resolve});state.readCommand=async(...args)=>{entered();await new Promise(resolve=>{release=resolve});return original(...args)};const service=create({stateStore:state}),value=input(),pending=service.capture(value,command(C1));await waiting;value.stores[0].orders.skuDaily[0].revenue=999;release();await pending;assert.equal((await service.read()).points[0].values['Не сопоставлено'].orderedRevenue,10.25);const invalid=input();invalid.evidence=[];await assert.rejects(service.capture(invalid,command(C2)),error=>error.public===true);});
