'use strict';const test=require('node:test'),assert=require('node:assert/strict');const {createPostgresScheduler}=require('../storage/acquisition/postgres-scheduler.cjs');
const C='11111111-1111-4111-8111-111111111111',A='22222222-2222-4222-8222-222222222222';
function repo(){let row=null,journal=new Map();return{read:async()=>row,readCommand:async id=>journal.get(id)||null,compareAndSet:async(value,o)=>{const before={revision:o.expectedRevision,value:row?.value?structuredClone(row.value):null},revision=String(BigInt(row?.revision||'0')+1n);row={value:structuredClone(value),revision,deleted:false};journal.set(o.commandId,{before,after:structuredClone(row)});return{revision,replayed:false}}};}
const input=(state='running')=>({kind:'market',storeId:'1',expectedRevision:'0',commandId:C,attemptId:A,timestamp:'2026-09-22T10:00:00Z',nextDueAt:'2026-09-22T10:10:00Z',state,stage:'collect',count:0,errorCodes:[],documentRevision:'1'});
test('scheduler journals deterministic jobs and exact replay without rebuilding intent',async()=>{const scheduler=createPostgresScheduler({repository:repo()}),first=await scheduler.transition(input());assert.equal(first.replayed,false);const replay=await scheduler.transition(input());assert.equal(replay.replayed,true);assert.equal((await scheduler.jobsProvider())['1'].status,'running');await assert.rejects(scheduler.transition({...input(),stage:'changed'}),{code:'COMMAND_ID_REUSED'});});
test('unknown attempt is held and cannot start a fresh payload',async()=>{const r=repo(),scheduler=createPostgresScheduler({repository:r});await scheduler.transition(input('unknown'));await assert.rejects(scheduler.transition({...input('running'),commandId:'33333333-3333-4333-8333-333333333333',expectedRevision:'1'}),{code:'UNKNOWN_OUTCOME_HOLD'});});
test('stale runner cannot complete a replaced attempt and unknown requeue needs explicit resolution',async()=>{const r=repo(),scheduler=createPostgresScheduler({repository:r});await scheduler.transition(input('queued'));const running={...input('running'),commandId:'33333333-3333-4333-8333-333333333333',expectedRevision:'1',runnerId:'runner-a',expectedAttemptId:A,expectedState:'queued',expectedRunnerId:null};await scheduler.transition(running);await assert.rejects(scheduler.transition({...running,state:'done',commandId:'44444444-4444-4444-8444-444444444444',expectedRevision:'2',expectedRunnerId:'runner-b'}),{code:'JOB_CONFLICT'});const unknown={...running,state:'unknown',commandId:'55555555-5555-4555-8555-555555555555',expectedRevision:'2',expectedState:'running',expectedRunnerId:'runner-a',runnerId:null};await scheduler.transition(unknown);await assert.rejects(scheduler.transition({...unknown,state:'queued',attemptId:'66666666-6666-4666-8666-666666666666',commandId:'77777777-7777-4777-8777-777777777777',expectedRevision:'3',expectedState:'unknown',expectedRunnerId:null}),{code:'UNKNOWN_OUTCOME_HOLD'});});
test('scheduler journals an immutable refresh-all target set',async()=>{const scheduler=createPostgresScheduler({repository:repo()}),value={commandId:C,timestamp:'2026-09-22T10:00:00.000Z',kind:'insights-full',targets:[{storeId:'2',documentRevision:'8'},{storeId:'1',documentRevision:'7'}]},first=await scheduler.captureRequest(value),replay=await scheduler.captureRequest({...value,targets:[{storeId:'1',documentRevision:'9'},{storeId:'3',documentRevision:'1'}]});assert.deepEqual(first.targets,[{storeId:'1',documentRevision:'7'},{storeId:'2',documentRevision:'8'}]);assert.deepEqual(replay.targets,first.targets);assert.equal(replay.replayed,true);await assert.rejects(scheduler.captureRequest({...value,timestamp:'2026-09-22T10:00:01.000Z'}),{code:'COMMAND_ID_REUSED'})});
test('refresh-all capture retries only a confirmed CAS conflict with immutable intent',async()=>{let row=null,reads=0,commandReads=0;const revisions=[],captured=[],expected=[{storeId:'1',documentRevision:'7'},{storeId:'2',documentRevision:'8'}];const repository={read:async()=>{reads++;return row&&structuredClone(row)},readCommand:async()=>{commandReads++;return null},compareAndSet:async(value,{expectedRevision})=>{revisions.push(expectedRevision);captured.push(structuredClone(value.requests[C].targets));if(revisions.length===1){row={revision:'1',deleted:false,value:{version:1,jobs:{other:{kind:'other',storeId:'0'}}}};throw Object.assign(Error('conflict'),{code:'REVISION_CONFLICT'})}row={revision:'2',deleted:false,value:structuredClone(value)};return{revision:'2',replayed:false}}},scheduler=createPostgresScheduler({repository}),targets=[{storeId:'2',documentRevision:'8'},{storeId:'1',documentRevision:'7'}],pending=scheduler.captureRequest({commandId:C,timestamp:'2026-09-22T10:00:00.000Z',targets});targets[0].documentRevision='999';targets.push({storeId:'3',documentRevision:'1'});const result=await pending;assert.deepEqual(revisions,['0','1']);assert.equal(reads,2);assert.equal(commandReads,2);assert.deepEqual(captured,[expected,expected]);assert.deepEqual(result.targets,expected);});
