'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const source=require('../buyer-order-segments.cjs'),create=require('../storage/domains/postgres-buyer-order-segments.cjs').create;
const DAY='2026-09-20',stores={1:{name:'Первый'},'wb-1':{name:'Второй',market:'WB'}};
function snapshot(){const record=source.projectOzonPosting({posting_number:'order-1',created_at:DAY+'T09:00:00Z',products:[{quantity:2}],analytics_data:{is_legal:true},status:'awaiting_deliver'},{scheme:'FBO',storeId:'1',storeName:'Первый'});return {records:[record],report:{coverage:{sources:[{market:'Ozon',scheme:'FBO',storeId:'1',name:'Первый',from:DAY,to:DAY,available:true,complete:true,fetchedAt:DAY+'T10:00:00Z'},{market:'Ozon',scheme:'FBS',storeId:'1',name:'Первый',from:DAY,to:DAY,available:true,complete:true,fetchedAt:DAY+'T10:01:00Z'}]}}};}
test('async SQL snapshot preserves legacy public counts, coverage and missing connected sources',async()=>{let reads=0;const service=create({getStores:async()=>structuredClone(stores),getSnapshot:async()=>{reads++;return snapshot()}}),ozon=await service.read({from:DAY,to:DAY,market:'Ozon'}),all=await service.read({from:DAY,to:DAY,market:'all'});assert.equal(reads,2);assert.equal(ozon.status,'ready');assert.equal(ozon.totals.legal.units,2);assert.equal(ozon.source.commonFreshnessAt,DAY+'T10:00:00.000Z');assert.equal('contracts'in ozon.source,false);assert.equal(all.status,'partial');assert.ok(all.coverage.sources.some(row=>row.market==='WB'&&!row.available));});
test('missing snapshot and invalid scope fail closed without invented zero totals',async()=>{const service=create({getStores:async()=>stores,getSnapshot:async()=>null});assert.equal((await service.read({from:DAY,to:DAY,market:'WB'})).totals,null);await assert.rejects(service.read({from:'2026-02-30',to:DAY}),/период/u);await assert.rejects(service.read({from:DAY,to:DAY,storeId:'missing'}),/магазин/u);});
test('daily SQL snapshots form a range without double counting and preserve unknown buyers',async()=>{
 const first=snapshot(),unknown=source.projectOzonPosting({posting_number:'order-2',created_at:'2026-09-21T09:00:00Z',products:[{quantity:3}],analytics_data:{},status:'awaiting_deliver'},{scheme:'FBO',storeId:'1',storeName:'Первый'}),second={generatedAt:'2026-09-21T12:00:00Z',records:[structuredClone(first.records[0]),unknown],report:{coverage:{sources:[{market:'Ozon',scheme:'FBO',storeId:'1',name:'Первый',from:'2026-09-21',to:'2026-09-21',available:true,complete:true,fetchedAt:'2026-09-21T10:00:00Z'},{market:'Ozon',scheme:'FBS',storeId:'1',name:'Первый',from:'2026-09-21',to:'2026-09-21',available:true,complete:true,fetchedAt:'2026-09-21T10:01:00Z'}]}}};
 first.generatedAt='2026-09-20T12:00:00Z';const service=create({getStores:async()=>({1:stores[1]}),getSnapshots:async()=>[first,second]}),result=await service.read({from:'2026-09-20',to:'2026-09-21',market:'Ozon'});
 assert.equal(result.status,'ready');assert.equal(result.totals.legal.units,2);assert.equal(result.totals.individual.units,0);assert.equal(result.totals.unknown.units,3);assert.equal(result.coverage.duplicateRecords,0);assert.equal(result.coverage.sources.every(item=>item.complete),true);
});
test('a gap in daily source coverage remains partial while known records stay visible',async()=>{const only=snapshot();only.generatedAt='2026-09-20T12:00:00Z';const service=create({getStores:async()=>({1:stores[1]}),getSnapshots:async()=>[only]}),result=await service.read({from:'2026-09-20',to:'2026-09-21',market:'Ozon'});assert.equal(result.status,'partial');assert.equal(result.totals.legal.units,2);assert.equal(result.coverage.sources.every(item=>item.complete===false),true);});
test('partial history keeps known records but an empty failed retry cannot claim or erase coverage',async()=>{const known=snapshot(),empty=snapshot();known.generatedAt='2026-09-21T10:00:00Z';known._partialSource=true;known.records[0].createdAt='2026-09-21T09:00:00Z';for(const item of known.report.coverage.sources){item.from='2026-09-21';item.to='2026-09-22'}empty.generatedAt='2026-09-22T10:00:00Z';empty._partialSource=true;empty.records=[];for(const item of empty.report.coverage.sources){item.from='2026-09-21';item.to='2026-09-22';item.complete=false}const service=create({getStores:async()=>({1:stores[1]}),getSnapshots:async()=>[known,empty]}),result=await service.read({from:'2026-09-21',to:'2026-09-22',market:'Ozon'});assert.equal(result.status,'partial');assert.equal(result.totals.legal.units,2);assert.equal(result.totals.individual.units,0);assert.equal(result.totals.unknown.units,0);assert.equal(result.coverage.sources.every(item=>item.available&&!item.complete),true);});
module.exports={};
