'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const create=require('../storage/domains/postgres-conversion.cjs');
const NOW=Date.parse('2026-09-18T12:00:00Z');
function snapshot(){return {version:1,storeId:'oz',complete:true,current:{from:'2026-09-11',to:'2026-09-17'},previous:{from:'2026-09-04',to:'2026-09-10'},updatedAt:'2026-09-18T10:00:00Z',currentRows:[{sku:'1',orderedUnits:8,views:200,cartAdds:30}],previousRows:[{sku:'1',orderedUnits:10,views:250,cartAdds:50}]};}
test('reader analyzes fresh Ozon SQL snapshot and combines a verified WB report',async()=>{const wb={id:'wb',name:'WB',market:'WB',status:'ready',rows:[{id:'w',declining:true}],coverage:{tracked:1,mapped:1,catalog:1,unmapped:0,declining:1,comparable:1},fetchedAt:'2026-09-18T10:00:00Z'};const service=create({getStores:async()=>({oz:{name:'Ozon'},wb:{name:'WB',market:'WB'}}),getProducts:async()=>[{key:'oz:1',storeId:'oz',sku:'1',name:'Товар'}],getOzonFunnel:async()=>({status:'ready',snapshot:snapshot()}),getWbConversion:async()=>wb,now:()=>NOW}),result=await service.read({market:'all'});assert.equal(result.status,'ready');assert.equal(result.rows.length,2);const oz=result.rows.find(row=>row.market==='Ozon');assert.equal(oz.current.orders,8);assert.equal(oz.declining,true);assert.equal(result.coverage.declining,2);});
test('missing provider data remains unavailable and does not become zero',async()=>{let products=0;const service=create({getStores:async()=>({oz:{name:'Ozon'},wb:{name:'WB',market:'WB'}}),getProducts:async()=>{products++;return[]},getOzonFunnel:async()=>({status:'pending'}),getWbConversion:async()=>null,now:()=>NOW}),result=await service.read({market:'all'});assert.equal(result.status,'unavailable');assert.equal(result.rows.length,0);assert.equal(result.coverage.availableStores,0);assert.equal(products,0);assert.deepEqual(result.stores.map(row=>row.code),['pending','wb_unavailable']);});
test('scope filters and invalid provider contracts fail closed without external operations',async()=>{let wb=0;const service=create({getStores:async()=>({oz:{name:'Ozon'}}),getProducts:async()=>[],getOzonFunnel:async()=>({snapshot:{...snapshot(),storeId:'other'},status:'ready'}),getWbConversion:async()=>{wb++;},now:()=>NOW});const result=await service.read({storeId:'oz',market:'Ozon'});assert.equal(result.status,'unavailable');assert.equal(result.stores[0].code,'scope');assert.equal(wb,0);await assert.rejects(service.read({market:'Other'}),/площадки/u);await assert.rejects(service.read({storeId:'missing'}),/подключённый/u);});
test('dependency errors are redacted even when they forge public fields',async()=>{const canary='private-provider-canary',service=create({getStores:async()=>({oz:{name:'Ozon'}}),getProducts:async()=>[],getOzonFunnel:async()=>{throw Object.assign(Error(canary),{public:true,status:400})},getWbConversion:async()=>null,now:()=>NOW}),result=await service.read({market:'Ozon'});assert.equal(result.status,'unavailable');assert.equal(JSON.stringify(result).includes(canary),false);});
