'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const create=require('../storage/domains/postgres-derived-capture.cjs');
const hash=value=>crypto.createHash('sha256').update(value).digest('hex'),ATTEMPT='11111111-1111-4111-8111-111111111111';
function job(){const content=Buffer.from('{"synthetic":true}'),sha256=hash(content),evidence={sourcePath:'data-1.json',revision:'7',sha256};return{content,evidence,value:{attemptId:ATTEMPT,timestamp:'2026-09-22T08:00:00.000Z',payload:{intraday:[{storeId:'1',input:{orders:null,ledger:null,products:[]},evidence:[evidence]}],category:{stores:[],categories:[],registry:{available:false},date:'2026-09-22',evidence:[evidence]},archives:[{sourceFile:'data-1.json',sourceMtime:123,capturedAt:'2026-09-22T08:00:00.000Z',contentHash:sha256,evidence}]}}}}
function fixture(f,{factsStatus='ignored'}={}){const calls=[],records=new Map();let archived=false;const journaledArchive={async addVersion(input){calls.push(['add',input]);archived=true;records.set(input.commandId,{before:{revision:input.expectedRevision}});return{changed:true}},async processVersion(input){calls.push(['process',input]);records.set(input.commandId,{before:{revision:input.expectedRevision}});return{imported:true}}},archiveRead={async latest(){return archived?{contentHash:f.value.payload.archives[0].contentHash}:null},async versionEvidence(sourceFile,contentHash){calls.push(['evidence',sourceFile,contentHash]);return{contentHash,sourceBytes:f.content.length,factsStatus:calls.some(row=>row[0]==='process')?'imported':factsStatus}}},stateStore={async read(){return null},async readCommand(key,id){return records.get(id)||null}};return{calls,journaledArchive,archiveRead,stateStore}}
test('derived capture journals archive writes with deterministic child commands',async()=>{const f=job(),x=fixture(f),service=create({intraday:{async capture(storeId,input,op){x.calls.push(['intraday',storeId,input,op]);return{changed:true}}},categoryCapture:{async capture(input,op){x.calls.push(['category',input,op]);return{changed:true}}},...x,loadSource:async evidence=>({revision:evidence.revision,content:Buffer.from(f.content)})});const first=await service.run(f.value),second=await service.resolve(f.value);assert.equal(first.attemptId,ATTEMPT);assert.equal(second.resolved,true);assert.equal(x.calls.filter(row=>row[0]==='add').length,1,'unchanged source must not duplicate a large command envelope');const add=x.calls.find(row=>row[0]==='add')[1];assert.equal(add.kind,'archive.version-add');assert.equal(add.expectedRevision,'0');assert.deepEqual(add.raw,f.content);const categoryIds=x.calls.filter(row=>row[0]==='category').map(row=>row[2].commandId);assert.equal(new Set(categoryIds).size,1);assert.equal(categoryIds[0]===ATTEMPT,false)});
test('pending archive facts are processed through a second durable command',async()=>{const f=job(),x=fixture(f,{factsStatus:'pending'}),service=create({intraday:{capture:async()=>({})},categoryCapture:{capture:async()=>({})},...x,loadSource:async()=>({revision:'7',content:f.content})});await service.run(f.value);const call=x.calls.find(row=>row[0]==='process')[1];assert.equal(call.kind,'archive.process-exact-pending-version');assert.equal(call.contentHash,f.value.payload.archives[0].contentHash);assert.match(call.commandId,/^[0-9a-f-]{36}$/u)});
test('derived capture fails before archive write when durable source evidence changed',async()=>{const f=job(),x=fixture(f);let writes=0;x.journaledArchive.addVersion=async()=>{writes++};const service=create({intraday:{capture:async()=>({})},categoryCapture:{capture:async()=>({})},...x,loadSource:async()=>({revision:'8',content:f.content})});await assert.rejects(service.run(f.value),/DERIVED_SOURCE_CHANGED/u);assert.equal(writes,0)});
test('live derived capture resolves version references and never creates source archives',async()=>{const evidence={sourcePath:'data-1.json',revision:'9',sha256:'c'.repeat(64)},payload={mode:'live',intraday:[{storeId:'1',sources:[evidence]}],category:{stores:[{id:'1',market:'Ozon',sources:[evidence]}],categories:[],registry:{available:false},date:'2026-09-22',evidence:[evidence]},archives:[]},calls=[],service=create({intraday:{async capture(id,input){calls.push(['intraday',id,input]);return{changed:true}}},categoryCapture:{async capture(input){calls.push(['category',input]);return{changed:true}}},loadDerived:async saved=>{assert.deepEqual(saved,payload);return{intraday:[{storeId:'1',input:{orders:null,ledger:null,products:[]},evidence:[evidence]}],category:{stores:[],categories:[],registry:{available:false},date:'2026-09-22',evidence:[evidence]},archives:[]}}});const result=await service.run({attemptId:ATTEMPT,timestamp:'2026-09-22T08:00:00.000Z',payload});assert.deepEqual(result.archives,[]);assert.equal(calls.filter(row=>row[0]==='category').length,1);assert.equal(calls.filter(row=>row[0]==='intraday').length,1)});
