'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const create = require('../storage/domains/postgres-intraday.cjs');
const { createStateStore } = require('../storage/postgres-state.cjs');
const hash = value => crypto.createHash('sha256').update(value).digest(), command = value => ({ commandId: `${value.repeat(8)}-${value.repeat(4)}-4${value.repeat(3)}-8${value.repeat(3)}-${value.repeat(12)}`, timestamp: `2026-09-22T10:00:0${value}Z` });
function memory(unknown) { const records = new Map(), commands = new Map(); return { records, async read(k) { return records.get(k) || null; }, async readCommand(k, id) { return commands.get(id) || null; }, async write(k, content, options) { const replay = commands.get(options.commandId); if (replay) { if (!replay.after.content.equals(content)) throw Object.assign(Error(), { code: 'COMMAND_ID_REUSED' }); return { revision: replay.after.revision }; } const current = records.get(k); if ((current?.revision || '0') !== options.expectedRevision) throw Object.assign(Error(), { code: 'REVISION_CONFLICT' }); const before = current || { revision: '0', absent: true, deleted: null, mediaType: null, content: null, sha256: null }, after = { revision: String(BigInt(options.expectedRevision) + 1n), mediaType: options.mediaType, content: Buffer.from(content), sha256: hash(content), deleted: false }; records.set(k, after); commands.set(options.commandId, { before, after }); if (unknown === options.commandId) { unknown = null; throw Object.assign(Error('hidden'), { code: 'OUTCOME_UNKNOWN' }); } return { revision: after.revision }; }, async remove() {} }; }
const orders = at => ({ updatedAt: at, period: { from: '2026-09-22', to: '2026-09-22' }, daily: [{ date: '2026-09-22', revenue: 10.25, units: 2 }] });
test('capture keeps distinct observations, exact zero semantics and fresh async series', async () => { const state = memory(), service = create({ stateStore: state }); assert.deepEqual(await service.capture('1', { orders: orders('2026-09-22T07:00:00Z') }, command('1')), { changed: true, pointCount: 1 }); assert.deepEqual(await service.capture('1', { orders: orders('2026-09-22T07:30:00Z') }, command('2')), { changed: true, pointCount: 2 }); const result = await service.series(['1'], '2026-09-22'); assert.equal(result.orders.length, 2); assert.equal(result.orders[0].orderedRevenue, 10.25); assert.equal(result.orders[0].orderedUnits, 2); assert.deepEqual(result.finance, []); });
test('unknown commit retry is exact after later writes and changed command intent is rejected', async () => { const op = command('3'), state = memory(op.commandId), service = create({ stateStore: state }), input = { orders: orders('2026-09-22T08:00:00Z') }; await assert.rejects(service.capture('1', input, op), error => error.code === 'OUTCOME_UNKNOWN'); await service.capture('1', { orders: orders('2026-09-22T08:30:00Z') }, command('4')); assert.deepEqual(await service.capture('1', input, op), { changed: true, pointCount: 1 }); await assert.rejects(service.capture('1', { orders: orders('2026-09-22T09:00:00Z') }, op), error => error.code === 'COMMAND_ID_REUSED'); await assert.rejects(service.capture('1', input, { ...op, timestamp: '2026-09-22T11:00:00Z' }), error => error.code === 'COMMAND_ID_REUSED'); });
test('capture detaches caller input before its first SQL await and keeps only the latest receipt', async () => { const state = memory(), originalRead = state.readCommand.bind(state); let entered, release; const waiting = new Promise(resolve => { entered = resolve; }); state.readCommand = async (...args) => { entered(); await new Promise(resolve => { release = resolve; }); return originalRead(...args); }; const service = create({ stateStore: state }), input = { orders: orders('2026-09-22T07:00:00Z') }, pending = service.capture('1', input, command('6')); await waiting; input.orders.updatedAt = '2026-09-22T09:00:00Z'; release(); await pending; state.readCommand = originalRead; await service.capture('1', { orders: orders('2026-09-22T07:30:00Z') }, command('7')); const stored = JSON.parse([...state.records.values()][0].content); assert.deepEqual(stored.points.map(point => point.at), ['2026-09-22T07:00:00.000Z', '2026-09-22T07:30:00.000Z']); assert.equal(stored.commandResults.length, 1); assert.equal(stored.commandResults[0].commandId, command('7').commandId); });
const integrationUrl = process.env.PULT_TEST_DATABASE_URL;
test('imported finance observations preserve unavailable cost and profit as null', async () => {
  const state = memory(), sourcePath = 'intraday-1.json';
  const original = { version: 1, points: [{ source: 'finance', date: '2026-09-22', at: '2026-09-22T07:00:00.000Z', values: { realized: 1000, net: 800, ads: 0 }, economy: { realized: 10, cogs: null, profit: null } }] };
  const content = Buffer.from(JSON.stringify(original));
  state.records.set(require('../storage/postgres-document-import.cjs').sourceKey(sourcePath), { revision: '1', mediaType: 'application/json', deleted: false, content, sha256: hash(content) });
  const service = create({ stateStore: state });
  const series = await service.series(['1'], '2026-09-22');
  assert.equal(series.finance[0].ourMargin, null);
  assert.equal(series.finance[0].ourRoi, null);
  await service.capture('1', { orders: orders('2026-09-22T08:00:00Z') }, command('8'));
  assert.deepEqual(JSON.parse([...state.records.values()][0].content).points[0], original.points[0]);
  for (const invalid of [undefined, '0', Infinity]) {
    const value = structuredClone(original); value.points[0].economy.cogs = invalid;
    assert.equal(create.validState(value), false);
  }
});
test('PostgreSQL intraday integration persists per-store mapping and reopens history', { skip: !integrationUrl }, async t => { assert.match(decodeURIComponent(new URL(integrationUrl).pathname.slice(1)), /^pult_test_/u); const { Pool } = require('pg'), pool = new Pool({ connectionString: integrationUrl }), schema = `intraday_${crypto.randomBytes(8).toString('hex')}`; let owned = false; t.after(async () => { if (owned) await pool.query(`DROP SCHEMA "${schema}" CASCADE`); await pool.end(); }); await pool.query(require('../storage/postgres-schema.cjs').replace(/\bpult\b/gu, schema)); owned = true; await pool.query(require('../storage/postgres-document-schema.cjs').replace(/\bpult\b/gu, schema)); const state = createStateStore({ pool, schema }), first = create({ stateStore: state }); await first.capture('1', { orders: orders('2026-09-22T07:00:00Z') }, command('5')); assert.equal((await create({ stateStore: state }).series(['1'], '2026-09-22')).orders.length, 1); assert.deepEqual((await pool.query(`SELECT source_path FROM "${schema}".source_files`)).rows, [{ source_path: 'intraday-1.json' }]); });
