'use strict';const test=require('node:test'),assert=require('node:assert/strict');const{createPostgresRuntime}=require('../storage/postgres-runtime-composition.cjs');
test('runtime passes metadata revision reader to the HTTP core',async()=>{
 const crypto=require('node:crypto'),value={'1':{name:'SK',clientId:'1',key:'encrypted',connectedAt:'2026-09-01T00:00:00.000Z'}},content=Buffer.from(JSON.stringify(value));
 const calls=[],stateStore={async read(key){calls.push(['read',key]);return{revision:'1',deleted:false,mediaType:'application/json',content,sha256:crypto.createHash('sha256').update(content).digest()}},async write(){throw Error('unused')},async remove(){throw Error('unused')},async revisions(paths){calls.push(['revisions',paths]);return new Map([['costs-1.json','2'],['prices-1.json','3'],['data-1.json','4']])}};
 const scheduler={load:async()=>{},jobsProvider:async()=>new Map()},pool={query:async()=>({rows:[]}),connect(){}},runtime=createPostgresRuntime({pool,stateStore,scheduler,schedulerRunner:{start(){},close(){}},ownerAdapters:{},ownerRoutesBuilder:()=>({handle(){}}),acquisition:{market:{acquire(){}},costsPrices:{refresh(){}},insights:{refreshOrders(){},refreshFunnel(){}}},readAdapters:{stateStore,scheduler,marketRepository:{getSnapshot:async()=>null}},startServer:async()=>({close(){}})});
 const rows=await runtime.core.publicStores();
 assert.equal(rows[0].snapshotRevision,'4');assert.equal(rows[0].revision,':2:3');
 assert.deepEqual(calls.map(([kind])=>kind),['read','revisions']);
});
test('partial composition stays gated and owner adapters cannot replace root authorize',async()=>{let loaded=0,captured,receivedAuthorize;const stateStore={read:async()=>null,list(){},write(){},remove(){},readCommand(){}};const runner={start(){},close(){}},forged=async()=>true,rootAuthorize=async()=>false;const runtime=createPostgresRuntime({pool:{query:async()=>({rows:[]}),connect(){}},stateStore,scheduler:{load:async()=>{loaded++},jobsProvider:async()=>({})},schedulerRunner:runner,ownerAdapters:{authorize:forged},ownerRoutesBuilder:options=>{receivedAuthorize=options.authorize;return{handle(){}}},acquisition:{market:{acquire(){}},costsPrices:{refresh(){}},insights:{refreshOrders(){},refreshFunnel(){}}},staticDir:'C:\\public',staticFiles:['index.html'],startServer:async options=>{captured=options;options.ownerRoutesFactory({authorize:rootAuthorize});return{close(){}}}});assert.deepEqual(await runtime.readiness(),{ready:false,missingAdapters:['runtime-composition'],passive:false});await runtime.start({port:0});assert.equal(receivedAuthorize,rootAuthorize);assert.notEqual(receivedAuthorize,forged);assert.equal(captured.background[0],runner);assert.equal(captured.port,0);assert.ok(loaded>=1);});
