'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const { createAcquisitionDispatchers } = require('../storage/acquisition/postgres-acquisition-dispatcher.cjs');
const digest = value => crypto.createHash('sha256').update(value).digest();
const job = { kind: 'insights-full', storeId: '1', attemptId: '11111111-1111-4111-8111-111111111111', documentRevision: '4' };
function dependencies(readCommand) { let runs = 0; return { get runs() { return runs; }, value: createAcquisitionDispatchers({ stateStore: { readCommand }, market: { acquire: async () => ({ revision: '1' }) }, costsPrices: { refresh: async () => ({ revision: '1' }) }, insights: { refreshOrders: async input => { runs++; assert.equal(input.mode, 'full'); return { revision: '5', value: { sections: {}, orders: { daily: [1] } } }; }, refreshFunnel: async () => ({ revision: '1' }) }, wbOrders: { refresh: async () => ({ revision: '1' }) } }) }; }
test('dispatcher resolves a committed receipt before any external collection', async () => { const content = Buffer.from(JSON.stringify({ sections: {}, orders: { daily: [1, 2] } })), fixture = dependencies(async () => ({ before: { revision: '4' }, after: { revision: '5', mediaType: 'application/json', content, sha256: digest(content) } })); const result = await fixture.value['insights-full'].resolve(job); assert.equal(result.revision, '5'); assert.equal(result.count, 2); assert.equal(fixture.runs, 0); });
test('dispatcher rejects changed revision and corrupt committed bytes', async () => { let content = Buffer.from('{}'), fixture = dependencies(async () => ({ before: { revision: '3' }, after: { revision: '5', mediaType: 'application/json', content, sha256: digest(content) } })); await assert.rejects(fixture.value['insights-full'].resolve(job), { code: 'COMMAND_ID_REUSED' }); content = Buffer.from([0xc3, 0x28]); fixture = dependencies(async () => ({ before: { revision: '4' }, after: { revision: '5', mediaType: 'application/json', content, sha256: digest(content) } })); await assert.rejects(fixture.value['insights-full'].resolve(job), { code: 'CORRUPT_RECEIPT' }); });
test('dispatcher forwards durable attempt and emits controlled scheduler codes', async () => { const fixture = dependencies(async () => null), result = await fixture.value['insights-full'].run(job); assert.equal(result.revision, '5'); assert.equal(result.count, 1); assert.equal(fixture.runs, 1); const market = createAcquisitionDispatchers({ stateStore: { readCommand: async () => null }, market: { acquire: async () => ({ revision: '2', status: 'partial', errors: ['secret upstream detail'] }) }, costsPrices: { refresh: async () => ({}) }, insights: { refreshOrders: async () => ({}), refreshFunnel: async () => ({}) }, wbOrders: { refresh: async () => ({}) } }); assert.deepEqual((await market.market.run({ ...job, kind: 'market' })).errorCodes, ['MARKET_PARTIAL']); });
test('derived dispatcher uses the immutable scheduler payload for run and recovery',async()=>{const seen=[],dispatchers=createAcquisitionDispatchers({stateStore:{readCommand:async()=>null},market:{acquire:async()=>({})},costsPrices:{refresh:async()=>({})},insights:{refreshOrders:async()=>({}),refreshFunnel:async()=>({})},wbOrders:{refresh:async()=>({})},derivedCapture:{run:async value=>{seen.push(['run',value]);return{intraday:[1],archives:[]}},resolve:async value=>{seen.push(['resolve',value]);return{intraday:[1],archives:[1]}}}}),derived={kind:'derived-capture',storeId:'0',attemptId:job.attemptId,timestamp:'2026-09-22T12:00:00.000Z',payload:{immutable:true}};assert.equal((await dispatchers['derived-capture'].run(derived)).count,2);assert.equal((await dispatchers['derived-capture'].resolve(derived)).count,3);assert.deepEqual(seen[0][1].payload,{immutable:true});});
test('recovery delegates committed market and insight receipts without acquisition calls',async()=>{let external=0,stateReads=0;const dispatchers=createAcquisitionDispatchers({stateStore:{readCommand:async()=>{stateReads++;return null}},market:{acquire:async()=>{external++},resolve:async input=>({revision:'8',status:'done',errors:[],input})},costsPrices:{refresh:async()=>({})},insights:{refreshOrders:async()=>{external++},refreshFunnel:async()=>{external++},resolveOrders:async input=>({revision:'9',value:{sections:{},orders:{daily:[]}},input}),resolveFunnel:async()=>null},wbOrders:{refresh:async()=>({})}});assert.equal((await dispatchers.market.resolve({...job,kind:'market'})).revision,'8');assert.equal((await dispatchers['insights-full'].resolve(job)).revision,'9');assert.equal(external,0);assert.equal(stateReads,0)});
