'use strict';const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const create=require('../storage/domains/postgres-info-routes.cjs'),{createReleaseNotesLoader}=require('../storage/postgres-application.cjs');const{sourceKey}=require('../storage/postgres-document-import.cjs');
const value={donatedRub:10,childrenHomes:2,updatedAt:'2026-09-22T00:00:00Z'},content=Buffer.from(JSON.stringify(value)),record={revision:'1',deleted:false,mediaType:'application/json',content,sha256:crypto.createHash('sha256').update(content).digest()};function res(){return{writeHead(status){this.status=status},end(body){this.body=JSON.parse(body)}}}
test('info routes serve verified SQL impact and injected release notes',async()=>{const routes=create({stateStore:{read:async key=>{assert.equal(key,sourceKey('company-impact.json'));return record},write(){},remove(){}},releaseNotes:{items:[{id:'x'}]}});let out=res();assert.equal(await routes.handle({method:'GET'},out,new URL('http://local/api/impact')),true);assert.deepEqual(out.body,{...value,source:'owner'});out=res();await routes.handle({method:'GET'},out,new URL('http://local/api/changes'));assert.deepEqual(out.body,{items:[{id:'x'}]});});

test('release notes loader rereads a changed file by mtime and rejects malformed replacements',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'release-notes-')),file=path.join(dir,'release-notes.json'),write=(value,seconds)=>{fs.writeFileSync(file,value);const at=new Date(Date.now()+seconds*1000);fs.utimesSync(file,at,at)};t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));write(JSON.stringify({updatedAt:'2026-09-23T10:00:00Z',entries:[{id:'old'}]}),0);const load=createReleaseNotesLoader(file);assert.equal((await load()).entries[0].id,'old');write(JSON.stringify({updatedAt:'2026-09-23T11:00:00Z',entries:[{id:'new'}]}),2);assert.equal((await load()).entries[0].id,'new');write('{broken',4);await assert.rejects(load);write(JSON.stringify({updatedAt:'2026-09-23T12:00:00Z',entries:[{id:'fixed'}]}),6);assert.equal((await load()).entries[0].id,'fixed')});

test('changes route serves the newest valid journal and preserves it when a later read is malformed',async()=>{let next={updatedAt:'2026-09-23T10:00:00Z',entries:[{id:'first'}]},broken=false;const routes=create({stateStore:{read:async()=>record,write(){},remove(){}},releaseNotes:{updatedAt:'2026-09-22T10:00:00Z',entries:[{id:'startup'}]},loadReleaseNotes:async()=>{if(broken)throw Error('malformed');return next}});let out=res();await routes.handle({method:'GET'},out,new URL('http://local/api/changes'));assert.equal(out.body.entries[0].id,'first');next={updatedAt:'2026-09-23T11:00:00Z',entries:[{id:'second'}]};out=res();await routes.handle({method:'GET'},out,new URL('http://local/api/changes'));assert.equal(out.body.entries[0].id,'second');broken=true;out=res();await routes.handle({method:'GET'},out,new URL('http://local/api/changes'));assert.equal(out.status,200);assert.equal(out.body.entries[0].id,'second')});

test('changes route fails safely when no valid journal has ever loaded',async()=>{const routes=create({stateStore:{read:async()=>record,write(){},remove(){}},loadReleaseNotes:async()=>({broken:true})}),out=res();await routes.handle({method:'GET'},out,new URL('http://local/api/changes'));assert.equal(out.status,503);assert.deepEqual(out.body,{error:'Журнал изменений временно недоступен.'})});

test('data update status separates durable success from the current attempt and exposes no payload or stage',async()=>{
 const jobs={
  'market:1':{kind:'market',storeId:'1',state:'queued',timestamp:'2026-09-23T12:40:00Z',nextDueAt:'2026-09-23T12:41:00Z',stage:'private stage',payload:{secret:'never'},errorCodes:[]},
  'insights-today:1':{kind:'insights-today',storeId:'1',state:'error',timestamp:'2026-09-23T12:30:00Z',nextDueAt:'2026-09-23T12:20:00Z',errorCodes:['DATABASE_ERROR','not-safe']}
 };
 let metadataReads=0;const routes=create({stateStore:{read:async()=>record,write(){},remove(){}},releaseNotes:{},storesRepository:{async read(){return{'1':{name:'Магазин',market:'Ozon'}}}},scheduler:{async statusJobs(){return jobs}},async readSourceMetadata(paths){metadataReads++;assert.deepEqual(paths.sort(),['costs-1.json','data-1.json','insights-1.json','ozon-funnel-1.json']);return new Map([['data-1.json',{completedAt:'2026-09-23T12:00:00Z',sections:{products:{ok:true},stocks:{ok:true},finance:{ok:true}}}],['insights-1.json',{orders:{updatedAt:'2026-09-23T12:10:00Z',historyUpdatedAt:'2026-09-23T11:50:00Z'},sections:{orders:{ok:true},types:{ok:true}}}],['costs-1.json',null],['ozon-funnel-1.json',null]])},now:()=>Date.parse('2026-09-23T12:45:00Z')});
 const out=res();await routes.handle({method:'GET'},out,new URL('http://local/api/data-updates'));assert.equal(out.status,200);assert.equal(out.body.checkedAt,'2026-09-23T12:45:00.000Z');
 const market=out.body.jobs.find(row=>row.kind==='market');assert.equal(market.lastSuccessAt,'2026-09-23T12:00:00.000Z');assert.equal(market.attemptAt,'2026-09-23T12:40:00.000Z');assert.equal(market.nextDueKind,'manual');assert.equal(market.nextDueAt,null);assert.equal(metadataReads,1);
 const orders=out.body.jobs.find(row=>row.kind==='insights-today');assert.equal(orders.lastSuccessAt,'2026-09-23T12:10:00.000Z');assert.deepEqual(orders.errorCodes,['DATABASE_ERROR']);assert.equal(orders.nextDueKind,'estimate');assert.equal(orders.nextDueAt,'2026-09-23T12:20:00.000Z');assert.doesNotMatch(JSON.stringify(out.body),/private stage|never|payload/u);
});

test('partial market metadata is not reported as a successful update',async()=>{const routes=create({stateStore:{read:async()=>record,write(){},remove(){}},releaseNotes:{},storesRepository:{async read(){return{'1':{name:'Магазин',market:'Ozon'}}}},scheduler:{async statusJobs(){return{}}},async readSourceMetadata(){return new Map([['data-1.json',{completedAt:'2026-09-23T12:00:00Z',sections:{products:{ok:true},finance:{ok:false}}}],['costs-1.json',null],['insights-1.json',null],['ozon-funnel-1.json',null]])}}),out=res();await routes.handle({method:'GET'},out,new URL('http://local/api/data-updates'));assert.equal(out.body.jobs.find(row=>row.kind==='market').lastSuccessAt,null)});

test('data update status fails closed when metadata readers are unavailable',async()=>{const routes=create({stateStore:{read:async()=>record,write(){},remove(){}},releaseNotes:{}}),out=res();await routes.handle({method:'GET'},out,new URL('http://local/api/data-updates'));assert.equal(out.status,503);assert.deepEqual(out.body,{error:'Статусы обновлений временно недоступны.'});});
