'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {ingest,create}=require('../stock-history.cjs');
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pult-stocks-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const dbFile=path.join(dir,'stocks.sqlite');return {dbFile,api:create({dbFile})}}
const row=(more={})=>({day:'2026-09-07',observedAt:'2026-09-07T07:44:15.694Z',source:'daily-total',storeId:'11',storeName:'Первый',sku:'00123',article:'=TEST',name:'Товар',warehouse:null,warehouseId:null,cluster:null,totalStock:20,available:null,inTransit:0,reserved:null,quality:'Снимок источника',sourceFile:'daily.json',sourceRow:0,...more});
const add=(dbFile,rows,importId='a'.repeat(64))=>ingest({dbFile,rows,importId,manifest:[],issues:[]});
test('keeps sources, stores, observation times and unknown quantities separate',t=>{const {dbFile,api}=setup(t);add(dbFile,[row(),row({storeId:'22',storeName:'Второй',totalStock:9}),row({source:'daily-warehouse',warehouseId:'w',warehouse:'Склад',totalStock:7})]);assert.equal(api.status().records,3);assert.equal(api.status().products,2);const x=api.report({store:'11'});assert.equal(x.total,1);assert.equal(x.rows[0].sku,'00123');assert.equal(x.rows[0].available,null);assert.equal(x.rows[0].inTransit,0);assert.equal(x.rows[0].observedAt,'2026-09-07T07:44:15.694Z');assert.equal(api.report({source:'daily-warehouse'}).total,1)});
test('same import is idempotent and unchanged rows from another import stay single',t=>{const {dbFile,api}=setup(t);add(dbFile,[row()]);assert.equal(add(dbFile,[row()]).duplicate,true);assert.equal(add(dbFile,[row()],'b'.repeat(64)).inserted,0);assert.equal(api.status().records,1)});
test('conflicting historical values preserved, never overwrite current or previous observations',t=>{const {dbFile,api}=setup(t);add(dbFile,[row()]);add(dbFile,[row({totalStock:21})],'b'.repeat(64));assert.equal(api.report().total,2);assert.deepEqual(api.report().rows.map(r=>r.totalStock).sort(),[20,21])});
test('invalid row rolls back whole import and can be corrected under same import id',t=>{const {dbFile,api}=setup(t);assert.throws(()=>add(dbFile,[row(),row({sku:'other',totalStock:-1})]),/остаток/);assert.equal(api.status().records,0);assert.equal(add(dbFile,[row()]).inserted,1)});
test('literal search, date scope, pagination and export use same filter',t=>{const {dbFile,api}=setup(t);add(dbFile,[row({name:'Товар_100%'}),row({sku:'999',day:'2026-09-08',name:'Другой'})]);assert.equal(api.report({q:'_100%'}).total,1);assert.equal(api.report({from:'2026-09-08',to:'2026-09-08'}).total,1);assert.equal(api.report({limit:1,offset:1}).rows[0].sku,'00123');const csv=api.csv({store:'11',sku:'00123'});assert.match(csv,/00123/);assert.match(csv,/'=TEST/);assert.doesNotMatch(csv,/Другой/);assert.equal(csv.split('\r\n').length,2)});
test('rejects malformed filters and handles absence without creating a database',t=>{const {dbFile,api}=setup(t);assert.equal(api.status().records,0);assert.equal(fs.existsSync(dbFile),false);for(const args of [{source:'all'},{from:'2026-02-30'},{from:'2026-10-01',to:'2026-09-01'},{limit:500},{offset:-1}])assert.throws(()=>api.report(args));assert.equal(fs.existsSync(dbFile),false)});
